//! Equations of state.
//!
//! The third namespace, and the first that is not a correlation over pipe or wall
//! geometry. It exists because a cubic equation of state decomposes the same way
//! every other calculation here does - into constitutive coefficients, each with a
//! published source and a worked example - and the decomposition is worth having
//! explicitly, since a wrong coefficient is invisible downstream.
//!
//! * [`pr_kappa`] - the Peng-Robinson alpha-function coefficient
//! * [`pr_alpha_ab`] - the alpha function and the reduced attraction parameters
//! * [`pr_z_factor`] - the compressibility factor, the cubic's real roots
//! * [`pr_departure`] - fugacity coefficient and departure functions
//! * [`pr_molar_volume`] - molar volume, the one dimensional quantity here
//! * [`pr_mass_density`] - mass density, and the end of the path to something useful
//!
//! # Models
//!
//! [`pure_saturation`] is a *model* rather than a calculation: its spec fixes a
//! procedure rather than an equation, and it is generated by `tools/gen_models.py`
//! into [`model_gen`] rather than by `gen_registry.py` into `spec_gen`. It composes
//! the kernels above and adds nothing but a search.
//! * [`prsv_kappa`] - the Stryjek-Vera coefficient, for the same alpha function
//! * [`vdw1f_mix_binary`] - van der Waals one-fluid mixing for a binary
//! * [`rachford_rice_binary`] - the vapour fraction that solves Rachford-Rice
//!
//! # Why the coefficients come first
//!
//! The obvious shape for this namespace is one calc per equation of state, taking
//! a component and returning a Z factor. That shape hides the constants: a
//! transposed digit in the `omega**2` coefficient produces an equation that still
//! runs, still converges and is slightly wrong everywhere, and no check on the Z
//! factor can see it, because the Z factor is computed *from* the coefficient.
//!
//! Splitting the constitutive coefficients out gives each one its own spec, its own
//! worked example and its own cross-language test. It also makes a modification
//! cheap: Peng-Robinson-Stryjek-Vera changes the temperature dependence of
//! `kappa` and nothing else, so under this decomposition it is one new calc rather
//! than a fork of the whole chain.
//!
//! # Dimensionless by construction
//!
//! Everything here works in reduced variables - `Tr`, `Pr`, and the dimensionless
//! coefficients that follow from them. `A = 0.45724 * alpha * Pr / Tr**2` needs no
//! gas constant, no pressure unit and no temperature unit, and the vapour-liquid
//! mixing rule is linear in `A` and `B` exactly as it is in `a` and `b`. That is
//! why this crate has no `uom` dependency: the dimensional conversion belongs at
//! the boundary, in one place, where it can be tested once.

pub mod model_gen;
pub mod pr_alpha_ab;
pub mod pr_departure;
pub mod pr_kappa;
pub mod pr_mass_density;
pub mod pr_molar_volume;
pub mod pr_z_factor;
pub mod prsv_kappa;
pub mod pure_saturation;
pub mod rachford_rice_binary;
pub mod results;
pub mod spec_gen;
pub mod vdw1f_mix_binary;

pub use pr_alpha_ab::{OMEGA_A, OMEGA_B, pr_alpha_ab};
pub use pr_departure::pr_departure;
pub use pr_kappa::pr_kappa;
pub use pr_mass_density::pr_mass_density;
pub use pr_molar_volume::{MOLAR_GAS_CONSTANT, pr_molar_volume};
pub use pr_z_factor::pr_z_factor;
pub use prsv_kappa::prsv_kappa;
pub use pure_saturation::pure_saturation;
pub use rachford_rice_binary::rachford_rice_binary;
pub use results::{
    PrAlphaAbResult, PrDepartureResult, PrKappaResult, PrMassDensityResult, PrMolarVolumeResult,
    PrZFactorResult, PrsvKappaResult, PureSaturationResult, RachfordRiceBinaryResult,
    RootStructure, Vdw1fMixBinaryResult,
};
pub use vdw1f_mix_binary::vdw1f_mix_binary;
