//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_models.py` from:
//!   - specs/models/eos/bubble_pressure.yaml
//!   - specs/models/eos/critical_point.yaml
//!   - specs/models/eos/dew_pressure.yaml
//!   - specs/models/eos/molar_enthalpy_entropy.yaml
//!   - specs/models/eos/ph_flash.yaml
//!   - specs/models/eos/pt_flash.yaml
//!   - specs/models/eos/pure_saturation.yaml
//!   - specs/models/eos/stability_test.yaml
//!
//! Regenerate with `python tools/gen_models.py`; CI runs `--check` and fails
//! on any difference.

use azoth_core::{
    Band, ModelAlgorithm, ModelBracket, ModelSpec, RangeCheck, Severity, SpecCheck, TestCase,
    WarningCode,
};

static BUBBLE_PRESSURE_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "min_t_over_tc",
            min: None,
            min_inclusive: true,
            max: Some(1.0),
            max_inclusive: false,
            equals: None,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "Above the nearest component's critical temperature the mixture may still have a bubble point - a mixture's critical temperature is not any one component's - but the iteration converges more slowly and the answer is less trustworthy. A warning rather than an error because the state is real, and because whether a bubble point exists at all is decided by the guard in the notes rather than by this bound.",
        },
    },
];

static BUBBLE_PRESSURE_CASES: &[TestCase] = &[
    TestCase {
        id: "methane_and_butane_at_300_k",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 300.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599200.0, 3796000.0]),
            ("omega", &[0.01142, 0.2002]),
            ("x", &[0.2, 0.8]),
        ],
        matrices: &[("kij", &[0.0, 0.05, 0.05, 0.0])],
        expected: &[
            ("pressure", 4405971.88524195),
            ("z_liquid", 0.15923644847947147),
            ("z_vapour", 0.8559280792104562),
            ("min_t_over_tc", 0.7056831012420023),
            ("iterations", 23.0),
        ],
        expected_vectors: &[
            ("incipient", &[0.8954934205328267, 0.10450657946717332]),
            ("k", &[4.477467102662785, 0.1306332243339273]),
        ],
    },
    TestCase {
        id: "methane_propane_and_butane_at_320_k",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 320.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 369.83, 425.12]),
            ("Pc", &[4599200.0, 4248000.0, 3796000.0]),
            ("omega", &[0.01142, 0.1523, 0.2002]),
            ("x", &[0.2, 0.3, 0.5]),
        ],
        matrices: &[("kij", &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])],
        expected: &[
            ("pressure", 4562186.628738893),
            ("z_liquid", 0.1619174258974364),
            ("z_vapour", 0.7941260235229536),
            ("min_t_over_tc", 0.7527286413248024),
            ("iterations", 29.0),
        ],
        expected_vectors: &[
            (
                "incipient",
                &[0.7222910363935799, 0.15937358543476263, 0.11833537817165739],
            ),
            (
                "k",
                &[3.6114551819644003, 0.5312452847820274, 0.23667075634308543],
            ),
        ],
    },
];

static BUBBLE_PRESSURE_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "bubble_pressure_successive_substitution",
    convergence: "absolute",
    tolerance: 1e-12,
    max_iterations: 200,
    bracket: None,
    initialisation: Some("wilson_raoult"),
    inner: None,
};

/// Registry entry for `eos.bubble_pressure`.
pub static BUBBLE_PRESSURE_SPEC: ModelSpec = ModelSpec {
    id: "eos.bubble_pressure",
    kind: "procedure",
    algorithm: Some(&BUBBLE_PRESSURE_ALGORITHM),
    checks: BUBBLE_PRESSURE_CHECKS,
    cases: BUBBLE_PRESSURE_CASES,
};

static CRITICAL_POINT_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "Tc",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "the critical temperature of the composition searched for. The iteration is perfectly capable of leaving the region where the equation of state has a critical point and converging on a temperature that is not a state, and this is the check that says so rather than returning it.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "Pc",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "the pressure at the returned volume. It is evaluated from the explicit equation of state rather than solved for, so a non-positive value means the volume is inside the co-volume and the state is not one.",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "Z_c",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`Pc Vc/(R Tc)`. **Not an accuracy bound and not a physical range check** - a cubic's critical compressibility is the equation's, not the substance's. It is here because a sign error in any of the three quantities above shows up as a negative `Z_c` before it shows up anywhere else.",
        },
    },
];

static CRITICAL_POINT_CASES: &[TestCase] = &[
    TestCase {
        id: "pure_propane",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[],
        lists: &[],
        vectors: &[
            ("Tc", &[369.83]),
            ("Pc", &[4248000.0]),
            ("omega", &[0.1523]),
            ("z", &[1.0]),
        ],
        matrices: &[("kij", &[0.0])],
        expected: &[
            ("Tc", 369.83000000000004),
            ("Pc", 4248000.000000011),
            ("Vc", 0.00022251409546288967),
            ("Z_c", 0.3074013091160614),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "methane_and_butane",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599200.0, 3796000.0]),
            ("omega", &[0.01142, 0.2002]),
            ("z", &[0.4, 0.6]),
        ],
        matrices: &[("kij", &[0.0, 0.05, 0.05, 0.0])],
        expected: &[
            ("Tc", 389.60393756196225),
            ("Pc", 8496149.7632273),
            ("Vc", 0.00018249737998221664),
            ("Z_c", 0.4786535349108495),
        ],
        expected_vectors: &[],
    },
];

static CRITICAL_POINT_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "newton_on_temperature_eigenvalue",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 60,
    bracket: None,
    initialisation: None,
    inner: None,
};

static CRITICAL_POINT_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "heidemann_khalil_critical",
    convergence: "absolute",
    tolerance: 1e-09,
    max_iterations: 60,
    bracket: None,
    initialisation: Some("kay_rule_and_covolume"),
    inner: Some(&CRITICAL_POINT_INNER),
};

/// Registry entry for `eos.critical_point`.
pub static CRITICAL_POINT_SPEC: ModelSpec = ModelSpec {
    id: "eos.critical_point",
    kind: "procedure",
    algorithm: Some(&CRITICAL_POINT_ALGORITHM),
    checks: CRITICAL_POINT_CHECKS,
    cases: CRITICAL_POINT_CASES,
};

static DEW_PRESSURE_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "min_t_over_tc",
            min: None,
            min_inclusive: true,
            max: Some(1.0),
            max_inclusive: false,
            equals: None,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "Above the nearest component's critical temperature the iteration converges more slowly and the answer is less trustworthy. A warning rather than an error because a mixture's critical temperature is not any one component's, so a mixture can still have a dew point where this bound is crossed.",
        },
    },
];

static DEW_PRESSURE_CASES: &[TestCase] = &[
    TestCase {
        id: "methane_and_butane_at_300_k",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 300.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599200.0, 3796000.0]),
            ("omega", &[0.01142, 0.2002]),
            ("y", &[0.8, 0.2]),
        ],
        matrices: &[("kij", &[0.0, 0.05, 0.05, 0.0])],
        expected: &[
            ("pressure", 1568262.871743118),
            ("z_liquid", 0.059502183160440175),
            ("z_vapour", 0.9238233886624134),
            ("min_t_over_tc", 0.7056831012420023),
            ("iterations", 25.0),
        ],
        expected_vectors: &[
            ("incipient", &[0.06533180227306302, 0.934668197726937]),
            ("k", &[12.245184920151232, 0.21397967801460738]),
        ],
    },
    TestCase {
        id: "methane_propane_and_butane_at_300_k",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 300.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 369.83, 425.12]),
            ("Pc", &[4599200.0, 4248000.0, 3796000.0]),
            ("omega", &[0.01142, 0.1523, 0.2002]),
            ("y", &[0.5, 0.3, 0.2]),
        ],
        matrices: &[("kij", &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])],
        expected: &[
            ("pressure", 1032568.2312776279),
            ("z_liquid", 0.03812011709239035),
            ("z_vapour", 0.902967011675539),
            ("min_t_over_tc", 0.7056831012420023),
            ("iterations", 20.0),
        ],
        expected_vectors: &[
            (
                "incipient",
                &[0.03357294952023628, 0.31034212171707015, 0.6560849287626935],
            ),
            (
                "k",
                &[14.892942298646231, 0.9666750950218941, 0.3048385829823517],
            ),
        ],
    },
];

static DEW_PRESSURE_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "dew_pressure_successive_substitution",
    convergence: "absolute",
    tolerance: 1e-12,
    max_iterations: 200,
    bracket: None,
    initialisation: Some("wilson_raoult"),
    inner: None,
};

/// Registry entry for `eos.dew_pressure`.
pub static DEW_PRESSURE_SPEC: ModelSpec = ModelSpec {
    id: "eos.dew_pressure",
    kind: "procedure",
    algorithm: Some(&DEW_PRESSURE_ALGORITHM),
    checks: DEW_PRESSURE_CHECKS,
    cases: DEW_PRESSURE_CASES,
};

static MOLAR_ENTHALPY_ENTROPY_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T_ref",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "the reference temperature, and the argument of `ln(T/T_ref)` in the entropy integral - so zero is a division rather than a state",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P_ref",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "the reference pressure, and the argument of `ln(P/P_ref)`",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "compressibility",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`Z = P v /(R T)` is positive for any state with a positive volume. The stricter check that actually matters - that the root exceeds the mixture's `B`, without which `ln(Z - B)` is the logarithm of a negative number - needs the composition and belongs to the implementation rather than to this table.",
        },
    },
];

static MOLAR_ENTHALPY_ENTROPY_CASES: &[TestCase] = &[
    TestCase {
        id: "methane_and_butane_with_a_zero_datum",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 298.15),
            ("P_ref", 101325.0),
            ("T", 330.0),
            ("P", 2500000.0),
            ("compressibility", 0.8274482588400789),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599200.0, 3796000.0]),
            ("omega", &[0.01142, 0.2002]),
            ("cp_a", &[4.0, 4.0]),
            ("cp_b", &[1.0, 1.0]),
            ("cp_c", &[-0.5, -0.5]),
            ("cp_d", &[0.1, 0.1]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.05, 0.05, 0.0])],
        expected: &[
            ("h", -351.24593942874526),
            ("s", -20.553517170090107),
            ("h_ideal", 1130.1847399375104),
            ("s_ideal", -17.456668341283496),
            ("h_departure", -1481.4306793662556),
            ("s_departure", -3.0968488288066105),
            ("psi_bar", -0.5619363510353611),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "the_same_state_with_the_ideal_gas_terms_off",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 298.15),
            ("P_ref", 101325.0),
            ("T", 330.0),
            ("P", 2500000.0),
            ("compressibility", 0.8274482588400789),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599200.0, 3796000.0]),
            ("omega", &[0.01142, 0.2002]),
            ("cp_a", &[0.0, 0.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.05, 0.05, 0.0])],
        expected: &[
            ("h", -1481.4306793662556),
            ("s", -24.154898040804962),
            ("h_ideal", 0.0),
            ("s_ideal", -21.058049211998352),
            ("h_departure", -1481.4306793662556),
            ("s_departure", -3.0968488288066105),
            ("psi_bar", -0.5619363510353611),
        ],
        expected_vectors: &[],
    },
];

/// Registry entry for `eos.molar_enthalpy_entropy`.
pub static MOLAR_ENTHALPY_ENTROPY_SPEC: ModelSpec = ModelSpec {
    id: "eos.molar_enthalpy_entropy",
    kind: "direct",
    algorithm: None,
    checks: MOLAR_ENTHALPY_ENTROPY_CHECKS,
    cases: MOLAR_ENTHALPY_ENTROPY_CASES,
};

static PH_FLASH_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states, and the cubic's reduced variables divide by it.",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "T",
            min: Some(100.0),
            min_inclusive: true,
            max: Some(1500.0),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "the bracket itself, reported rather than left implicit. The scan covers 100 K to 1500 K, so an answer outside it cannot be found - and that is a property of this implementation rather than of thermodynamics, which is why it warns.",
        },
    },
];

static PH_FLASH_CASES: &[TestCase] = &[
    TestCase {
        id: "two_phase_round_trip",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-07,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("P", 2000000.0),
            ("H", -6723.003844102389),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 300.0), ("beta", 0.6824390296506371)],
        expected_vectors: &[],
    },
    TestCase {
        id: "single_phase_vapour_round_trip",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-07,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("P", 2000000.0),
            ("H", 4078.801680952362),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 450.0)],
        expected_vectors: &[],
    },
];

static PH_FLASH_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "successive_substitution_flash",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    inner: None,
};

static PH_FLASH_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "ph_flash_temperature_bisection",
    convergence: "relative",
    tolerance: 1e-08,
    max_iterations: 200,
    bracket: Some(ModelBracket {
        scheme: "linear_scan_for_enthalpy",
        lower: 100.0,
        upper: 1500.0,
        steps: 2000,
    }),
    initialisation: None,
    inner: Some(&PH_FLASH_INNER),
};

/// Registry entry for `eos.ph_flash`.
pub static PH_FLASH_SPEC: ModelSpec = ModelSpec {
    id: "eos.ph_flash",
    kind: "procedure",
    algorithm: Some(&PH_FLASH_ALGORITHM),
    checks: PH_FLASH_CHECKS,
    cases: PH_FLASH_CASES,
};

static PT_FLASH_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states. This also keeps every `B_i` positive, which `eos.pr_z_factor` requires - `B` is proportional to pressure and the cubic degenerates at zero.",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "min_t_over_tc",
            min: None,
            min_inclusive: true,
            max: Some(0.9),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "Above `T / Tc = 0.9` for the nearest component the cubic's roots are close to coalescing, the two phases stop being distinguishable, and successive substitution converges slowly or to the trivial solution. This is a warning rather than an error because the arithmetic is still defined and the answer is still the equation's - it is the accuracy and the iteration that degrade, not the meaning. Recorded as a bound rather than left in prose so a caller sees the caveat without having to read this file.",
        },
    },
];

static PT_FLASH_CASES: &[TestCase] = &[
    TestCase {
        id: "methane_and_butane_at_330_k_and_25_bar",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 330.0), ("P", 2500000.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599200.0, 3796000.0]),
            ("omega", &[0.01142, 0.2002]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.05, 0.05, 0.0])],
        expected: &[
            ("beta", 0.8447220271668119),
            ("z_liquid", 0.0933521915309248),
            ("z_vapour", 0.8722188526935039),
            ("min_t_over_tc", 0.7762514113662025),
            ("iterations", 13.0),
        ],
        expected_vectors: &[
            ("x", &[0.08646861506372552, 0.9135313849362734]),
            ("y", &[0.6943980503344653, 0.3056019496655348]),
            ("k", &[8.030636894354197, 0.3345281341230035]),
            ("ln_phi_liquid", &[2.0769347319092257, -1.4953745844048578]),
            (
                "ln_phi_vapour",
                &[-0.006329107265372294, -0.4003402894548284],
            ),
        ],
    },
    TestCase {
        id: "methane_propane_and_butane_at_350_k_and_50_bar",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 350.0), ("P", 5000000.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 369.83, 425.12]),
            ("Pc", &[4599200.0, 4248000.0, 3796000.0]),
            ("omega", &[0.01142, 0.1523, 0.2002]),
            ("z", &[0.5, 0.3, 0.2]),
        ],
        matrices: &[("kij", &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])],
        expected: &[
            ("beta", 0.9897493300887433),
            ("z_liquid", 0.1923272374793064),
            ("z_vapour", 0.6962296633271022),
            ("min_t_over_tc", 0.8232969514490026),
            ("iterations", 22.0),
        ],
        expected_vectors: &[
            (
                "x",
                &[0.17105357654811876, 0.3837611570605945, 0.445185266391286],
            ),
            (
                "y",
                &[0.5034068436348336, 0.2991324995670004, 0.19746065679816602],
            ),
            (
                "k",
                &[2.9429775968070517, 0.7794757079069585, 0.44354715150121843],
            ),
            (
                "ln_phi_liquid",
                &[1.140973487143631, -0.7934020172498539, -1.631208601116444],
            ),
            (
                "ln_phi_vapour",
                &[
                    0.06155163030297489,
                    -0.5442682626142179,
                    -0.8182574350707497,
                ],
            ),
        ],
    },
    TestCase {
        id: "a_subcooled_liquid_feed",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 300.0), ("P", 3000000.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599200.0, 3796000.0]),
            ("omega", &[0.01142, 0.2002]),
            ("z", &[0.1, 0.9]),
        ],
        matrices: &[("kij", &[0.0, 0.05, 0.05, 0.0])],
        expected: &[
            ("beta", -0.046417400850318154),
            ("z_liquid", 0.1109805757787235),
            ("z_vapour", 0.8903679940210696),
            ("min_t_over_tc", 0.7056831012420023),
            ("iterations", 12.0),
        ],
        expected_vectors: &[
            ("x", &[0.1343066534039841, 0.8656933465960167]),
            ("y", &[0.8733970112336372, 0.12660298876638099]),
            ("k", &[6.503006285224948, 0.1462446133659167]),
            ("ln_phi_liquid", &[1.8168271437554724, -2.413916106531643]),
            (
                "ln_phi_vapour",
                &[-0.05543743164054027, -0.49144148129974313],
            ),
        ],
    },
];

static PT_FLASH_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "rachford_rice_bisection",
    convergence: "absolute",
    tolerance: 1e-14,
    max_iterations: 200,
    bracket: None,
    initialisation: None,
    inner: None,
};

static PT_FLASH_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "successive_substitution_flash",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    inner: Some(&PT_FLASH_INNER),
};

/// Registry entry for `eos.pt_flash`.
pub static PT_FLASH_SPEC: ModelSpec = ModelSpec {
    id: "eos.pt_flash",
    kind: "procedure",
    algorithm: Some(&PT_FLASH_ALGORITHM),
    checks: PT_FLASH_CHECKS,
    cases: PT_FLASH_CASES,
};

static PURE_SATURATION_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "Tc",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a critical temperature is absolute and positive by definition; it is also a divisor in the reduced temperature",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "Pc",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a critical pressure is positive by definition, and it converts the reduced answer back to pascals",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "t_over_tc",
            min: None,
            min_inclusive: true,
            max: Some(1.0),
            max_inclusive: false,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "Above the critical temperature a pure component has no saturation pressure. The bound is on the *ratio* because that is the quantity the model needs - a bound on `T` alone would have to be a bound that happened to be right for the `Tc` in play, which is not a bound at all. At exactly `Tc` the two roots have merged, there is one fugacity, and the residual is zero for every pressure - so the search would converge on nothing. Hence exclusive.",
        },
    },
];

static PURE_SATURATION_CASES: &[TestCase] = &[
    TestCase {
        id: "propane_at_300_k",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("Tc", 369.83),
            ("Pc", 4248000.0),
            ("omega", 0.1523),
            ("T", 300.0),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("p_sat", 997667.7436544185)],
        expected_vectors: &[],
    },
    TestCase {
        id: "carbon_dioxide_at_280_k",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("Tc", 304.13),
            ("Pc", 7377000.0),
            ("omega", 0.2239),
            ("T", 280.0),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("p_sat", 4159392.604815074)],
        expected_vectors: &[],
    },
];

static PURE_SATURATION_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "saturation_pressure_bisection",
    convergence: "relative",
    tolerance: 1e-12,
    max_iterations: 200,
    bracket: Some(ModelBracket {
        scheme: "linear_scan_for_spinodal",
        lower: 1e-06,
        upper: 0.999,
        steps: 4000,
    }),
    initialisation: None,
    inner: None,
};

/// Registry entry for `eos.pure_saturation`.
pub static PURE_SATURATION_SPEC: ModelSpec = ModelSpec {
    id: "eos.pure_saturation",
    kind: "procedure",
    algorithm: Some(&PURE_SATURATION_ALGORITHM),
    checks: PURE_SATURATION_CHECKS,
    cases: PURE_SATURATION_CASES,
};

static STABILITY_TEST_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "min_t_over_tc",
            min: None,
            min_inclusive: true,
            max: Some(0.9),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "The same bound `eos.pt_flash` carries, and it applies here at least as directly. Above `T / Tc = 0.9` for *every* component - which is what a minimum above 0.9 means - the cubic's roots are close to coalescing and the two phases stop being distinguishable. This model rests entirely on the trials finding *distinct* stationary points, so near the critical point a `stable` verdict is the one to distrust: it may mean the feed is single phase, or it may mean the trials could not separate. A warning rather than an error because the arithmetic is defined and the answer is still the criterion's - what degrades is what a negative result is worth, not what a positive one says.",
        },
    },
];

static STABILITY_TEST_CASES: &[TestCase] = &[
    TestCase {
        id: "a_two_phase_feed_is_unstable",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 330.0), ("P", 2500000.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599200.0, 3796000.0]),
            ("omega", &[0.01142, 0.2002]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.05, 0.05, 0.0])],
        expected: &[],
        expected_vectors: &[
            ("tm", &[0.0, -0.2151222395220802]),
            ("iterations", &[16.0, 9.0]),
        ],
    },
    TestCase {
        id: "a_trivial_flash_is_not_a_stable_feed",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 430.0), ("P", 6000000.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599200.0, 3796000.0]),
            ("omega", &[0.01142, 0.2002]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.05, 0.05, 0.0])],
        expected: &[],
        expected_vectors: &[
            ("tm", &[0.0, -4.440892098500626e-16]),
            ("iterations", &[16.0, 17.0]),
        ],
    },
];

static STABILITY_TEST_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "tangent_plane_stability",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 2000,
    bracket: None,
    initialisation: Some("wilson"),
    inner: None,
};

/// Registry entry for `eos.stability_test`.
pub static STABILITY_TEST_SPEC: ModelSpec = ModelSpec {
    id: "eos.stability_test",
    kind: "procedure",
    algorithm: Some(&STABILITY_TEST_ALGORITHM),
    checks: STABILITY_TEST_CHECKS,
    cases: STABILITY_TEST_CASES,
};

static ALL_MODELS: &[&ModelSpec] = &[
    &BUBBLE_PRESSURE_SPEC,
    &CRITICAL_POINT_SPEC,
    &DEW_PRESSURE_SPEC,
    &MOLAR_ENTHALPY_ENTROPY_SPEC,
    &PH_FLASH_SPEC,
    &PT_FLASH_SPEC,
    &PURE_SATURATION_SPEC,
    &STABILITY_TEST_SPEC,
];

/// Every model in this namespace, in id order.
#[must_use]
pub fn models() -> &'static [&'static ModelSpec] {
    ALL_MODELS
}

/// One model by id, or `None`. Used by the contract tests.
#[must_use]
pub fn model(id: &str) -> Option<&'static ModelSpec> {
    ALL_MODELS.iter().copied().find(|m| m.id == id)
}
