//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_registry.py` from:
//!
//!   - specs/calcs/eos/ideal_gas_cp.yaml
//!   - specs/calcs/eos/pr_alpha_ab.yaml
//!   - specs/calcs/eos/pr_departure.yaml
//!   - specs/calcs/eos/pr_kappa.yaml
//!   - specs/calcs/eos/pr_mass_density.yaml
//!   - specs/calcs/eos/pr_molar_volume.yaml
//!   - specs/calcs/eos/pr_z_factor.yaml
//!   - specs/calcs/eos/prsv_kappa.yaml
//!   - specs/calcs/eos/rachford_rice_binary.yaml
//!   - specs/calcs/eos/vdw1f_mix_binary.yaml
//!
//! Tables for the `eos` namespace. Every namespace has its own generated
//! file, because a crate is the unit of compilation and a calculation must be able
//! to read its own bounds without depending on another namespace's crate. The
//! types these tables are built from are shared - see `azoth_core::spec`.
//!
//! These tables are what make the specs authoritative at runtime rather than
//! merely descriptive. Each calc reads its own range checks from here, so a
//! bound changed in a spec file changes the code's behaviour with no second
//! edit - and `cargo test` fails if the two ever disagree.
use azoth_core::{
    Band, CalcSpec, RangeCheck, Severity, SolverSpec, SpecCheck, TestCase, WarningCode,
};

/// Registry entry for `eos.ideal_gas_cp`.
static IDEAL_GAS_CP_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature, and the divisor in the reduced temperature; zero and below are not states. The bound is on `T` and not on `theta` because `theta` is what the equation uses while `T` is what the caller supplies, so naming `T` is what makes the message legible.",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "cp",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "a heat capacity is positive by definition, so a negative one means the polynomial has turned over outside its fitted range. A warning rather than an error because the arithmetic is well defined and a caller inspecting the limit is doing something legitimate - but it must not pass in silence, because the value feeds an integral downstream and a negative heat capacity produces an enthalpy that is wrong by an amount nobody can see.",
        },
    },
];

static IDEAL_GAS_CP_TESTS: &[TestCase] = &[
    TestCase {
        id: "a_second_temperature",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("a", 4.0),
            ("b", 1.0),
            ("c", -0.5),
            ("d", 0.1),
            ("T", 300.0),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("cp_over_r", 4.2577), ("cp", 35.40048748931105)],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_polynomial_that_has_turned_over",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("a", 4.0),
            ("b", -20.0),
            ("c", 10.0),
            ("d", 1.0),
            ("T", 1000.0),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("cp_over_r", -5.0), ("cp", -41.5723130907662)],
        expected_vectors: &[],
    },
    TestCase {
        id: "an_all_zero_coefficient_set",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-15,
        numbers: &[("a", 0.0), ("b", 0.0), ("c", 0.0), ("d", 0.0), ("T", 350.0)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("cp_over_r", 0.0), ("cp", 0.0)],
        expected_vectors: &[],
    },
    TestCase {
        id: "monotonic",
        kind: "property",
        property: Some("monotonic"),
        status: "active",
        skip_reason: Some(
            "The polynomial is not monotonic in `T` for a general coefficient set and must not be: `Cp` rises, turns over and falls for a real substance. A monotonicity claim here would be a claim about the coefficients rather than about the code, and the schema's `monotonic` property is written for calcs whose monotonicity is a consequence of the equation.",
        ),
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "unit_round_trip",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.ideal_gas_cp`.
///
/// Public and addressable directly, so a calc can hold `&IDEAL_GAS_CP_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static IDEAL_GAS_CP_SPEC: CalcSpec = CalcSpec {
    id: "eos.ideal_gas_cp",
    verification: "unverified",
    checks: IDEAL_GAS_CP_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "illustrative_coefficients_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("a", 4.0),
            ("b", 1.0),
            ("c", -0.5),
            ("d", 0.1),
            ("T", 500.0),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("cp_over_r", 4.3875), ("cp", 36.47970473714734)],
        expected_vectors: &[],
    },
    tests: IDEAL_GAS_CP_TESTS,
};

/// Registry entry for `eos.pr_alpha_ab`.
static PR_ALPHA_AB_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "Tr",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`Tr` appears as a square root in alpha and as a divisor, squared, in `a_reduced`. Tr = 0 is singular, a negative Tr makes the square root undefined, and neither is a limiting case worth returning a number for - both are caller errors. `b_reduced` is the one term that would survive, which is exactly why the bound belongs on the input rather than being left to each output.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "Pr",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "Pr = 0 drives both A and B to zero, and B appears as a divisor in the fugacity-coefficient expression that consumes this calc's output. The ideal-gas limit is a real and useful state, but it is not a state a cubic equation of state describes - and a calc that returned A = B = 0 would be handing the next step a division by zero rather than a limit. The bound says so here, where the reason is visible, instead of downstream where it would read as a mystery.",
        },
    },
];

static PR_ALPHA_AB_TESTS: &[TestCase] = &[
    TestCase {
        id: "at_the_critical_point_the_parameters_are_the_omegas",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-15,
        numbers: &[("kappa", 0.60282728832), ("Tr", 1.0), ("Pr", 1.0)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("alpha", 1.0),
            ("a_reduced", 0.4572355289213822),
            ("b_reduced", 0.07779607390388846),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "supercritical_and_a_different_kappa",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("kappa", 0.392217407205312), ("Tr", 1.5), ("Pr", 0.5)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("alpha", 0.8314725184069646),
            ("a_reduced", 0.08448417260831159),
            ("b_reduced", 0.025932024634629486),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "monotonic",
        kind: "property",
        property: Some("monotonic"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "skipped",
        skip_reason: Some(
            "Every input and every output is dimensionless, so there is no unit to convert. Declared rather than omitted so the omission is a recorded decision, following `crane_k_factors` and `eos.pr_kappa`.",
        ),
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.pr_alpha_ab`.
///
/// Public and addressable directly, so a calc can hold `&PR_ALPHA_AB_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static PR_ALPHA_AB_SPEC: CalcSpec = CalcSpec {
    id: "eos.pr_alpha_ab",
    verification: "unverified",
    checks: PR_ALPHA_AB_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "propane_at_tr_0_8_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("kappa", 0.60282728832), ("Tr", 0.8), ("Pr", 0.25)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("alpha", 1.1313346661636197),
            ("a_reduced", 0.20206500174625697),
            ("b_reduced", 0.02431127309496514),
        ],
        expected_vectors: &[],
    },
    tests: PR_ALPHA_AB_TESTS,
};

/// Registry entry for `eos.pr_departure`.
static PR_DEPARTURE_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "b_reduced",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`b_reduced` appears as a divisor in the coefficient `A/(2*sqrt(2)*B)`. At B = 0 the departure functions are all zero - the ideal-gas limit - and that limit is a real thing to ask about, but it is not reachable by division. A caller wanting it does not need this calc.",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "z_minus_b_reduced",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`z` appears as `ln(z - b_reduced)`, so `z = b_reduced` is the zero-volume limit and `z < b_reduced` makes the logarithm of a negative number. That the requirement is on the *difference* rather than on `z` alone is why this is a derived check: a bound on `z` would have to be a bound that happened to be right for the `B` in play, which is not a bound at all. `eos.pr_z_factor` already discards roots at or below `B`, so a `z` from there passes this - which is the point. This bound exists for the caller who supplied `z` some other way, and it names the failure rather than letting `math domain error` do it.",
        },
    },
];

static PR_DEPARTURE_TESTS: &[TestCase] = &[
    TestCase {
        id: "the_liquid_root_of_the_same_state",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("a_reduced", 0.20206500174625697),
            ("b_reduced", 0.02431127309496514),
            ("z", 0.036765449656896015),
            ("kappa", 0.60282728832),
            ("Tr", 0.8),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("ln_phi", -0.3218698775991462),
            ("h_dep_rt", -6.6056599807533996),
            ("s_dep_r", -6.283790103154252),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "supercritical_state_with_a_different_coefficient",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("a_reduced", 0.08448417260831159),
            ("b_reduced", 0.025932024634629486),
            ("z", 0.943312987185517),
            ("kappa", 0.392217407205312),
            ("Tr", 1.5),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("ln_phi", -0.05766112543659872),
            ("h_dep_rt", -0.18983428427214197),
            ("s_dep_r", -0.13217315883554326),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "the_gibbs_identity_holds",
        kind: "property",
        property: Some("consistency_with"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "low_pressure_limit_is_the_ideal_gas",
        kind: "property",
        property: Some("consistency_with"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "skipped",
        skip_reason: Some(
            "Every input and every output is dimensionless, so there is no unit to convert. Declared rather than omitted so the omission is a recorded decision, following `crane_k_factors` and the other four `eos` calcs.",
        ),
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.pr_departure`.
///
/// Public and addressable directly, so a calc can hold `&PR_DEPARTURE_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static PR_DEPARTURE_SPEC: CalcSpec = CalcSpec {
    id: "eos.pr_departure",
    verification: "unverified",
    checks: PR_DEPARTURE_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "propane_vapour_root_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("a_reduced", 0.20206500174625697),
            ("b_reduced", 0.02431127309496514),
            ("z", 0.7907789662973796),
            ("kappa", 0.60282728832),
            ("Tr", 0.8),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("ln_phi", -0.19131055684257678),
            ("h_dep_rt", -0.5830167814158524),
            ("s_dep_r", -0.39170622457327564),
        ],
        expected_vectors: &[],
    },
    tests: PR_DEPARTURE_TESTS,
};

/// Registry entry for `eos.pr_kappa`.
static PR_KAPPA_CHECKS: &[SpecCheck] = &[SpecCheck {
    on_input: false,
    check: RangeCheck {
        quantity: "kappa",
        min: Some(0.0),
        min_inclusive: false,
        max: None,
        max_inclusive: true,
        equals: None,
        band: Band::Outside,
        severity: Severity::Warning,
        code: WarningCode::OutOfValidRange,
        rationale: "The polynomial passes through zero at two values of omega, the roots of 0.37464 + 1.54226*omega - 0.26992*omega**2 = 0: -0.23338349942403008 and 5.947150541510574. Below the lower one - and above the upper one, which no real fluid reaches - kappa is negative. That matters because kappa enters alpha = (1 + kappa*(1 - sqrt(Tr)))**2 as the coefficient of how fast the attraction weakens with temperature. For kappa > 0 the attraction weakens as Tr rises, which is the behaviour the function exists to model; for kappa < 0 it strengthens, which is not a physical statement about any fluid. The returned value is still the polynomial's value and is still returned - a warning, not a refusal - but it is no longer a Peng-Robinson attraction parameter. This fires for real fluids, not for a theoretical corner. Helium (omega = -0.385) is below the root and produces kappa = -0.259138992; hydrogen (-0.216) is just above it and produces kappa = +0.02891845248, a coefficient small enough that alpha is very nearly 1 at every temperature. That PR handles the quantum fluids poorly is well known, and this bound says so in a way a caller can branch on rather than in a footnote. The roots are stated to full precision rather than rounded because they are the boundary this bound is drawn at, and a reader checking where the sign changes should get the same answer this does. They are the roots of the quadratic as published; see `verification` for what that qualification means here.",
    },
}];

static PR_KAPPA_TESTS: &[TestCase] = &[
    TestCase {
        id: "methane_at_a_very_different_acentric_factor",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("omega", 0.01142)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("kappa", 0.392217407205312)],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_negative_acentric_factor_warns",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("omega", -0.385)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("kappa", -0.259138992)],
        expected_vectors: &[],
    },
    TestCase {
        id: "monotonic",
        kind: "property",
        property: Some("monotonic"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "skipped",
        skip_reason: Some(
            "Both the input and the output are dimensionless, so there is no unit to convert and the round trip would assert that a dimensionless quantity survives conversion untouched - which `test_units_conversion.py` already asserts for the dimensionless entry in the vocabulary, once, rather than once per dimensionless calc. Declared rather than omitted so the omission is a recorded decision; the practice follows `crane_k_factors`, which skips this test for the same reason.",
        ),
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.pr_kappa`.
///
/// Public and addressable directly, so a calc can hold `&PR_KAPPA_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static PR_KAPPA_SPEC: CalcSpec = CalcSpec {
    id: "eos.pr_kappa",
    verification: "unverified",
    checks: PR_KAPPA_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "propane_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("omega", 0.152)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("kappa", 0.60282728832)],
        expected_vectors: &[],
    },
    tests: PR_KAPPA_TESTS,
};

/// Registry entry for `eos.pr_mass_density`.
static PR_MASS_DENSITY_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "M",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "A molar mass is a positive mass per amount of substance. Zero would give a density of zero for any volume, which is not a state; negative has no meaning at all. Note that this bound is on a *physical constant*, so it catches only the caller who passed something that is not a molar mass.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "v",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`v` is a divisor, and molar volume is strictly positive for any real state - `eos.pr_molar_volume` refuses a `z`, `T` or `P` that would make it otherwise. Zero is the zero-volume limit, which is arithmetic rather than a state.",
        },
    },
];

static PR_MASS_DENSITY_TESTS: &[TestCase] = &[
    TestCase {
        id: "a_liquid_density_that_shows_the_equations_error",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("M", 0.0440956), ("v", 8.516118084951335e-05)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("rho", 517.7899080323988)],
        expected_vectors: &[],
    },
    TestCase {
        id: "doubling_the_molar_mass_doubles_the_density",
        kind: "property",
        property: Some("consistency_with"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.pr_mass_density`.
///
/// Public and addressable directly, so a calc can hold `&PR_MASS_DENSITY_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static PR_MASS_DENSITY_SPEC: CalcSpec = CalcSpec {
    id: "eos.pr_mass_density",
    verification: "unverified",
    checks: PR_MASS_DENSITY_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "propane_vapour_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("M", 0.0440956), ("v", 0.0018317107825229842)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("rho", 24.073451125981286)],
        expected_vectors: &[],
    },
    tests: PR_MASS_DENSITY_TESTS,
};

/// Registry entry for `eos.pr_molar_volume`.
static PR_MOLAR_VOLUME_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "z",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "A molar volume is positive, so a `z` at or below zero could only come from a caller who is not passing a compressibility factor. The cubic's admissible roots are all strictly above `b_reduced`, which is positive, so a `z` from `eos.pr_z_factor` always passes this - the bound is for the caller who computed one some other way.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states, and a negative one would give a negative volume",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`P` is a divisor, and zero pressure is the infinite-volume limit - which is arithmetic rather than a state this calc can answer for. A negative pressure would give a negative volume.",
        },
    },
];

static PR_MOLAR_VOLUME_TESTS: &[TestCase] = &[
    TestCase {
        id: "a_reference_for_the_liquid_root",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("z", 0.036765449656896015),
            ("T", 295.864),
            ("P", 1062000.0),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("v", 8.516118084951335e-05)],
        expected_vectors: &[],
    },
    TestCase {
        id: "the_ideal_gas_limit_is_z_of_one",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("z", 1.0), ("T", 300.0), ("P", 101325.0)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("v", 0.024617209824287906)],
        expected_vectors: &[],
    },
    TestCase {
        id: "monotonic",
        kind: "property",
        property: Some("monotonic"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.pr_molar_volume`.
///
/// Public and addressable directly, so a calc can hold `&PR_MOLAR_VOLUME_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static PR_MOLAR_VOLUME_SPEC: CalcSpec = CalcSpec {
    id: "eos.pr_molar_volume",
    verification: "unverified",
    checks: PR_MOLAR_VOLUME_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "propane_vapour_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("z", 0.7907789662973796), ("T", 295.864), ("P", 1062000.0)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("v", 0.0018317107825229842)],
        expected_vectors: &[],
    },
    tests: PR_MOLAR_VOLUME_TESTS,
};

/// Registry entry for `eos.pr_z_factor`.
static PR_Z_FACTOR_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "b_reduced",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`B` is proportional to pressure and is zero only at zero pressure, where the cubic degenerates to `z**3 - z**2 = z**2 (z - 1)`. That has a double root at zero and the ideal-gas root at one - so the answer is not wrong, it is *trivial*, and it would come back as `z_min = z_max = 1` with nothing to say it was not a phase. The ideal-gas limit belongs to the caller, who knows they are asking for it; see the same bound and the same argument in `eos.pr_alpha_ab`.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "a_reduced",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`A` is a squared term times a positive coefficient - `Omega_a * alpha * Pr / Tr**2` - so it cannot be negative for any real input to `eos.pr_alpha_ab`. A negative value here means it did not come from that calc, and the cubic it produces is not a Peng-Robinson equation of state. Zero is permitted: it is the hard-sphere limit, which is a real thing to ask about even though no PR state reaches it.",
        },
    },
];

static PR_Z_FACTOR_TESTS: &[TestCase] = &[
    TestCase {
        id: "a_hand_pickable_cubic_with_three_roots",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("a_reduced", 0.25), ("b_reduced", 0.03125)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("z_min", 0.04868889529885568),
            ("z_max", 0.7280875526160305),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_single_root_above_the_critical_temperature",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("a_reduced", 0.08448417260831159),
            ("b_reduced", 0.025932024634629486),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("z_min", 0.943312987185517), ("z_max", 0.943312987185517)],
        expected_vectors: &[],
    },
    TestCase {
        id: "the_critical_point_is_where_the_answer_stops_being_determined",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 0.001,
        numbers: &[
            ("a_reduced", 0.4572355289213822),
            ("b_reduced", 0.07779607390388846),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("z_min", 0.30740130869870386),
            ("z_max", 0.30740130869870386),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "selected_roots_satisfy_the_cubic",
        kind: "property",
        property: Some("consistency_with"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "the_middle_root_is_not_returned",
        kind: "property",
        property: Some("consistency_with"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "the_admissible_count_is_never_two",
        kind: "property",
        property: Some("consistency_with"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "monotonic",
        kind: "property",
        property: Some("monotonic"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "skipped",
        skip_reason: Some(
            "Every input and every output is dimensionless, so there is no unit to convert. Declared rather than omitted so the omission is a recorded decision, following `crane_k_factors` and the other two `eos` calcs.",
        ),
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.pr_z_factor`.
///
/// Public and addressable directly, so a calc can hold `&PR_Z_FACTOR_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static PR_Z_FACTOR_SPEC: CalcSpec = CalcSpec {
    id: "eos.pr_z_factor",
    verification: "unverified",
    checks: PR_Z_FACTOR_CHECKS,
    solver: Some(SolverSpec {
        kind: "cubic_roots",
        tolerance: 1e-14,
        max_iterations: 50,
        initial_guess: None,
        convergence: "relative",
    }),
    worked_example: TestCase {
        id: "propane_like_three_root_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("a_reduced", 0.20206500174625697),
            ("b_reduced", 0.02431127309496514),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("z_min", 0.036765449656896015),
            ("z_max", 0.7907789662973796),
        ],
        expected_vectors: &[],
    },
    tests: PR_Z_FACTOR_TESTS,
};

/// Registry entry for `eos.prsv_kappa`.
static PRSV_KAPPA_CHECKS: &[SpecCheck] = &[SpecCheck {
    on_input: true,
    check: RangeCheck {
        quantity: "Tr",
        min: Some(0.0),
        min_inclusive: false,
        max: None,
        max_inclusive: true,
        equals: None,
        band: Band::Outside,
        severity: Severity::Error,
        code: WarningCode::OutOfValidRange,
        rationale: "`Tr` appears as a square root. Tr = 0 is finite but a negative Tr makes the root undefined, and a reduced temperature at or below zero is not a state. Refusing both ends keeps the bound to one rule rather than two that differ by accident.",
    },
}];

static PRSV_KAPPA_TESTS: &[TestCase] = &[
    TestCase {
        id: "at_tr_0_7_the_kappa1_term_vanishes",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("omega", 0.152), ("Tr", 0.7), ("kappa1", 0.05)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("kappa", 0.6014406094290431)],
        expected_vectors: &[],
    },
    TestCase {
        id: "with_kappa1_zero_the_coefficient_is_temperature_independent",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("omega", 0.152), ("Tr", 0.85), ("kappa1", 0.0)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("kappa", 0.6014406094290431)],
        expected_vectors: &[],
    },
    TestCase {
        id: "the_prsv_coefficient_feeds_the_pr_alpha_function",
        kind: "property",
        property: Some("consistency_with"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "monotonic",
        kind: "property",
        property: Some("monotonic"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "skipped",
        skip_reason: Some(
            "Every input and every output is dimensionless, so there is no unit to convert. Declared rather than omitted so the omission is a recorded decision, following `crane_k_factors` and the other three `eos` calcs.",
        ),
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.prsv_kappa`.
///
/// Public and addressable directly, so a calc can hold `&PRSV_KAPPA_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static PRSV_KAPPA_SPEC: CalcSpec = CalcSpec {
    id: "eos.prsv_kappa",
    verification: "unverified",
    checks: PRSV_KAPPA_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "propane_like_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("omega", 0.152), ("Tr", 0.8), ("kappa1", 0.05)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("kappa", 0.5919684734740435)],
        expected_vectors: &[],
    },
    tests: PRSV_KAPPA_TESTS,
};

/// Registry entry for `eos.rachford_rice_binary`.
static RACHFORD_RICE_BINARY_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "z1",
            min: Some(0.0),
            min_inclusive: true,
            max: Some(1.0),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a mole fraction; both ends are admitted, since a pure component is a legitimate limiting case and is a useful check",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "K1",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`K = y/x` with both compositions positive, so a K-value is strictly positive. A zero or negative one is not in the range where the equation means anything, and it would make the vapour composition `K*x` negative.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "K2",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "as for `K1`",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "K1",
            min: None,
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            equals: Some(1.0),
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`K1 - 1` is a divisor in the closed form. It is also the degenerate case of the equation: with `K1 = 1` component 1 distributes equally and drops out of the sum entirely, leaving a one-component problem whose solution is entirely determined by `K2`. Refusing is better than returning whatever the algebra collapses to.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "K2",
            min: None,
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            equals: Some(1.0),
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "as for `K1`",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "beta",
            min: Some(0.0),
            min_inclusive: true,
            max: Some(1.0),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "Outside `[0, 1]` the feed is single phase and the equation's solution is the *tangent-plane* value rather than a phase split. The result is returned with this warning rather than refused, because the value is meaningful and useful - a negative `beta` says the feed is subcooled liquid, and `beta > 1` says it is superheated vapour - but a caller must not read it as a vapour fraction. The warning is on the output rather than on the inputs because whether the feed splits depends on all three, not on any one of them, and there is no bound on `z1`, `K1` or `K2` individually that expresses it.",
        },
    },
];

static RACHFORD_RICE_BINARY_TESTS: &[TestCase] = &[
    TestCase {
        id: "a_feed_that_does_not_split",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-15,
        numbers: &[("z1", 0.5), ("K1", 2.0), ("K2", 1.5)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("beta", -1.5)],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_second_two_phase_case",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("z1", 0.3), ("K1", 5.0), ("K2", 0.2)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("beta", 0.19999999999999998)],
        expected_vectors: &[],
    },
    TestCase {
        id: "the_returned_beta_solves_the_equation",
        kind: "property",
        property: Some("consistency_with"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "skipped",
        skip_reason: Some(
            "Every input and every output is dimensionless, so there is no unit to convert. Declared rather than omitted so the omission is a recorded decision, following `crane_k_factors` and the other `eos` calcs.",
        ),
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.rachford_rice_binary`.
///
/// Public and addressable directly, so a calc can hold `&RACHFORD_RICE_BINARY_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static RACHFORD_RICE_BINARY_SPEC: CalcSpec = CalcSpec {
    id: "eos.rachford_rice_binary",
    verification: "unverified",
    checks: RACHFORD_RICE_BINARY_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "a_hand_checkable_case",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("z1", 0.6), ("K1", 4.0), ("K2", 0.25)],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("beta", 0.6666666666666665)],
        expected_vectors: &[],
    },
    tests: RACHFORD_RICE_BINARY_TESTS,
};

/// Registry entry for `eos.vdw1f_mix_binary`.
static VDW1F_MIX_BINARY_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "z1",
            min: Some(0.0),
            min_inclusive: true,
            max: Some(1.0),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "A mole fraction. Both ends are admitted - a pure component is a legitimate thing to ask this calc for, and it is a useful check, since `z1 = 0` or `1` must reproduce the pure-component parameters exactly. Outside them is a caller error, not a limiting case.",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "a_mix",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "`a_mix` is a quadratic form in `(z1, z2)` with matrix `[[a1, a12], [a12, a2]]` where `a12 = (1 - k12)*sqrt(a1*a2)`, so it is non-negative for every composition exactly when `a12**2 <= a1*a2` - that is, when `0 <= k12 <= 2`. Outside that band some composition makes `a_mix` negative, and a negative attraction parameter is not a quantity the cubic can take: `eos.pr_z_factor` refuses `a_reduced < 0` for that reason. The bound is on `a_mix` rather than on `k12` because a `k12` outside the band is not wrong in itself - most compositions still give a physical `a_mix` - and refusing the parameter would reject calls that are fine. This bound fires on the case that is actually broken, and the rationale names the cause.",
        },
    },
];

static VDW1F_MIX_BINARY_TESTS: &[TestCase] = &[
    TestCase {
        id: "a_pure_component_reproduces_its_own_parameters",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-15,
        numbers: &[
            ("z1", 1.0),
            ("a1", 0.20206500174625697),
            ("a2", 0.08448417260831159),
            ("b1", 0.02431127309496514),
            ("b2", 0.025932024634629486),
            ("k12", 0.05),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("a_mix", 0.20206500174625697),
            ("b_mix", 0.02431127309496514),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "ethane_and_a_large_k12",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("z1", 0.25),
            ("a1", 0.115),
            ("a2", 0.31),
            ("b1", 0.018),
            ("b2", 0.041),
            ("k12", 0.4),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[("a_mix", 0.22404521707412323), ("b_mix", 0.03525)],
        expected_vectors: &[],
    },
    TestCase {
        id: "monotonic",
        kind: "property",
        property: Some("monotonic"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "skipped",
        skip_reason: Some(
            "Every input and every output is dimensionless, so there is no unit to convert. Declared rather than omitted so the omission is a recorded decision, following `crane_k_factors` and the other `eos` calcs.",
        ),
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
    },
];

/// Registered spec for `eos.vdw1f_mix_binary`.
///
/// Public and addressable directly, so a calc can hold `&VDW1F_MIX_BINARY_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static VDW1F_MIX_BINARY_SPEC: CalcSpec = CalcSpec {
    id: "eos.vdw1f_mix_binary",
    verification: "unverified",
    checks: VDW1F_MIX_BINARY_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "propane_like_and_methane_like_with_k12",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("z1", 0.6),
            ("a1", 0.20206500174625697),
            ("a2", 0.08448417260831159),
            ("b1", 0.02431127309496514),
            ("b2", 0.025932024634629486),
            ("k12", 0.05),
        ],
        lists: &[],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("a_mix", 0.14584053499701302),
            ("b_mix", 0.02495957371083088),
        ],
        expected_vectors: &[],
    },
    tests: VDW1F_MIX_BINARY_TESTS,
};

/// Every calculation in the registry, sorted by id.
static ALL_SPECS: &[&CalcSpec] = &[
    &IDEAL_GAS_CP_SPEC,
    &PR_ALPHA_AB_SPEC,
    &PR_DEPARTURE_SPEC,
    &PR_KAPPA_SPEC,
    &PR_MASS_DENSITY_SPEC,
    &PR_MOLAR_VOLUME_SPEC,
    &PR_Z_FACTOR_SPEC,
    &PRSV_KAPPA_SPEC,
    &RACHFORD_RICE_BINARY_SPEC,
    &VDW1F_MIX_BINARY_SPEC,
];

/// All specs, in a stable order.
#[must_use]
pub fn specs() -> &'static [&'static CalcSpec] {
    ALL_SPECS
}

/// Look up a spec by id.
#[must_use]
pub fn spec(id: &str) -> Option<&'static CalcSpec> {
    ALL_SPECS.iter().copied().find(|s| s.id == id)
}
