-- GENERATED FILE - DO NOT EDIT BY HAND.
--
-- Generated by `tools/gen_vocabulary.py` from
-- `specs/vocabulary/vocabulary.toml`.
--
-- One `#print axioms` per unit theorem in `Azoth/Vocabulary.lean`, so the
-- gate covers every unit rather than the ones somebody remembered. Run by
-- `tools/check_lean_axioms.py`, which refuses any axiom set outside
-- `propext`, `Classical.choice` and `Quot.sound`.

import Azoth.Vocabulary

#print axioms Azoth.Vocabulary.u_dimensionless_dimension
#print axioms Azoth.Vocabulary.u_m_dimension
#print axioms Azoth.Vocabulary.u_mm_dimension
#print axioms Azoth.Vocabulary.u_m_pow_2_dimension
#print axioms Azoth.Vocabulary.u_m_pow_3_per_s_dimension
#print axioms Azoth.Vocabulary.u_kg_per_s_dimension
#print axioms Azoth.Vocabulary.u_mol_per_s_dimension
#print axioms Azoth.Vocabulary.u_mol_dimension
#print axioms Azoth.Vocabulary.u_kg_dimension
#print axioms Azoth.Vocabulary.u_kg_per_m_pow_3_dimension
#print axioms Azoth.Vocabulary.u_m_per_s_dimension
#print axioms Azoth.Vocabulary.u_m_pow_2_per_s_dimension
#print axioms Azoth.Vocabulary.u_Pa_dimension
#print axioms Azoth.Vocabulary.u_Pa_times_s_dimension
#print axioms Azoth.Vocabulary.u_K_dimension
#print axioms Azoth.Vocabulary.u_W_dimension
#print axioms Azoth.Vocabulary.u_J_per__kg_times_K_dimension
#print axioms Azoth.Vocabulary.u_W_per__m_times_K_dimension
#print axioms Azoth.Vocabulary.u_W_per__m_pow_2_times_K_dimension
#print axioms Azoth.Vocabulary.u_W_per_K_dimension
#print axioms Azoth.Vocabulary.u_N_per_m_dimension
#print axioms Azoth.Vocabulary.u_kg_per_mol_dimension
#print axioms Azoth.Vocabulary.u_m_pow_3_per_mol_dimension
#print axioms Azoth.Vocabulary.u_J_dimension
#print axioms Azoth.Vocabulary.u_J_per_mol_dimension
#print axioms Azoth.Vocabulary.u_Pa_times_m_pow_6_per_mol_pow_2_dimension
#print axioms Azoth.Vocabulary.u_J_per__mol_times_K_dimension
#print axioms Azoth.Vocabulary.u_J_per__mol_times_K_pow_2_dimension
#print axioms Azoth.Vocabulary.u_J_per__mol_times_K_pow_3_dimension
#print axioms Azoth.Vocabulary.u_J_per__mol_times_K_pow_4_dimension
#print axioms Azoth.Vocabulary.u_J_per__mol_times_K_pow_5_dimension
#print axioms Azoth.Vocabulary.u_C_dimension
#print axioms Azoth.Vocabulary.u_angstrom_dimension
#print axioms Azoth.Vocabulary.u_1_per_K_dimension
#print axioms Azoth.Vocabulary.u_1_per_K_pow_2_dimension
#print axioms Azoth.Vocabulary.u_1_per_K_pow_3_dimension
#print axioms Azoth.Vocabulary.u_mol_per_kg_dimension
#print axioms Azoth.Vocabulary.u_bar_dimension
#print axioms Azoth.Vocabulary.u_kPa_dimension
#print axioms Azoth.Vocabulary.u_MPa_dimension
#print axioms Azoth.Vocabulary.u_psi_dimension
#print axioms Azoth.Vocabulary.u_atm_dimension
#print axioms Azoth.Vocabulary.u_kg_per_h_dimension
#print axioms Azoth.Vocabulary.u_t_per_h_dimension
#print axioms Azoth.Vocabulary.u_lb_per_h_dimension
#print axioms Azoth.Vocabulary.u_t_dimension
#print axioms Azoth.Vocabulary.u_lb_dimension
#print axioms Azoth.Vocabulary.u_kJ_dimension
#print axioms Azoth.Vocabulary.u_MJ_dimension
#print axioms Azoth.Vocabulary.u_Btu_dimension
#print axioms Azoth.Vocabulary.u_kW_dimension
#print axioms Azoth.Vocabulary.u_MW_dimension
#print axioms Azoth.Vocabulary.u_hp_dimension
#print axioms Azoth.Vocabulary.u_ft_dimension
#print axioms Azoth.Vocabulary.u_in_dimension
#print axioms Azoth.Vocabulary.u_cm_dimension
#print axioms Azoth.Vocabulary.u_m_pow_3_per_h_dimension
#print axioms Azoth.Vocabulary.u_L_per_min_dimension
#print axioms Azoth.Vocabulary.u_gpm_dimension
#print axioms Azoth.Vocabulary.u_ft_pow_3_per_min_dimension
#print axioms Azoth.Vocabulary.u_ft_per_s_dimension
#print axioms Azoth.Vocabulary.u_lb_per_ft_pow_3_dimension
#print axioms Azoth.Vocabulary.u_kJ_per__kg_times_K_dimension
#print axioms Azoth.Vocabulary.u_Btu_per__lb_times_degF_dimension
#print axioms Azoth.Vocabulary.u_kJ_per_mol_dimension
#print axioms Azoth.Vocabulary.u_cP_dimension
#print axioms Azoth.Vocabulary.u_kmol_dimension
#print axioms Azoth.Vocabulary.u_kmol_per_h_dimension
