-- GENERATED FILE - DO NOT EDIT BY HAND.
--
-- Generated by `tools/gen_guard_theorems.py` from `lean/guards.toml`.
--
-- One `#print axioms` per guard theorem, so the gate covers every guard rather than the ones
-- somebody remembered. Run by `tools/check_lean_axioms.py`.

import Azoth.Guards

#print axioms Azoth.Guards.choked_flow_area_exponent_and_radicand
#print axioms Azoth.Guards.conduction_plane_wall_divides_by_l
#print axioms Azoth.Guards.control_valve_cv_divisor_and_radicand
#print axioms Azoth.Guards.darcy_weisbach_divides_by_d
#print axioms Azoth.Guards.orifice_flow_divisor_and_radicand
#print axioms Azoth.Guards.pr_alpha_ab_sqrt_and_divisor
#print axioms Azoth.Guards.rachford_rice_binary_divisor_nonzero
#print axioms Azoth.Guards.rk_alpha_ab_sqrt_and_divisor
#print axioms Azoth.Guards.srk_alpha_ab_sqrt_and_divisor
