-- GENERATED FILE - DO NOT EDIT BY HAND.
--
-- Generated by `tools/gen_vocabulary.py` from
-- `specs/vocabulary/vocabulary.yaml`.
--
-- One entry per canonical unit a spec may declare, with the dimension it
-- carries as exponents in `Azoth.Dim.slots` order. The theorems that say
-- these mean what the calculus says they mean are hand-written, in
-- `Azoth/Units.lean`, because a proven statement is not a naming.

import Azoth.Dim

namespace Azoth.Vocabulary

open Units (Dimension)

/-- Every canonical unit string, with the dimension it carries.

Each exponent vector is written in `Azoth.Dim.slots` order, and has one
entry per slot - 7 of them.
-/
def units : List (String × Units.Dimension) :=
  [
    ("dimensionless", Dim.ofExponents [0, 0, 0, 0, 0, 0, 0]),
    ("m", Dim.ofExponents [1, 0, 0, 0, 0, 0, 0]),
    ("mm", Dim.ofExponents [1, 0, 0, 0, 0, 0, 0]),
    ("m**2", Dim.ofExponents [2, 0, 0, 0, 0, 0, 0]),
    ("m**3/s", Dim.ofExponents [3, 0, -1, 0, 0, 0, 0]),
    ("kg/s", Dim.ofExponents [0, 1, -1, 0, 0, 0, 0]),
    ("mol/s", Dim.ofExponents [0, 0, -1, 0, 0, 1, 0]),
    ("kg/m**3", Dim.ofExponents [-3, 1, 0, 0, 0, 0, 0]),
    ("m/s", Dim.ofExponents [1, 0, -1, 0, 0, 0, 0]),
    ("Pa", Dim.ofExponents [-1, 1, -2, 0, 0, 0, 0]),
    ("Pa*s", Dim.ofExponents [-1, 1, -1, 0, 0, 0, 0]),
    ("K", Dim.ofExponents [0, 0, 0, 0, 1, 0, 0]),
    ("W", Dim.ofExponents [2, 1, -3, 0, 0, 0, 0]),
    ("J/(kg*K)", Dim.ofExponents [2, 0, -2, 0, -1, 0, 0]),
    ("W/(m*K)", Dim.ofExponents [1, 1, -3, 0, -1, 0, 0]),
    ("W/(m**2*K)", Dim.ofExponents [0, 1, -3, 0, -1, 0, 0]),
    ("kg/mol", Dim.ofExponents [0, 1, 0, 0, 0, -1, 0]),
    ("m**3/mol", Dim.ofExponents [3, 0, 0, 0, 0, -1, 0]),
    ("J/mol", Dim.ofExponents [2, 1, -2, 0, 0, -1, 0]),
    ("J/(mol*K)", Dim.ofExponents [2, 1, -2, 0, -1, -1, 0]),
    ("J/(mol*K**2)", Dim.ofExponents [2, 1, -2, 0, -2, -1, 0]),
    ("J/(mol*K**3)", Dim.ofExponents [2, 1, -2, 0, -3, -1, 0]),
    ("J/(mol*K**4)", Dim.ofExponents [2, 1, -2, 0, -4, -1, 0]),
    ("J/(mol*K**5)", Dim.ofExponents [2, 1, -2, 0, -5, -1, 0])
  ]

/-- The dimension of a canonical unit, or `none` if the name is not in the
vocabulary.

A name that is not there is `none` rather than an error: asking about one is a
question about the vocabulary, and the answer is that it has no dimension
because it is not in it.
-/
def dimOf (name : String) : Option Units.Dimension :=
  (units.find? (fun entry => entry.1 == name)).map (fun entry => entry.2)

end Azoth.Vocabulary
