//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_registry.py` from:
//!
//!   - specs/calcs/hydraulics/crane_k_factors.yaml
//!   - specs/calcs/hydraulics/darcy_weisbach.yaml
//!   - specs/calcs/hydraulics/friction_factor_colebrook.yaml
//!   - specs/calcs/hydraulics/friction_factor_swamee_jain.yaml
//!   - specs/calcs/hydraulics/reynolds_number.yaml
//!
//! These tables are what make the specs authoritative at runtime rather than
//! merely descriptive. Each calc reads its own range checks from here, so a
//! bound changed in a spec file changes the code's behaviour with no second
//! edit - and `cargo test` fails if the two ever disagree.

use chemeng_core::{Band, RangeCheck, Severity, WarningCode};

/// Solver configuration for an implicit calculation.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SolverSpec {
    /// `fixed_point`, `bisection` or `newton`.
    pub kind: &'static str,
    /// Stopping tolerance.
    pub tolerance: f64,
    /// Iteration cap.
    pub max_iterations: u32,
    /// Starting value.
    pub initial_guess: f64,
    /// `absolute` or `relative`; see the spec schema for what each means.
    pub convergence: &'static str,
}

/// One test case from a spec's `tests` list, plus the worked example.
#[derive(Debug, Clone, Copy)]
pub struct TestCase {
    /// Test id, unique within the calc.
    pub id: &'static str,
    /// `worked_example`, `reference`, or `property`.
    pub kind: &'static str,
    /// Which invariant a `property` test checks.
    pub property: Option<&'static str>,
    /// `active` or `skipped`.
    pub status: &'static str,
    /// Why a skipped test does not run. Never `None` when status is `skipped`.
    pub skip_reason: Option<&'static str>,
    /// Relative tolerance for comparison.
    pub tolerance: f64,
    /// Scalar inputs, by name.
    pub numbers: &'static [(&'static str, f64)],
    /// List-valued inputs, by name.
    pub lists: &'static [(&'static str, &'static [&'static str])],
    /// Expected outputs, by name.
    pub expected: &'static [(&'static str, f64)],
}

impl TestCase {
    /// Fetch a scalar input. `None` if the spec does not supply it.
    #[must_use]
    pub fn input(&self, name: &str) -> Option<f64> {
        self.numbers
            .iter()
            .find(|(k, _)| *k == name)
            .map(|(_, v)| *v)
    }

    /// Fetch a list-valued input.
    #[must_use]
    pub fn list(&self, name: &str) -> Option<&'static [&'static str]> {
        self.lists.iter().find(|(k, _)| *k == name).map(|(_, v)| *v)
    }

    /// Fetch an expected output. `None` if the test does not assert it.
    #[must_use]
    pub fn expected_value(&self, name: &str) -> Option<f64> {
        self.expected
            .iter()
            .find(|(k, _)| *k == name)
            .map(|(_, v)| *v)
    }

    /// Whether this test should actually run.
    #[must_use]
    pub fn is_active(&self) -> bool {
        self.status == "active"
    }
}

/// A range check plus the phase in which it can be evaluated.
#[derive(Debug, Clone, Copy)]
pub struct SpecCheck {
    /// True when the bounded quantity is one of the calc's declared inputs, so
    /// the check can run before the calculation.
    ///
    /// False for outputs and derived quantities, which only exist afterwards -
    /// and, for an optional input, may not exist at all.
    pub on_input: bool,
    /// The bound itself.
    pub check: RangeCheck,
}

/// Everything the Rust side needs to know about one calculation.
#[derive(Debug, Clone, Copy)]
pub struct CalcSpec {
    /// Spec id, e.g. `hydraulics.darcy_weisbach`.
    pub id: &'static str,
    /// `verified`, `unverified` or `source_needed`.
    pub verification: &'static str,
    /// Bounds, in spec order.
    pub checks: &'static [SpecCheck],
    /// Present only for implicit calculations.
    pub solver: Option<SolverSpec>,
    /// The worked example, as a runnable test case.
    pub worked_example: TestCase,
    /// The rest of the `tests` list, excluding the worked example.
    pub tests: &'static [TestCase],
}

impl CalcSpec {
    /// Checks evaluable from the inputs alone.
    pub fn input_checks(&self) -> impl Iterator<Item = &RangeCheck> {
        self.checks.iter().filter(|c| c.on_input).map(|c| &c.check)
    }

    /// Checks that need the calculation to have run first.
    pub fn derived_checks(&self) -> impl Iterator<Item = &RangeCheck> {
        self.checks.iter().filter(|c| !c.on_input).map(|c| &c.check)
    }

    /// Every check, in spec order.
    pub fn all_checks(&self) -> impl Iterator<Item = &RangeCheck> {
        self.checks.iter().map(|c| &c.check)
    }

    /// The worked example plus every other test, in spec order.
    pub fn all_tests(&self) -> impl Iterator<Item = &TestCase> {
        std::iter::once(&self.worked_example).chain(self.tests.iter())
    }
}

/// Registry entry for `hydraulics.crane_k_factors`.
static CRANE_K_FACTORS_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "f_t",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a non-positive friction factor gives a negative loss",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "n_fittings",
            min: Some(1.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "An empty fitting list is a caller error rather than a physical state - the calculation would silently return zero loss, which reads as \"no fittings\" when the caller may have meant to pass some.",
        },
    },
];

static CRANE_K_FACTORS_TESTS: &[TestCase] = &[
    TestCase {
        id: "single_fitting_matches_coefficient",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("f_t", 0.019)],
        lists: &[("fittings", &["90_elbow"])],
        expected: &[("k_total", 0.57)],
    },
    TestCase {
        id: "scaling_is_linear_in_f_t",
        kind: "property",
        property: Some("symmetry"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[],
        lists: &[],
        expected: &[],
    },
];

/// Registered spec for `hydraulics.crane_k_factors`.
///
/// Public and addressable directly, so a calc can hold `&CRANE_K_FACTORS_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static CRANE_K_FACTORS_SPEC: CalcSpec = CalcSpec {
    id: "hydraulics.crane_k_factors",
    verification: "unverified",
    checks: CRANE_K_FACTORS_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "elbow_and_gate_valve_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("f_t", 0.018)],
        lists: &[("fittings", &["90_elbow", "gate_valve_open"])],
        expected: &[("k_total", 0.684)],
    },
    tests: CRANE_K_FACTORS_TESTS,
};

/// Registry entry for `hydraulics.darcy_weisbach`.
static DARCY_WEISBACH_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "f",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a non-positive friction factor is unphysical and would give a negative or zero loss",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "L",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "negative length is unphysical; zero length correctly gives zero drop",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "D",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "L/D is singular at D = 0",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "rho",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "pressure drop scales with density, which must be positive",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "v",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "speed is non-negative; the sign of the drop is not modelled",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "re",
            min: Some(2000.0),
            min_inclusive: true,
            max: Some(4000.0),
            max_inclusive: true,
            band: Band::Inside,
            severity: Severity::Warning,
            code: WarningCode::TransitionalFlow,
            rationale: "Transitional flow, where the friction factor - and therefore this pressure drop - is genuinely indeterminate rather than merely uncertain. The value returned is trustworthy arithmetic applied to an untrustworthy f. This check is only evaluable when mu is supplied; when it is not, the implementation must emit RANGE_CHECK_SKIPPED so an unchecked result is distinguishable from a checked one.",
        },
    },
];

static DARCY_WEISBACH_TESTS: &[TestCase] = &[
    TestCase {
        id: "crane_3_5",
        kind: "reference",
        property: None,
        status: "skipped",
        skip_reason: Some(
            "source_needed: the brief attributed this worked example to \"Crane TP-410 Example 3-5\", but the example could not be located or verified, and the expected value supplied with it was inconsistent with the stated equation by a factor of 10. Reproducing a worked example from the standard is also exactly what the project's copyright rule forbids. Skipped rather than guessed: the equivalent validation is covered by derived_worked_example and public_water_steel_example.",
        ),
        tolerance: 1e-09,
        numbers: &[],
        lists: &[],
        expected: &[],
    },
    TestCase {
        id: "perry_6_42",
        kind: "reference",
        property: None,
        status: "skipped",
        skip_reason: Some(
            "source_needed: \"Perry's 8th ed. Eq. 6-42\" could not be verified, and reproducing text or tables from Perry's is prohibited by the project's copyright rule. Skipped rather than fabricated.",
        ),
        tolerance: 1e-09,
        numbers: &[],
        lists: &[],
        expected: &[],
    },
    TestCase {
        id: "reynolds_reported_when_mu_supplied",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[
            ("f", 0.02),
            ("L", 100.0),
            ("D", 0.1),
            ("rho", 998.0),
            ("v", 1.5),
            ("mu", 0.001002),
        ],
        lists: &[],
        expected: &[("dp", 22455.0), ("re", 149401.19760479042)],
    },
    TestCase {
        id: "public_water_steel_example",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 0.02,
        numbers: &[
            ("f", 0.01884561),
            ("L", 100.0),
            ("D", 0.1),
            ("rho", 998.0),
            ("v", 1.768388),
        ],
        lists: &[],
        expected: &[("dp", 29600.0)],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[],
        lists: &[],
        expected: &[],
    },
];

/// Registered spec for `hydraulics.darcy_weisbach`.
///
/// Public and addressable directly, so a calc can hold `&DARCY_WEISBACH_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static DARCY_WEISBACH_SPEC: CalcSpec = CalcSpec {
    id: "hydraulics.darcy_weisbach",
    verification: "unverified",
    checks: DARCY_WEISBACH_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "derived_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("f", 0.02),
            ("L", 100.0),
            ("D", 0.1),
            ("rho", 998.0),
            ("v", 1.5),
        ],
        lists: &[],
        expected: &[("dp", 22455.0)],
    },
    tests: DARCY_WEISBACH_TESTS,
};

/// Registry entry for `hydraulics.friction_factor_colebrook`.
static FRICTION_FACTOR_COLEBROOK_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "re",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "the 2.51/(Re*sqrt(f)) term is singular at Re = 0",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "relative_roughness",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "negative roughness is unphysical",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "re",
            min: Some(4000.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "Below Re ~ 4000 the Colebrook equation is outside the range it was fitted to; it is a transition-region correlation for turbulent flow. The iteration still converges to a number, so this is a warning rather than an error, but the number should not be used. For laminar flow use f = 64/Re instead, which is a different equation and deliberately not part of this calc.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "relative_roughness",
            min: None,
            min_inclusive: true,
            max: Some(0.05),
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "Above epsilon/D ~ 0.05 the Moody/Colebrook framework is no longer meaningful, and this library also does not carry roughness data that large.",
        },
    },
];

static FRICTION_FACTOR_COLEBROOK_TESTS: &[TestCase] = &[
    TestCase {
        id: "smooth_pipe_agrees_with_textbook",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 0.001,
        numbers: &[("re", 100000.0), ("relative_roughness", 0.0)],
        lists: &[],
        expected: &[("f", 0.0179898)],
    },
    TestCase {
        id: "fully_rough_limit",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-06,
        numbers: &[("re", 1000000000000.0), ("relative_roughness", 0.01)],
        lists: &[],
        expected: &[("f", 0.03790371)],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-06,
        numbers: &[],
        lists: &[],
        expected: &[],
    },
];

/// Registered spec for `hydraulics.friction_factor_colebrook`.
///
/// Public and addressable directly, so a calc can hold `&FRICTION_FACTOR_COLEBROOK_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static FRICTION_FACTOR_COLEBROOK_SPEC: CalcSpec = CalcSpec {
    id: "hydraulics.friction_factor_colebrook",
    verification: "verified",
    checks: FRICTION_FACTOR_COLEBROOK_CHECKS,
    solver: Some(SolverSpec {
        kind: "fixed_point",
        tolerance: 1e-12,
        max_iterations: 100,
        initial_guess: 0.02,
        convergence: "relative",
    }),
    worked_example: TestCase {
        id: "commercial_steel_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-06,
        numbers: &[("re", 100000.0), ("relative_roughness", 0.00046)],
        lists: &[],
        expected: &[("f", 0.020162032)],
    },
    tests: FRICTION_FACTOR_COLEBROOK_TESTS,
};

/// Registry entry for `hydraulics.friction_factor_swamee_jain`.
static FRICTION_FACTOR_SWAMEE_JAIN_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "re",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "Re**0.9 is zero at Re = 0 and the 5.74/Re**0.9 term is singular",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "relative_roughness",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "negative roughness is unphysical",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "re",
            min: Some(5000.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "Below Re = 5000 the equation is outside the range stated in the original paper, where the approximation was fitted. It still returns a number, so this is a warning rather than an error, but that number is not covered by the paper's accuracy claim.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "re",
            min: None,
            min_inclusive: true,
            max: Some(100000000.0),
            max_inclusive: false,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "upper Reynolds-number bound stated in the original paper",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "relative_roughness",
            min: Some(1e-06),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "lower relative-roughness bound stated in the original paper",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "relative_roughness",
            min: None,
            min_inclusive: true,
            max: Some(0.01),
            max_inclusive: false,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "Upper relative-roughness bound stated in the original paper (10**-2). NOTE: the literature is not consistent here - several widely used references quote the upper bound as 5e-2 instead, and a few quote 4e-5 as the lower bound. This spec encodes the original paper's figures. The value last listed in `references` is the comparison against Colebrook that justifies the loose tolerance on the agreement test.",
        },
    },
];

static FRICTION_FACTOR_SWAMEE_JAIN_TESTS: &[TestCase] = &[
    TestCase {
        id: "agrees_with_colebrook_within_one_percent",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 0.01,
        numbers: &[("re", 100000.0), ("relative_roughness", 0.00046)],
        lists: &[],
        expected: &[("f", 0.020162032)],
    },
    TestCase {
        id: "exact_smooth_pipe_limit",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 0.0001,
        numbers: &[("re", 100000.0), ("relative_roughness", 0.0)],
        lists: &[],
        expected: &[("f", 0.01786257789)],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-06,
        numbers: &[],
        lists: &[],
        expected: &[],
    },
];

/// Registered spec for `hydraulics.friction_factor_swamee_jain`.
///
/// Public and addressable directly, so a calc can hold `&FRICTION_FACTOR_SWAMEE_JAIN_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static FRICTION_FACTOR_SWAMEE_JAIN_SPEC: CalcSpec = CalcSpec {
    id: "hydraulics.friction_factor_swamee_jain",
    verification: "verified",
    checks: FRICTION_FACTOR_SWAMEE_JAIN_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "commercial_steel_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-06,
        numbers: &[("re", 100000.0), ("relative_roughness", 0.00046)],
        lists: &[],
        expected: &[("f", 0.0202400309)],
    },
    tests: FRICTION_FACTOR_SWAMEE_JAIN_TESTS,
};

/// Registry entry for `hydraulics.reynolds_number`.
static REYNOLDS_NUMBER_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "rho",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "density must be positive; it divides into nothing here but a non-positive value is unphysical",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "D",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a zero diameter makes the Reynolds number zero regardless of flow",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "mu",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "zero viscosity makes the Reynolds number undefined rather than large",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "v",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "speed is non-negative; flow direction is not modelled by this calc",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "re",
            min: Some(2000.0),
            min_inclusive: true,
            max: Some(4000.0),
            max_inclusive: true,
            band: Band::Inside,
            severity: Severity::Warning,
            code: WarningCode::TransitionalFlow,
            rationale: "Transitional flow. Downstream friction-factor correlations are indeterminate in this band and the two branches disagree by design, so any pressure drop computed from this Reynolds number should be treated as unreliable. This is a warning rather than an error because the Reynolds number itself is perfectly well defined here - it is the correlations that are not.",
        },
    },
];

static REYNOLDS_NUMBER_TESTS: &[TestCase] = &[
    TestCase {
        id: "transitional_warning",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("rho", 1000.0), ("v", 0.1), ("D", 0.05), ("mu", 0.0015)],
        lists: &[],
        expected: &[("re", 3333.3333333333335)],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        lists: &[],
        expected: &[],
    },
];

/// Registered spec for `hydraulics.reynolds_number`.
///
/// Public and addressable directly, so a calc can hold `&REYNOLDS_NUMBER_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static REYNOLDS_NUMBER_SPEC: CalcSpec = CalcSpec {
    id: "hydraulics.reynolds_number",
    verification: "unverified",
    checks: REYNOLDS_NUMBER_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "water_pipe_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("rho", 998.0), ("v", 1.5), ("D", 0.1), ("mu", 0.001002)],
        lists: &[],
        expected: &[("re", 149401.19760479042)],
    },
    tests: REYNOLDS_NUMBER_TESTS,
};

/// Every calculation in the registry, sorted by id.
static ALL_SPECS: &[&CalcSpec] = &[
    &CRANE_K_FACTORS_SPEC,
    &DARCY_WEISBACH_SPEC,
    &FRICTION_FACTOR_COLEBROOK_SPEC,
    &FRICTION_FACTOR_SWAMEE_JAIN_SPEC,
    &REYNOLDS_NUMBER_SPEC,
];

/// All specs, in a stable order.
#[must_use]
pub fn specs() -> &'static [&'static CalcSpec] {
    ALL_SPECS
}

/// Look up a spec by id.
#[must_use]
pub fn spec(id: &str) -> Option<&'static CalcSpec> {
    ALL_SPECS.iter().copied().find(|s| s.id == id)
}
