//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_models.py` from:
//!   - specs/models/process/separator.yaml
//!
//! Regenerate with `python tools/gen_models.py`; CI runs `--check` and fails
//! on any difference.

use azoth_core::{
    Band, ModelAlgorithm, ModelSpec, RangeCheck, Severity, SpecCheck, TestCase, WarningCode,
};

static SEPARATOR_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "n",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a flow of zero moles is not a stream, and the duty branch divides by it - so a zero would reach the arithmetic as a division by zero rather than as a rejected input.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "pressure_drop",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a separator drops pressure. A negative drop is a pressure rise, which is a compressor, and admitting it here would let a caller model one by accident and get an answer that is arithmetically fine and physically nonsense.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states. `P - pressure_drop` at or below zero is caught by the flash rather than here, because the check the flash already applies is the one that matters.",
        },
    },
];

static SEPARATOR_CASES: &[TestCase] = &[
    TestCase {
        id: "a_two_phase_feed_splits_by_the_flash_vapour_fraction",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("pressure_drop", 0.0),
            ("heat_duty", 0.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("T", 300.0),
            ("P", 2000000.0),
            ("beta", 0.6824390296506371),
            ("gas_flow", 6.824390296506371),
            ("liquid_flow", 3.175609703493629),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_pressure_drop_leaves_the_temperature_alone",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("pressure_drop", 500000.0),
            ("heat_duty", 0.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 300.0), ("P", 1500000.0)],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_single_phase_feed_leaves_one_outlet_empty",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 450.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("pressure_drop", 0.0),
            ("heat_duty", 0.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("T", 450.0),
            ("P", 2000000.0),
            ("gas_flow", 10.0),
            ("liquid_flow", 0.0),
        ],
        expected_vectors: &[],
    },
];

static SEPARATOR_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "rachford_rice_bisection",
    convergence: "absolute",
    tolerance: 1e-14,
    max_iterations: 200,
    bracket: None,
    initialisation: None,
    inner: None,
};

static SEPARATOR_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "flash_then_phase_split",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    inner: Some(&SEPARATOR_INNER),
};

/// Registry entry for `process.separator`.
pub static SEPARATOR_SPEC: ModelSpec = ModelSpec {
    id: "process.separator",
    kind: "procedure",
    algorithm: Some(&SEPARATOR_ALGORITHM),
    checks: SEPARATOR_CHECKS,
    cases: SEPARATOR_CASES,
};

static ALL_MODELS: &[&ModelSpec] = &[&SEPARATOR_SPEC];

/// Every model in this namespace, in id order.
#[must_use]
pub fn models() -> &'static [&'static ModelSpec] {
    ALL_MODELS
}

/// One model by id, or `None`. Used by the contract tests.
#[must_use]
pub fn model(id: &str) -> Option<&'static ModelSpec> {
    ALL_MODELS.iter().copied().find(|m| m.id == id)
}
