//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_models.py` from:
//!   - specs/models/process/pump.toml
//!   - specs/models/process/splitter.toml
//!
//! Regenerate with `python tools/gen_models.py`; CI runs `--check` and fails
//! on any difference.

use azoth_core::{Band, ModelSpec, RangeCheck, Severity, SpecCheck, TestCase, WarningCode};

static PUMP_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "isentropic_efficiency",
            min: Some(0.0),
            min_inclusive: false,
            max: Some(1.0),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "the reversible work divides by it, so zero has no answer and above one would recover more work than isentropic",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "inlet_t",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature",
        },
    },
];

static PUMP_CASES: &[TestCase] = &[
    TestCase {
        id: "butane_5_to_20_bara_at_250_k",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-05,
        numbers: &[
            ("inlet_n", 1.0),
            ("inlet_p", 500000.0),
            ("inlet_t", 250.0),
            ("outlet_pressure", 2000000.0),
            ("isentropic_efficiency", 0.75),
        ],
        flags: &[],
        lists: &[("components", &["n-butane"])],
        strings: &[],
        vectors: &[("inlet_z", &[1.0])],
        matrices: &[],
        expected: &[
            ("outlet_n", 1.0),
            ("outlet_p", 2000000.0),
            ("outlet_t", 250.76214168277508),
            ("outlet_h", -25382.694279985513),
        ],
        expected_vectors: &[("outlet_z", &[1.0])],
        expected_strings: &[],
    },
    TestCase {
        id: "the_work_divides_by_the_efficiency",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-05,
        numbers: &[
            ("inlet_n", 1.0),
            ("inlet_p", 500000.0),
            ("inlet_t", 250.0),
            ("outlet_pressure", 2000000.0),
            ("isentropic_efficiency", 1.0),
        ],
        flags: &[],
        lists: &[("components", &["n-butane"])],
        strings: &[],
        vectors: &[("inlet_z", &[1.0])],
        matrices: &[],
        expected: &[
            ("outlet_n", 1.0),
            ("outlet_p", 2000000.0),
            ("outlet_t", 250.40558913594867),
            ("outlet_h", -25426.73406996356),
        ],
        expected_vectors: &[("outlet_z", &[1.0])],
        expected_strings: &[],
    },
];

/// Registry entry for `process.pump`.
pub static PUMP_SPEC: ModelSpec = ModelSpec {
    id: "process.pump",
    kind: "direct",
    algorithm: None,
    checks: PUMP_CHECKS,
    cases: PUMP_CASES,
};

static SPLITTER_CHECKS: &[SpecCheck] = &[SpecCheck {
    on_input: true,
    check: RangeCheck {
        quantity: "feed_t",
        min: Some(0.0),
        min_inclusive: false,
        max: None,
        max_inclusive: true,
        equals: None,
        band: Band::Outside,
        severity: Severity::Error,
        code: WarningCode::OutOfValidRange,
        rationale: "an absolute temperature",
    },
}];

static SPLITTER_CASES: &[TestCase] = &[
    TestCase {
        id: "a_two_way_split_of_a_liquid",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-05,
        numbers: &[("feed_n", 1.0), ("feed_p", 1000000.0), ("feed_t", 300.0)],
        flags: &[],
        lists: &[("components", &["n-butane", "n-pentane"])],
        strings: &[],
        vectors: &[("feed_z", &[0.6, 0.4]), ("split_factors", &[0.3, 0.7])],
        matrices: &[],
        expected: &[],
        expected_vectors: &[
            ("products_n", &[0.3, 0.7]),
            ("products_p", &[1000000.0, 1000000.0]),
            ("products_t", &[300.0, 300.0]),
            ("products_h", &[-20689.86284462001, -20689.86284462001]),
        ],
        expected_strings: &[],
    },
    TestCase {
        id: "the_factors_are_normalised",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-05,
        numbers: &[("feed_n", 1.0), ("feed_p", 1000000.0), ("feed_t", 300.0)],
        flags: &[],
        lists: &[("components", &["n-butane", "n-pentane"])],
        strings: &[],
        vectors: &[("feed_z", &[0.6, 0.4]), ("split_factors", &[3.0, 7.0])],
        matrices: &[],
        expected: &[],
        expected_vectors: &[
            ("products_n", &[0.3, 0.7]),
            ("products_p", &[1000000.0, 1000000.0]),
            ("products_t", &[300.0, 300.0]),
            ("products_h", &[-20689.86284462001, -20689.86284462001]),
        ],
        expected_strings: &[],
    },
];

/// Registry entry for `process.splitter`.
pub static SPLITTER_SPEC: ModelSpec = ModelSpec {
    id: "process.splitter",
    kind: "direct",
    algorithm: None,
    checks: SPLITTER_CHECKS,
    cases: SPLITTER_CASES,
};

static ALL_MODELS: &[&ModelSpec] = &[&PUMP_SPEC, &SPLITTER_SPEC];

/// Every model in this namespace, in id order.
#[must_use]
pub fn models() -> &'static [&'static ModelSpec] {
    ALL_MODELS
}

/// One model by id, or `None`. Used by the contract tests.
#[must_use]
pub fn model(id: &str) -> Option<&'static ModelSpec> {
    ALL_MODELS.iter().copied().find(|m| m.id == id)
}
