//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_models.py` from:
//!   - specs/models/process/compressor.yaml
//!   - specs/models/process/expander.yaml
//!   - specs/models/process/heater.yaml
//!   - specs/models/process/mixer.yaml
//!   - specs/models/process/pump.yaml
//!   - specs/models/process/separator.yaml
//!   - specs/models/process/splitter.yaml
//!   - specs/models/process/throttling_valve.yaml
//!
//! Regenerate with `python tools/gen_models.py`; CI runs `--check` and fails
//! on any difference.

use azoth_core::{
    Band, ModelAlgorithm, ModelSpec, RangeCheck, Severity, SpecCheck, TestCase, WarningCode,
};

static COMPRESSOR_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "efficiency",
            min: Some(0.0),
            min_inclusive: false,
            max: Some(1.0),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an efficiency above one is a machine that beats the second law, and zero makes the ideal enthalpy change infinite. NeqSim allows the same range and **clamps** to it rather than refusing (`Compressor.java:2118`); a clamp turns a caller's mistake into a slightly different answer that looks deliberate, so this refuses instead.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "outlet_pressure",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "n",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a flow of zero moles has no power to compute",
        },
    },
];

static COMPRESSOR_CASES: &[TestCase] = &[
    TestCase {
        id: "a_two_to_one_pressure_rise_at_three_quarters_efficiency",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("outlet_pressure", 4000000.0),
            ("efficiency", 0.75),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("T", 328.0895199847116),
            ("P", 4000000.0),
            ("power", 15274.141966358111),
            ("isentropic_temperature", 324.9618248392254),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "unit_efficiency_reaches_the_ideal_temperature",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("outlet_pressure", 4000000.0),
            ("efficiency", 1.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("P", 4000000.0),
            ("isentropic_temperature", 324.9618248392254),
        ],
        expected_vectors: &[],
    },
];

static COMPRESSOR_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "successive_substitution_flash",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: None,
};

static COMPRESSOR_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "isentropic_efficiency_flash",
    convergence: "relative",
    tolerance: 1e-08,
    max_iterations: 200,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: Some(&COMPRESSOR_INNER),
};

/// Registry entry for `process.compressor`.
pub static COMPRESSOR_SPEC: ModelSpec = ModelSpec {
    id: "process.compressor",
    kind: "procedure",
    algorithm: Some(&COMPRESSOR_ALGORITHM),
    checks: COMPRESSOR_CHECKS,
    cases: COMPRESSOR_CASES,
};

static EXPANDER_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "efficiency",
            min: Some(0.0),
            min_inclusive: false,
            max: Some(1.0),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an efficiency above one would give more work than the isentropic drop contains. Inherited from NeqSim's `Compressor` setter, which clamps to this range (`Compressor.java:2118`); this refuses instead.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "outlet_pressure",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "n",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a flow of zero moles has no power to compute",
        },
    },
];

static EXPANDER_CASES: &[TestCase] = &[
    TestCase {
        id: "twenty_to_five_bar_at_ninety_percent",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("outlet_pressure", 500000.0),
            ("efficiency", 0.9),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("T", 259.8355676783778),
            ("P", 500000.0),
            ("power", -18911.45107513822),
            ("isentropic_temperature", 258.3310655160541),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_superheated_feed_expands_to_vapour",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 450.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("outlet_pressure", 500000.0),
            ("efficiency", 0.9),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("T", 320.8267034829063),
            ("P", 500000.0),
            ("power", -37081.70547629313),
            ("isentropic_temperature", 308.3776788396833),
        ],
        expected_vectors: &[],
    },
];

static EXPANDER_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "successive_substitution_flash",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: None,
};

static EXPANDER_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "isentropic_efficiency_flash",
    convergence: "relative",
    tolerance: 1e-08,
    max_iterations: 200,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: Some(&EXPANDER_INNER),
};

/// Registry entry for `process.expander`.
pub static EXPANDER_SPEC: ModelSpec = ModelSpec {
    id: "process.expander",
    kind: "procedure",
    algorithm: Some(&EXPANDER_ALGORITHM),
    checks: EXPANDER_CHECKS,
    cases: EXPANDER_CASES,
};

static HEATER_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "n",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "the model divides the duty by the flow. A zero would reach the arithmetic as a division by zero, and a negative would give a temperature change of the wrong sign for a stream flowing the other way.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
];

static HEATER_CASES: &[TestCase] = &[
    TestCase {
        id: "fifty_kilowatts_on_ten_moles_per_second",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("pressure_drop", 0.0),
            ("heat_duty", 50000.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 328.5648195981979), ("P", 2000000.0)],
        expected_vectors: &[],
    },
    TestCase {
        id: "no_duty_is_the_identity",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-07,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("pressure_drop", 0.0),
            ("heat_duty", 0.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 300.0), ("P", 2000000.0)],
        expected_vectors: &[],
    },
];

static HEATER_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "successive_substitution_flash",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: None,
};

static HEATER_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "duty_enthalpy_flash",
    convergence: "relative",
    tolerance: 1e-08,
    max_iterations: 200,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: Some(&HEATER_INNER),
};

/// Registry entry for `process.heater`.
pub static HEATER_SPEC: ModelSpec = ModelSpec {
    id: "process.heater",
    kind: "procedure",
    algorithm: Some(&HEATER_ALGORITHM),
    checks: HEATER_CHECKS,
    cases: HEATER_CASES,
};

static MIXER_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "n",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "each inlet must carry something. A zero-flow inlet contributes no moles and no enthalpy, and the blend's division by the total flow would fail if they all were - so the check is on the *smallest* inlet, which is the one that would produce a meaningless composition row.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
];

static MIXER_CASES: &[TestCase] = &[
    TestCase {
        id: "two_different_feeds_blend",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T_ref", 300.0), ("P_ref", 100000.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("T", &[300.0, 350.0]),
            ("P", &[2000000.0, 1500000.0]),
            ("n", &[6.0, 4.0]),
        ],
        matrices: &[
            ("kij", &[0.0, 0.01289789, 0.01289789, 0.0]),
            ("z", &[0.6, 0.4, 0.4, 0.6]),
        ],
        expected: &[("T", 321.10986042022694), ("P", 1500000.0), ("flow", 10.0)],
        expected_vectors: &[("z_out", &[0.52, 0.48])],
    },
    TestCase {
        id: "two_identical_feeds_double_the_flow_and_change_nothing_else",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-07,
        numbers: &[("T_ref", 300.0), ("P_ref", 100000.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("T", &[300.0, 300.0]),
            ("P", &[2000000.0, 2000000.0]),
            ("n", &[6.0, 4.0]),
        ],
        matrices: &[
            ("kij", &[0.0, 0.01289789, 0.01289789, 0.0]),
            ("z", &[0.6, 0.4, 0.6, 0.4]),
        ],
        expected: &[("T", 300.0), ("P", 2000000.0), ("flow", 10.0)],
        expected_vectors: &[("z_out", &[0.6, 0.4])],
    },
];

static MIXER_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "successive_substitution_flash",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: None,
};

static MIXER_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "blend_then_isenthalpic_flash",
    convergence: "relative",
    tolerance: 1e-08,
    max_iterations: 200,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: Some(&MIXER_INNER),
};

/// Registry entry for `process.mixer`.
pub static MIXER_SPEC: ModelSpec = ModelSpec {
    id: "process.mixer",
    kind: "procedure",
    algorithm: Some(&MIXER_ALGORITHM),
    checks: MIXER_CHECKS,
    cases: MIXER_CASES,
};

static PUMP_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "efficiency",
            min: Some(0.0),
            min_inclusive: false,
            max: Some(1.0),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an efficiency above one is a machine that beats the second law, and zero makes the ideal enthalpy change infinite. NeqSim's setter assigns without clamping here (`Pump.java:854`), which is worse than clamping rather than better.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "outlet_pressure",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "n",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a flow of zero moles has no power to compute",
        },
    },
];

static PUMP_CASES: &[TestCase] = &[
    TestCase {
        id: "twenty_to_thirty_bar_at_eighty_percent",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("outlet_pressure", 3000000.0),
            ("efficiency", 0.8),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("T", 315.6004299531121),
            ("P", 3000000.0),
            ("power", 8294.83382119513),
            ("isentropic_temperature", 314.2567931729825),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_liquid_feed_is_pumped",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 4000000.0),
            ("n", 10.0),
            ("outlet_pressure", 5000000.0),
            ("efficiency", 0.8),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.2, 0.8]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("T", 301.2741362140612),
            ("P", 5000000.0),
            ("power", 1124.4773017828265),
            ("isentropic_temperature", 300.99279887328595),
        ],
        expected_vectors: &[],
    },
];

static PUMP_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "successive_substitution_flash",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: None,
};

static PUMP_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "isentropic_efficiency_flash",
    convergence: "relative",
    tolerance: 1e-08,
    max_iterations: 200,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: Some(&PUMP_INNER),
};

/// Registry entry for `process.pump`.
pub static PUMP_SPEC: ModelSpec = ModelSpec {
    id: "process.pump",
    kind: "procedure",
    algorithm: Some(&PUMP_ALGORITHM),
    checks: PUMP_CHECKS,
    cases: PUMP_CASES,
};

static SEPARATOR_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "n",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a flow of zero moles is not a stream, and the duty branch divides by it - so a zero would reach the arithmetic as a division by zero rather than as a rejected input.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "pressure_drop",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a separator drops pressure. A negative drop is a pressure rise, which is a compressor, and admitting it here would let a caller model one by accident and get an answer that is arithmetically fine and physically nonsense.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states. `P - pressure_drop` at or below zero is caught by the flash rather than here, because the check the flash already applies is the one that matters.",
        },
    },
];

static SEPARATOR_CASES: &[TestCase] = &[
    TestCase {
        id: "a_two_phase_feed_splits_by_the_flash_vapour_fraction",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("pressure_drop", 0.0),
            ("heat_duty", 0.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("T", 300.0),
            ("P", 2000000.0),
            ("beta", 0.6824390296506371),
            ("gas_flow", 6.824390296506371),
            ("liquid_flow", 3.175609703493629),
        ],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_pressure_drop_leaves_the_temperature_alone",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("pressure_drop", 500000.0),
            ("heat_duty", 0.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 300.0), ("P", 1500000.0)],
        expected_vectors: &[],
    },
    TestCase {
        id: "a_single_phase_feed_leaves_one_outlet_empty",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 450.0),
            ("P", 2000000.0),
            ("n", 10.0),
            ("pressure_drop", 0.0),
            ("heat_duty", 0.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[
            ("T", 450.0),
            ("P", 2000000.0),
            ("gas_flow", 10.0),
            ("liquid_flow", 0.0),
        ],
        expected_vectors: &[],
    },
];

static SEPARATOR_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "rachford_rice_bisection",
    convergence: "absolute",
    tolerance: 1e-14,
    max_iterations: 200,
    bracket: None,
    initialisation: None,
    initial_temperature: None,
    inner: None,
};

static SEPARATOR_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "flash_then_phase_split",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: Some(&SEPARATOR_INNER),
};

/// Registry entry for `process.separator`.
pub static SEPARATOR_SPEC: ModelSpec = ModelSpec {
    id: "process.separator",
    kind: "procedure",
    algorithm: Some(&SEPARATOR_ALGORITHM),
    checks: SEPARATOR_CHECKS,
    cases: SEPARATOR_CASES,
};

static SPLITTER_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "n",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a flow of zero moles has nothing to divide. The branches would all be zero and the fractions would have nothing to act on - a splitter with no feed is not a splitter.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure; zero and below are not states",
        },
    },
];

static SPLITTER_CASES: &[TestCase] = &[
    TestCase {
        id: "thirty_seventy_split_of_a_two_phase_feed",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 300.0), ("P", 2000000.0), ("n", 10.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("z", &[0.6, 0.4]),
            ("fractions", &[0.3, 0.7]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 300.0), ("P", 2000000.0), ("beta", 0.6824390296509166)],
        expected_vectors: &[("flows", &[3.0, 7.0])],
    },
    TestCase {
        id: "a_single_branch_takes_everything",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[("T", 300.0), ("P", 2000000.0), ("n", 10.0)],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("z", &[0.6, 0.4]),
            ("fractions", &[1.0]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 300.0), ("P", 2000000.0)],
        expected_vectors: &[("flows", &[10.0])],
    },
];

static SPLITTER_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "rachford_rice_bisection",
    convergence: "absolute",
    tolerance: 1e-14,
    max_iterations: 200,
    bracket: None,
    initialisation: None,
    initial_temperature: None,
    inner: None,
};

static SPLITTER_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "flow_scaled_isothermal_flash",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: Some(&SPLITTER_INNER),
};

/// Registry entry for `process.splitter`.
pub static SPLITTER_SPEC: ModelSpec = ModelSpec {
    id: "process.splitter",
    kind: "procedure",
    algorithm: Some(&SPLITTER_ALGORITHM),
    checks: SPLITTER_CHECKS,
    cases: SPLITTER_CASES,
};

static THROTTLING_VALVE_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "pressure_drop",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a throttling valve drops pressure. NeqSim has an `acceptNegativeDp` flag (`ThrottlingValve.java:424-432`) for the transient case; a steady-state model that admitted a rise would let a caller model a compressor by accident and get an answer that is arithmetically fine and physically nonsense.",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "T",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute temperature; zero and below are not states",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "P",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "an absolute pressure. A drop that takes the outlet to or below zero is caught by the flash, whose own check on a non-positive pressure is the one that matters.",
        },
    },
];

static THROTTLING_VALVE_CASES: &[TestCase] = &[
    TestCase {
        id: "a_five_bar_drop_cools_the_stream",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("pressure_drop", 500000.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 293.9107699394226), ("P", 1500000.0)],
        expected_vectors: &[],
    },
    TestCase {
        id: "no_drop_leaves_the_stream_alone",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-07,
        numbers: &[
            ("T_ref", 300.0),
            ("P_ref", 100000.0),
            ("T", 300.0),
            ("P", 2000000.0),
            ("pressure_drop", 0.0),
        ],
        lists: &[],
        vectors: &[
            ("Tc", &[190.56, 425.12]),
            ("Pc", &[4599000.0, 3796000.0]),
            ("omega", &[0.0115, 0.2002]),
            ("cp_a", &[3.0, 5.0]),
            ("cp_b", &[0.0, 0.0]),
            ("cp_c", &[0.0, 0.0]),
            ("cp_d", &[0.0, 0.0]),
            ("h_ref", &[0.0, 0.0]),
            ("s_ref", &[0.0, 0.0]),
            ("z", &[0.6, 0.4]),
        ],
        matrices: &[("kij", &[0.0, 0.01289789, 0.01289789, 0.0])],
        expected: &[("T", 300.0), ("P", 2000000.0)],
        expected_vectors: &[],
    },
];

static THROTTLING_VALVE_INNER: ModelAlgorithm = ModelAlgorithm {
    scheme: "successive_substitution_flash",
    convergence: "absolute",
    tolerance: 1e-10,
    max_iterations: 300,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: None,
};

static THROTTLING_VALVE_ALGORITHM: ModelAlgorithm = ModelAlgorithm {
    scheme: "isenthalpic_flash",
    convergence: "relative",
    tolerance: 1e-08,
    max_iterations: 200,
    bracket: None,
    initialisation: Some("wilson"),
    initial_temperature: None,
    inner: Some(&THROTTLING_VALVE_INNER),
};

/// Registry entry for `process.throttling_valve`.
pub static THROTTLING_VALVE_SPEC: ModelSpec = ModelSpec {
    id: "process.throttling_valve",
    kind: "procedure",
    algorithm: Some(&THROTTLING_VALVE_ALGORITHM),
    checks: THROTTLING_VALVE_CHECKS,
    cases: THROTTLING_VALVE_CASES,
};

static ALL_MODELS: &[&ModelSpec] = &[
    &COMPRESSOR_SPEC,
    &EXPANDER_SPEC,
    &HEATER_SPEC,
    &MIXER_SPEC,
    &PUMP_SPEC,
    &SEPARATOR_SPEC,
    &SPLITTER_SPEC,
    &THROTTLING_VALVE_SPEC,
];

/// Every model in this namespace, in id order.
#[must_use]
pub fn models() -> &'static [&'static ModelSpec] {
    ALL_MODELS
}

/// One model by id, or `None`. Used by the contract tests.
#[must_use]
pub fn model(id: &str) -> Option<&'static ModelSpec> {
    ALL_MODELS.iter().copied().find(|m| m.id == id)
}
