"""Type stub for the compiled extension.

Generated by `tools/gen_stub.py` from the result dataclasses and the specs. Do
not edit by hand: the result classes below are what `azoth.core.result` says, the
signatures are what the specs declare, and both are already asserted equal to the
Rust side by tests.

Nothing here is part of the public API. `azoth.hydraulics` is, and it returns the
result dataclasses in `azoth.core.result` rather than the transport types below -
see `azoth._rust_bridge`.
"""

from typing import TypedDict, final

# --- transport types ------------------------------------------------------
# The values that cross the boundary and are not results. Hand-written here
# because a `cdylib` has nothing to introspect; held to the Rust structs by
# `test_the_stub_matches_the_rust_transport_types`.

class ComponentArguments(TypedDict):
    """One substance as a keycard states it, on its way to the overlay. A record rather than a tuple, because it outgrew one: the ion class and the electrolyte data joined `Tc`, `Pc` and `omega`. Every field is optional for the reason the first three always were - a card stating one parameter keeps the rest - and `ion` is `None` for "the card says nothing", which is deliberately not `False`."""

    name: str
    tc: float | None
    pc: float | None
    omega: float | None
    ion: bool | None
    ionic_charge: float | None
    deshmukh_mather_diameter: float | None
    dielectric: list[float] | None

@final
class AssociationSpec:
    """One mixture's association, as every model whose Python side takes a `Mixture` requires it."""

    associating: bool
    schemes: list[str]
    values: list[list[float]]
    def __init__(self, associating: bool, schemes: list[str], values: list[list[float]]) -> None: ...

@final
class DataFile:
    name: str
    path: str
    text: str

@final
class FittingRow:
    id: str
    family: str
    name: str
    n_ld: float
    f_t_basis: str
    citation: str
    verify_status: str

@final
class FluidRow:
    fluid: str
    temperature_c: float
    density_kg_m3: float
    dynamic_viscosity_pa_s: float
    citation: str
    verify_status: str

@final
class ComponentRow:
    """One row of the component databank, as the Rust core parsed it."""

    name: str
    tc_k: float
    pc_pa: float
    acentric_factor: float
    cp_a: float | None
    cp_b: float | None
    cp_c: float | None
    cp_d: float | None
    cp_e: float | None
    association_scheme: str
    association_sites: int
    association_energy: float
    association_volume_srk: float
    association_a_srk: float
    association_b_srk: float
    association_m_srk: float
    association_volume_pr: float
    association_a_pr: float
    association_b_pr: float
    association_m_pr: float
    association_racket_z: float
    association_volume_correction: float
    component_type: str
    ionic_charge: float
    deshmukh_mather_diameter: float
    dielectric: list[float]

@final
class KijRow:
    """One row of the interaction table, as the Rust core parsed it."""

    component_a: str
    component_b: str
    kij_pr: float
    kij_srk: float

@final
class Overlay:
    """A keycard's sections, as the extension reads them. Built either entry by entry from the values `azoth.keycard` resolved to or by reading a card's text with `card_overlay`, and opaque: what it resolves to is read through `overlay_entry_row` and its siblings."""


@final
class Qty:
    """A physical quantity: always SI magnitude, plus a canonical unit label."""

    magnitude_si: float
    unit: str
    def __init__(self, magnitude_si: float, unit: str) -> None: ...

@final
class Warning:
    """A warning, transported. `code` is the SCREAMING_SNAKE_CASE string."""

    code: str
    message: str
    field: str | None

@final
class BatchColumn:
    name: str
    unit: str
    values: list[float] | None
    labels: list[str | None] | None

@final
class BatchResult:
    columns: list[BatchColumn]
    warnings: list[list[Warning]]

@final
class KComponent:
    """One fitting's contribution to the total resistance coefficient."""

    fitting_id: str
    n_ld: float
    k: float

@final
class Session:
    """A live flowsheet: the middleware's session, which holds the document so an edit re-checks it and a run's values belong to the document that produced them. Every mutating call returns the whole envelope as the wire's JSON."""

    def __init__(self, document: str, palette_dir: str | None = ...) -> None: ...
    def apply(self, command: str) -> str: ...
    def set_order(self, order: str) -> str: ...
    def run(self) -> str: ...
    def envelope(self) -> str: ...
    def document(self) -> str: ...
    def graph(self) -> str: ...
    def value(self, path: str) -> float: ...
    @property
    def paths(self) -> list[str]: ...
    @property
    def ok(self) -> bool: ...
    @property
    def dirty(self) -> bool: ...
    @property
    def run_error(self) -> str | None: ...

@final
class Stream:
    """A material stream: composition, molar flow, pressure, temperature and molar enthalpy. All SI magnitudes - `p` in pascals, `t` in kelvin, `h` in J/mol, `n` in mol/s."""

    components: list[str]
    z: list[float]
    n: float
    p: float
    t: float
    h: float
    def __init__(self, components: list[str], z: list[float], n: float, p: float, t: float) -> None: ...
    @staticmethod
    def from_ph(components: list[str], z: list[float], n: float, p: float, h: float) -> Stream: ...

# --- results --------------------------------------------------------------
# Generated from the result dataclasses, so the stub and `azoth.core.result`
# cannot disagree about a field.

@final
class AmmoniaPhaseResult:
    z_factor: float
    u: Qty
    h: Qty
    s: Qty
    cv: Qty
    cp: Qty
    g: Qty
    warnings: list[Warning]

@final
class AntoineVaporPressureResult:
    p_sat: Qty
    warnings: list[Warning]

@final
class AqueousViscosityResult:
    viscosity: Qty
    warnings: list[Warning]

@final
class ArgonSolidPhaseResult:
    z_factor: float
    u: Qty
    h: Qty
    s: Qty
    cv: Qty
    cp: Qty
    g: Qty
    warnings: list[Warning]

@final
class BubblePressureResult:
    pressure: Qty
    incipient: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    min_t_over_tc: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class BubbleTemperatureResult:
    temperature: Qty
    incipient: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    min_t_over_tc: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class BwrsPhaseResult:
    z_factor: float
    ln_phi: list[float]
    h_res: Qty
    s_res: Qty
    cp_res: Qty
    warnings: list[Warning]

@final
class CapillaryDewPointResult:
    temperature: Qty
    incipient: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    capillary_pressure: Qty
    min_t_over_tc: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class ChungConductivityResult:
    k: Qty
    warnings: list[Warning]

@final
class ChungViscosityResult:
    mu: Qty
    warnings: list[Warning]

@final
class Co2PhaseResult:
    z_factor: float
    u: Qty
    h: Qty
    s: Qty
    cv: Qty
    cp: Qty
    g: Qty
    warnings: list[Warning]

@final
class Co2WaterDiffusivityResult:
    d: Qty
    warnings: list[Warning]

@final
class CostaldMolarVolumeResult:
    v: Qty
    warnings: list[Warning]

@final
class CriticalPointResult:
    tc: Qty
    pc: Qty
    vc: Qty
    z_c: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class DesmukhMatherPhaseResult:
    gamma: list[float]
    ln_gamma: list[float]
    molality: list[float]
    ionic_strength: float
    solvent_molar_mass: float
    ln_phi: list[float]
    warnings: list[Warning]

@final
class DewPressureResult:
    pressure: Qty
    incipient: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    min_t_over_tc: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class DewTemperatureResult:
    temperature: Qty
    incipient: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    min_t_over_tc: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class EffectiveDiffusionResult:
    effective_diffusion: list[Qty]
    warnings: list[Warning]

@final
class EosCgPhaseResult:
    z_factor: float
    u: Qty
    h: Qty
    s: Qty
    cv: Qty
    cp: Qty
    g: Qty
    warnings: list[Warning]

@final
class FreezingPointResult:
    temperature: Qty
    component: str
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class FullerSchettlerGiddingsDiffusivityResult:
    d: Qty
    warnings: list[Warning]

@final
class FurstElectrolyteMod2004PhaseResult:
    z_factor: float
    ln_phi: list[float]
    warnings: list[Warning]

@final
class FurstElectrolytePhaseResult:
    z_factor: float
    ln_phi: list[float]
    warnings: list[Warning]

@final
class GeFlashResult:
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    ln_phi_liquid: list[float]
    ln_phi_vapour: list[float]
    z_vapour: float
    min_t_over_tc: float
    phase: str
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class GeNrtlFlashResult:
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    ln_phi_liquid: list[float]
    ln_phi_vapour: list[float]
    z_vapour: float
    min_t_over_tc: float
    phase: str
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class GeNrtlPhaseResult:
    gamma: list[float]
    ln_gamma: list[float]
    ln_phi: list[float]
    p_sat: list[Qty]
    warnings: list[Warning]

@final
class GeUnifacPhaseResult:
    gamma: list[float]
    ln_gamma: list[float]
    ln_phi: list[float]
    p_sat: list[Qty]
    warnings: list[Warning]

@final
class GeUniquacPhaseResult:
    gamma: list[float]
    ln_gamma: list[float]
    ln_phi: list[float]
    p_sat: list[Qty]
    warnings: list[Warning]

@final
class GeVanLaarAcidPhaseResult:
    gamma: list[float]
    ln_gamma: list[float]
    ln_phi: list[float]
    p_sat: list[Qty]
    warnings: list[Warning]

@final
class GeWilsonPhaseResult:
    gamma: list[float]
    ln_gamma: list[float]
    ln_phi: list[float]
    p_sat: list[Qty]
    warnings: list[Warning]

@final
class Gerg2008PhaseResult:
    z_factor: float
    u: Qty
    h: Qty
    s: Qty
    cv: Qty
    cp: Qty
    g: Qty
    warnings: list[Warning]

@final
class HaydukMinhasDiffusivityResult:
    d: Qty
    warnings: list[Warning]

@final
class HeatOfVaporizationResult:
    hov: Qty
    warnings: list[Warning]

@final
class HeliumPhaseResult:
    z_factor: float
    u: Qty
    h: Qty
    s: Qty
    cv: Qty
    cp: Qty
    g: Qty
    warnings: list[Warning]

@final
class HybridEosGeFlashResult:
    beta: list[float]
    x: list[list[float]]
    ln_phi: list[list[float]]
    iterations: int
    residual: float
    max_material_balance_residual: float
    max_log_fugacity_residual: float
    min_t_over_tc: float
    warnings: list[Warning]

@final
class HydrateEquilibriumLineResult:
    temperature: list[float]
    pressure: list[float]
    warnings: list[Warning]

@final
class HydrateFormationPressureResult:
    pressure: Qty
    structure: str
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class HydrateFormationTemperatureResult:
    temperature: Qty
    structure: str
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class HydrateFractionResult:
    beta: float
    structure: str
    balance_error: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class HydrateInhibitorConcentrationResult:
    inhibitor_moles: float
    weight_fraction: float
    hydrate_temperature: Qty
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class HydrateInhibitorWtResult:
    inhibitor_moles: float
    weight_fraction: float
    phases: int
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class HydrogenPhaseResult:
    z_factor: float
    u: Qty
    h: Qty
    s: Qty
    cv: Qty
    cp: Qty
    g: Qty
    warnings: list[Warning]

@final
class IapwsHenryLawResult:
    henry: Qty
    ln_henry: float
    d_ln_henry_d_t: float
    status: str
    rms_log_residual: float
    warnings: list[Warning]

@final
class IdealGasCpResult:
    cp: Qty
    warnings: list[Warning]

@final
class KentEisenbergPhaseResult:
    gamma: list[float]
    ln_gamma: list[float]
    ln_phi: list[float]
    warnings: list[Warning]

@final
class LiquidHeatCapacityResult:
    cp: Qty
    warnings: list[Warning]

@final
class MasonSaxenaConductivityResult:
    k: Qty
    warnings: list[Warning]

@final
class Matcop5PrumrAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class MatcopAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class MatcopPrAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class MatcopPrumrAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class MatcopPrumrNewAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class MolarEnthalpyEntropyResult:
    h: Qty
    s: Qty
    h_ideal: Qty
    s_ideal: Qty
    h_departure: Qty
    s_departure: Qty
    psi_bar: float
    cp: Qty
    cp_ideal: Qty
    cp_departure: Qty
    warnings: list[Warning]

@final
class MollerupAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class NitricSulfuricAcidVaporPressureResult:
    p_water: Qty
    p_nitric_acid: Qty
    p_sulfuric_acid: Qty
    warnings: list[Warning]

@final
class NrtlActivityCoefficientsResult:
    ln_gamma: list[float]
    gamma: list[float]
    warnings: list[Warning]

@final
class ParachorMixtureSurfaceTensionResult:
    sigma: Qty
    warnings: list[Warning]

@final
class ParachorSurfaceTensionResult:
    sigma: Qty
    warnings: list[Warning]

@final
class ParahydrogenSolidPhaseResult:
    z_factor: float
    u: Qty
    h: Qty
    s: Qty
    cv: Qty
    cp: Qty
    g: Qty
    warnings: list[Warning]

@final
class PcsaftRahmatPhaseResult:
    z_factor: float
    ln_phi: list[float]
    v: Qty
    h_res: Qty
    s_res: Qty
    warnings: list[Warning]

@final
class PhFlashResult:
    T: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PitzerPhaseResult:
    gamma: list[float]
    ln_gamma: list[float]
    ln_phi: list[float]
    henry: list[Qty]
    gamma_inf: list[float]
    molality: list[float]
    ionic_strength: float
    osmotic_coefficient: float
    water_activity: float
    dataset: str
    warnings: list[Warning]

@final
class Pr78KappaResult:
    kappa: float
    warnings: list[Warning]

@final
class PrAlphaAbResult:
    alpha: float
    a_reduced: float
    b_reduced: float
    warnings: list[Warning]

@final
class PrCpaPhaseResult:
    z_factor: float
    ln_phi: list[float]
    h_res: Qty
    s_res: Qty
    warnings: list[Warning]

@final
class PrDaneshAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class PrDelft1998AlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class PrDepartureResult:
    ln_phi: float
    h_dep_rt: float
    s_dep_r: float
    cp_dep_r: float
    warnings: list[Warning]

@final
class PrGassem2001AlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class PrKappaResult:
    kappa: float
    warnings: list[Warning]

@final
class PrLeeKeslerAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class PrMassDensityResult:
    rho: Qty
    warnings: list[Warning]

@final
class PrMolarVolumeResult:
    v: Qty
    warnings: list[Warning]

@final
class PrPenelouxShiftResult:
    c: Qty
    warnings: list[Warning]

@final
class PrZFactorResult:
    z_min: float
    z_max: float
    root_structure: str
    iterations: int
    converged: bool
    residual: float
    warnings: list[Warning]

@final
class PrsvKappaResult:
    kappa: float
    warnings: list[Warning]

@final
class PsFlashResult:
    T: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PtFlashResult:
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    ln_phi_liquid: list[float]
    ln_phi_vapour: list[float]
    z_liquid: float
    z_vapour: float
    min_t_over_tc: float
    phase: str
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PtPhaseEnvelopeResult:
    dew_temperature: list[float]
    dew_pressure: list[float]
    bubble_temperature: list[float]
    bubble_pressure: list[float]
    cricondenbar_temperature: Qty
    cricondenbar_pressure: Qty
    cricondentherm_temperature: Qty
    cricondentherm_pressure: Qty
    critical_temperature: Qty
    critical_pressure: Qty
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PuFlashResult:
    T: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PureSaturationResult:
    p_sat: Qty
    ln_phi: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PvFlashResult:
    T: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PvRefluxFlashResult:
    T: Qty
    beta: float | None
    phase: str
    x: list[float]
    y: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PvfFlashResult:
    T: Qty
    beta: float
    phase: str
    x: list[float]
    y: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class RachfordRiceResult:
    beta: float
    warnings: list[Warning]

@final
class RachfordRiceBinaryResult:
    beta: float
    warnings: list[Warning]

@final
class RackettMolarVolumeResult:
    v: Qty
    warnings: list[Warning]

@final
class RkAlphaAbResult:
    alpha: float
    a_reduced: float
    b_reduced: float
    warnings: list[Warning]

@final
class RkDepartureResult:
    ln_phi: float
    h_dep_rt: float
    s_dep_r: float
    cp_dep_r: float
    warnings: list[Warning]

@final
class SaftVrMiePhaseResult:
    z_factor: float
    ln_phi: list[float]
    v: Qty
    h_res: Qty
    s_res: Qty
    warnings: list[Warning]

@final
class SaltPrecipitationResult:
    precipitated_moles: float
    initial_saturation_ratio: float
    final_saturation_ratio: float
    iterations: int
    extent_of_maximum: float
    warnings: list[Warning]

@final
class ScaleSaturationRatioResult:
    saturation_ratio: float
    ion_activity_product: float
    solubility_product: float
    warnings: list[Warning]

@final
class SchwartzentruberAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class SiddiqiLucasDiffusivityResult:
    d: Qty
    warnings: list[Warning]

@final
class SolidFugacityResult:
    fugacity_coefficient: float
    warnings: list[Warning]

@final
class SoreideWhitsonAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class SoreideWhitsonPhaseResult:
    z_factor: float
    ln_phi: list[float]
    warnings: list[Warning]

@final
class SrkAlphaAbResult:
    alpha: float
    a_reduced: float
    b_reduced: float
    warnings: list[Warning]

@final
class SrkCpaPhaseResult:
    z_factor: float
    ln_phi: list[float]
    h_res: Qty
    s_res: Qty
    warnings: list[Warning]

@final
class SrkDepartureResult:
    ln_phi: float
    h_dep_rt: float
    s_dep_r: float
    cp_dep_r: float
    warnings: list[Warning]

@final
class SrkKappaResult:
    kappa: float
    warnings: list[Warning]

@final
class SrkPenelouxShiftResult:
    c: Qty
    warnings: list[Warning]

@final
class SrkZFactorResult:
    z_min: float
    z_max: float
    root_structure: str
    iterations: int
    converged: bool
    residual: float
    warnings: list[Warning]

@final
class StabilityTestResult:
    verdict: str
    tm: list[float]
    w: list[list[float]]
    iterations: list[int]
    min_t_over_tc: float
    warnings: list[Warning]

@final
class TbpFractionPropertiesResult:
    tc: Qty
    pc: Qty
    boiling_temperature: Qty
    acentric_factor: float
    attraction_exponent: float
    warnings: list[Warning]

@final
class ThFlashResult:
    P: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class ThermalConductivityResult:
    k: Qty
    warnings: list[Warning]

@final
class TpFlashSaftResult:
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    ln_phi_liquid: list[float]
    ln_phi_vapour: list[float]
    z_liquid: float
    z_vapour: float
    phase: str
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class TpMultiflashResult:
    phase_count: int
    beta: list[float]
    x: list[list[float]]
    z_factor: list[float]
    ln_phi: list[list[float]]
    seeded: str
    tm: list[float]
    iterations: int
    residual: float
    min_t_over_tc: float
    warnings: list[Warning]

@final
class TpMultiflashWaxResult:
    wax_fraction: float
    phase_count: int
    beta: list[float]
    x: list[list[float]]
    iterations: int
    residual: float
    converged: bool
    warnings: list[Warning]

@final
class TpSolidFlashResult:
    solid_fraction: float
    phase_count: int
    beta: list[float]
    x: list[list[float]]
    solid_fugacity_coefficient: float
    iterations: int
    residual: float
    converged: bool
    warnings: list[Warning]

@final
class TsFlashResult:
    P: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class TuFlashResult:
    P: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class TvFlashResult:
    P: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class TvFractionFlashResult:
    P: Qty
    T: Qty
    beta: float | None
    volume_fraction: float
    phase: str
    x: list[float]
    y: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class TwuKappaResult:
    kappa: float
    warnings: list[Warning]

@final
class TwucoonAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class TwucoonParamAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class TwucoonStatoilAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class TynCalusDiffusivityResult:
    d: Qty
    warnings: list[Warning]

@final
class UmrCpaPhaseResult:
    z_factor: float
    ln_phi: list[float]
    h_res: Qty
    s_res: Qty
    warnings: list[Warning]

@final
class UmrprAlphaResult:
    alpha: float
    warnings: list[Warning]

@final
class UnifacActivityCoefficientsResult:
    ln_gamma: list[float]
    gamma: list[float]
    warnings: list[Warning]

@final
class UnifacPsrkActivityCoefficientsResult:
    ln_gamma: list[float]
    gamma: list[float]
    warnings: list[Warning]

@final
class UnifacUmrpruActivityCoefficientsResult:
    ln_gamma: list[float]
    gamma: list[float]
    warnings: list[Warning]

@final
class UniquacActivityCoefficientsResult:
    ln_gamma: list[float]
    gamma: list[float]
    warnings: list[Warning]

@final
class VanLaarAcidActivityCoefficientsResult:
    ln_gamma: list[float]
    gamma: list[float]
    warnings: list[Warning]

@final
class Vdw1fMixBinaryResult:
    a_mix: float
    b_mix: float
    warnings: list[Warning]

@final
class VhFlashResult:
    P: Qty
    T: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class ViscosityResult:
    mu: Qty
    warnings: list[Warning]

@final
class VsFlashResult:
    P: Qty
    T: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class VuFlashResult:
    P: Qty
    T: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class VuFlashSingleCompResult:
    T: Qty
    beta: float
    V: Qty
    phase: str
    warnings: list[Warning]

@final
class WaterPhaseResult:
    z_factor: float
    u: Qty
    h: Qty
    s: Qty
    cv: Qty
    cp: Qty
    g: Qty
    warnings: list[Warning]

@final
class WaxSolidFugacityResult:
    fugacity_coefficient: float
    warnings: list[Warning]

@final
class WilkeChangDiffusivityResult:
    d: Qty
    warnings: list[Warning]

@final
class WilkeViscosityResult:
    mu: Qty
    warnings: list[Warning]

@final
class WilsonActivityCoefficientsResult:
    ln_gamma: list[float]
    gamma: list[float]
    warnings: list[Warning]

@final
class ChokedFlowAreaResult:
    a: Qty
    warnings: list[Warning]

@final
class ControlValveCvResult:
    q: Qty
    warnings: list[Warning]

@final
class KFactorsResult:
    k_total: float
    f_t: float
    components: list[KComponent]
    warnings: list[Warning]

@final
class DarcyWeisbachResult:
    dp: Qty
    f: float
    re: float | None
    regime: str | None
    warnings: list[Warning]

@final
class ColebrookResult:
    f: float
    iterations: int
    converged: bool
    residual: float
    warnings: list[Warning]

@final
class HaalandResult:
    f: float
    warnings: list[Warning]

@final
class SwameeJainResult:
    f: float
    warnings: list[Warning]

@final
class OrificeFlowResult:
    q: Qty
    warnings: list[Warning]

@final
class PumpPowerResult:
    power: Qty
    warnings: list[Warning]

@final
class ReynoldsNumberResult:
    re: float
    regime: str
    warnings: list[Warning]

@final
class AbsorptionColumnResult:
    tray_temperature: list[Qty]
    tray_pressure: list[Qty]
    tray_gas_n: list[Qty]
    tray_liquid_n: list[Qty]
    gas_out_n: Qty
    gas_out_z: list[float]
    gas_out_p: Qty
    gas_out_t: Qty
    gas_out_h: Qty
    liquid_out_n: Qty
    liquid_out_z: list[float]
    liquid_out_p: Qty
    liquid_out_t: Qty
    liquid_out_h: Qty
    iterations: int
    temperature_residual: float
    mass_residual: float
    energy_residual: float
    warnings: list[Warning]

@final
class ComponentSplitterResult:
    overhead_n: Qty
    overhead_z: list[float]
    overhead_p: Qty
    overhead_t: Qty
    overhead_h: Qty
    bottoms_n: Qty
    bottoms_z: list[float]
    bottoms_p: Qty
    bottoms_t: Qty
    bottoms_h: Qty
    warnings: list[Warning]

@final
class CompressorResult:
    outlet_n: Qty
    outlet_z: list[float]
    outlet_p: Qty
    outlet_t: Qty
    outlet_h: Qty
    warnings: list[Warning]

@final
class CoolerResult:
    outlet_n: Qty
    outlet_z: list[float]
    outlet_p: Qty
    outlet_t: Qty
    outlet_h: Qty
    outlet_duty: Qty
    warnings: list[Warning]

@final
class DistillationColumnResult:
    tray_temperature: list[Qty]
    tray_pressure: list[Qty]
    tray_gas_n: list[Qty]
    tray_liquid_n: list[Qty]
    distillate_n: Qty
    distillate_z: list[float]
    distillate_p: Qty
    distillate_t: Qty
    distillate_h: Qty
    bottoms_n: Qty
    bottoms_z: list[float]
    bottoms_p: Qty
    bottoms_t: Qty
    bottoms_h: Qty
    gas_side_draw_n: list[Qty]
    liquid_side_draw_n: list[Qty]
    pumparound_n: list[Qty]
    condenser_duty: Qty
    reboiler_duty: Qty
    iterations: int
    temperature_residual: float
    mass_residual: float
    energy_residual: float
    warnings: list[Warning]

@final
class EjectorResult:
    outlet_n: Qty
    outlet_z: list[float]
    outlet_p: Qty
    outlet_t: Qty
    outlet_h: Qty
    warnings: list[Warning]

@final
class ExpanderResult:
    outlet_n: Qty
    outlet_z: list[float]
    outlet_p: Qty
    outlet_t: Qty
    outlet_h: Qty
    warnings: list[Warning]

@final
class FilterResult:
    outlet_n: Qty
    outlet_z: list[float]
    outlet_p: Qty
    outlet_t: Qty
    outlet_h: Qty
    applied_drop: Qty
    warnings: list[Warning]

@final
class FlareResult:
    product_n: Qty
    product_z: list[float]
    product_p: Qty
    product_t: Qty
    product_h: Qty
    heat_duty: Qty
    co2_emission: Qty
    warnings: list[Warning]

@final
class GasScrubberResult:
    vapour_n: Qty
    vapour_z: list[float]
    vapour_p: Qty
    vapour_t: Qty
    vapour_h: Qty
    liquid_n: Qty
    liquid_z: list[float]
    liquid_p: Qty
    liquid_t: Qty
    liquid_h: Qty
    warnings: list[Warning]

@final
class GibbsReactorResult:
    product_n: Qty
    product_z: list[float]
    product_p: Qty
    product_t: Qty
    product_h: Qty
    converged: bool
    iterations: float
    final_error: float
    lagrange_multipliers: list[float]
    element_balance_difference: list[float]
    gibbs_energy_history: list[float]
    warnings: list[Warning]

@final
class HeatExchangerResult:
    hot_out_n: Qty
    hot_out_z: list[float]
    hot_out_p: Qty
    hot_out_t: Qty
    hot_out_h: Qty
    cold_out_n: Qty
    cold_out_z: list[float]
    cold_out_p: Qty
    cold_out_t: Qty
    cold_out_h: Qty
    warnings: list[Warning]

@final
class HeaterResult:
    outlet_n: Qty
    outlet_z: list[float]
    outlet_p: Qty
    outlet_t: Qty
    outlet_h: Qty
    outlet_duty: Qty
    warnings: list[Warning]

@final
class ManifoldResult:
    products_n: list[Qty]
    products_z: list[list[float]]
    products_p: list[Qty]
    products_t: list[Qty]
    products_h: list[Qty]
    warnings: list[Warning]

@final
class MixerResult:
    product_n: Qty
    product_z: list[float]
    product_p: Qty
    product_t: Qty
    product_h: Qty
    warnings: list[Warning]

@final
class PackedColumnResult:
    tray_temperature: list[Qty]
    tray_pressure: list[Qty]
    tray_gas_n: list[Qty]
    tray_liquid_n: list[Qty]
    distillate_n: Qty
    distillate_z: list[float]
    distillate_p: Qty
    distillate_t: Qty
    distillate_h: Qty
    bottoms_n: Qty
    bottoms_z: list[float]
    bottoms_p: Qty
    bottoms_t: Qty
    bottoms_h: Qty
    gas_side_draw_n: list[Qty]
    liquid_side_draw_n: list[Qty]
    pumparound_n: list[Qty]
    condenser_duty: Qty
    reboiler_duty: Qty
    iterations: int
    temperature_residual: float
    mass_residual: float
    energy_residual: float
    warnings: list[Warning]

@final
class PipeResult:
    outlet_n: Qty
    outlet_z: list[float]
    outlet_p: Qty
    outlet_t: Qty
    outlet_h: Qty
    pressure_drop: Qty
    warnings: list[Warning]

@final
class PlugFlowReactorResult:
    product_n: Qty
    product_z: list[float]
    product_p: Qty
    product_t: Qty
    product_h: Qty
    conversion: float
    pressure_drop: Qty
    outlet_temperature: Qty
    heat_duty: Qty
    positions: list[float]
    temperature_profile: list[float]
    pressure_profile: list[float]
    conversion_profile: list[float]
    warnings: list[Warning]

@final
class PumpResult:
    outlet_n: Qty
    outlet_z: list[float]
    outlet_p: Qty
    outlet_t: Qty
    outlet_h: Qty
    warnings: list[Warning]

@final
class SeparatorResult:
    vapour_n: Qty
    vapour_z: list[float]
    vapour_p: Qty
    vapour_t: Qty
    vapour_h: Qty
    liquid_n: Qty
    liquid_z: list[float]
    liquid_p: Qty
    liquid_t: Qty
    liquid_h: Qty
    warnings: list[Warning]

@final
class ShortcutDistillationColumnResult:
    distillate_n: Qty
    distillate_z: list[float]
    distillate_p: Qty
    distillate_t: Qty
    distillate_h: Qty
    bottoms_n: Qty
    bottoms_z: list[float]
    bottoms_p: Qty
    bottoms_t: Qty
    bottoms_h: Qty
    minimum_stages: float
    minimum_reflux_ratio: float
    actual_stages: float
    actual_reflux_ratio: float
    feed_tray_number: int
    condenser_duty: Qty
    reboiler_duty: Qty
    relative_volatility: float
    warnings: list[Warning]

@final
class SplitterResult:
    products_n: list[Qty]
    products_z: list[list[float]]
    products_p: list[Qty]
    products_t: list[Qty]
    products_h: list[Qty]
    warnings: list[Warning]

@final
class StirredTankReactorResult:
    product_n: Qty
    product_z: list[float]
    product_p: Qty
    product_t: Qty
    product_h: Qty
    heat_duty: Qty
    warnings: list[Warning]

@final
class StrippingColumnResult:
    tray_temperature: list[Qty]
    tray_pressure: list[Qty]
    tray_gas_n: list[Qty]
    tray_liquid_n: list[Qty]
    overhead_gas_n: Qty
    overhead_gas_z: list[float]
    overhead_gas_p: Qty
    overhead_gas_t: Qty
    overhead_gas_h: Qty
    lean_liquid_n: Qty
    lean_liquid_z: list[float]
    lean_liquid_p: Qty
    lean_liquid_t: Qty
    lean_liquid_h: Qty
    iterations: int
    temperature_residual: float
    mass_residual: float
    energy_residual: float
    warnings: list[Warning]

@final
class TankResult:
    gas_n: Qty
    gas_z: list[float]
    gas_p: Qty
    gas_t: Qty
    gas_h: Qty
    liquid_n: Qty
    liquid_z: list[float]
    liquid_p: Qty
    liquid_t: Qty
    liquid_h: Qty
    warnings: list[Warning]

@final
class ThreePhaseSeparatorResult:
    vapour_n: Qty
    vapour_z: list[float]
    vapour_p: Qty
    vapour_t: Qty
    vapour_h: Qty
    light_liquid_n: Qty
    light_liquid_z: list[float]
    light_liquid_p: Qty
    light_liquid_t: Qty
    light_liquid_h: Qty
    heavy_liquid_n: Qty
    heavy_liquid_z: list[float]
    heavy_liquid_p: Qty
    heavy_liquid_t: Qty
    heavy_liquid_h: Qty
    warnings: list[Warning]

@final
class ThrottlingValveResult:
    outlet_n: Qty
    outlet_z: list[float]
    outlet_p: Qty
    outlet_t: Qty
    outlet_h: Qty
    warnings: list[Warning]

@final
class ChemicalEquilibriumResult:
    moles: list[Qty]
    iterations: int
    error: float
    converged: bool
    warnings: list[Warning]

@final
class EquilibriumConstantResult:
    ln_k: float
    k: float
    ln_k_derivative: Qty
    reaction_heat: Qty
    reference: str
    warnings: list[Warning]

@final
class KineticRateLawResult:
    rate_factor: float
    warnings: list[Warning]

@final
class KineticsResult:
    coefficient: list[float]
    phi_infinite: list[float]
    irreversible: list[float]
    warnings: list[Warning]

@final
class ReactiveHybridEosGeFlashResult:
    beta: list[float]
    x: list[list[float]]
    coupled_moles: list[Qty]
    aqueous_moles: list[Qty]
    passes: int
    chemical_deviation: float
    residual: float
    max_material_balance_residual: float
    max_log_fugacity_residual: float
    element_residual: float
    charge_residual: float
    warnings: list[Warning]

@final
class ReactivePhFlashResult:
    temperature: Qty
    converged: bool
    outer_iterations: int
    total_inner_iterations: int
    warnings: list[Warning]

@final
class ReactivePhaseEquilibriumResult:
    skipped: bool
    a_matrix: list[list[float]]
    b: list[Qty]
    chem_ref: list[Qty]
    moles: list[Qty]
    iterations: int
    error: float
    converged: bool
    refinements: int
    certified: bool
    max_reaction_log_residual: float
    net_charge_moles: Qty
    max_element_residual: Qty
    seed_applied: bool
    seed_moles: list[Qty]
    warnings: list[Warning]

@final
class ReactiveTpFlashResult:
    phase_count: int
    phase_type: list[str]
    phase_moles: list[list[Qty]]
    phase_fraction: list[float]
    converged: bool
    total_iterations: int
    equilibrium_total_moles: Qty
    gibbs_energy: float
    residual: float
    element_residual: float
    warnings: list[Warning]

@final
class ReferencePotentialsResult:
    potentials: list[Qty]
    independent: list[float]
    survivors: list[float]
    rank: int
    warnings: list[Warning]

@final
class Iso6976Result:
    molar_mass: Qty
    compression_factor: float
    relative_density: float
    density_ideal: Qty
    density_real: Qty
    superior_calorific_value: Qty
    inferior_calorific_value: Qty
    warnings: list[Warning]

@final
class ConductionPlaneWallResult:
    q: Qty
    warnings: list[Warning]

# --- calculations ---------------------------------------------------------
# All arguments and returns are SI magnitudes; unit handling happens once, in
# Python, before the call crosses this boundary. See crates/azoth-python.

def ammonia_phase(T: float, P: float) -> AmmoniaPhaseResult: ...
def antoine_vapor_pressure(
    A: float,
    B: float,
    C: float,
    D: float,
    E: float,
    form: str,
    Tc: float,
    Pc: float,
    T: float,
) -> AntoineVaporPressureResult: ...
def aqueous_viscosity(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    molar_mass: list[float],
    liqvisc: list[float],
    liqvisc_model: list[int],
    T: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> AqueousViscosityResult: ...
def argon_solid_phase(T: float, P: float) -> ArgonSolidPhaseResult: ...
def bubble_pressure(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    T: float,
    x: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> BubblePressureResult: ...
def bubble_temperature(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    P: float,
    x: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> BubbleTemperatureResult: ...
def bwrs_phase(
    a: list[float],
    rhoc: list[float],
    T: float,
    P: float,
    z: list[float],
) -> BwrsPhaseResult: ...
def capillary_dew_point(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    P: float,
    y: list[float],
    pore_radius: float,
    contact_angle: float,
    surface_tension: float,
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> CapillaryDewPointResult: ...
def chung_conductivity(
    Cv0: float,
    M: float,
    omega: float,
    Tc: float,
    Vc: float,
    dipole: float,
    kappa: float,
    T: float,
) -> ChungConductivityResult: ...
def chung_viscosity(
    omega: float,
    Tc: float,
    Vc: float,
    M: float,
    dipole: float,
    kappa: float,
    T: float,
    V: float,
) -> ChungViscosityResult: ...
def co2_phase(T: float, P: float) -> Co2PhaseResult: ...
def co2_water_diffusivity(T: float) -> Co2WaterDiffusivityResult: ...
def costald_molar_volume(
    omega: float,
    Tc: float,
    Vc: float,
    M: float,
    rho_normal: float,
    T: float,
) -> CostaldMolarVolumeResult: ...
def critical_point(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> CriticalPointResult: ...
def desmukh_mather_phase(
    components: list[str],
    T: float,
    P: float,
    x: list[float],
) -> DesmukhMatherPhaseResult: ...
def dew_pressure(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    T: float,
    y: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> DewPressureResult: ...
def dew_temperature(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    P: float,
    y: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> DewTemperatureResult: ...
def effective_diffusion(
    binary_diffusion: list[list[float]],
    x: list[float],
) -> EffectiveDiffusionResult: ...
def eos_cg_phase(components: list[str], T: float, P: float, z: list[float]) -> EosCgPhaseResult: ...
def freezing_point(
    components: list[str],
    z: list[float],
    solid: str,
    P: float,
) -> FreezingPointResult: ...
def fuller_schettler_giddings_diffusivity(
    MA: float,
    MB: float,
    VA: float,
    VB: float,
    T: float,
    P: float,
) -> FullerSchettlerGiddingsDiffusivityResult: ...
def furst_electrolyte_mod2004_phase(
    components: list[str],
    T: float,
    P: float,
    x: list[float],
    compressed_phase: str,
) -> FurstElectrolyteMod2004PhaseResult: ...
def furst_electrolyte_phase(
    components: list[str],
    T: float,
    P: float,
    x: list[float],
    compressed_phase: str,
) -> FurstElectrolytePhaseResult: ...
def ge_flash(
    components: list[str],
    liquid_model: str,
    T: float,
    P: float,
    z: list[float],
    cubic: str,
) -> GeFlashResult: ...
def ge_nrtl_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    alpha: list[float],
    dij: list[float],
    antoine_type: list[str],
    antoine_coefficients: list[float],
    antoine_tc: list[float],
    antoine_pc: list[float],
    T: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    cubic_alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> GeNrtlFlashResult: ...
def ge_nrtl_phase(
    alpha: list[float],
    dij: list[float],
    antoine_type: list[str],
    antoine_coefficients: list[float],
    antoine_tc: list[float],
    antoine_pc: list[float],
    T: float,
    P: float,
    x: list[float],
) -> GeNrtlPhaseResult: ...
def ge_unifac_phase(
    groups: list[float],
    group_r: list[float],
    group_q: list[float],
    aij: list[float],
    antoine_type: list[str],
    antoine_coefficients: list[float],
    antoine_tc: list[float],
    antoine_pc: list[float],
    T: float,
    P: float,
    x: list[float],
) -> GeUnifacPhaseResult: ...
def ge_uniquac_phase(
    r: list[float],
    q: list[float],
    antoine_type: list[str],
    antoine_coefficients: list[float],
    antoine_tc: list[float],
    antoine_pc: list[float],
    T: float,
    P: float,
    x: list[float],
    aij: list[list[float]],
) -> GeUniquacPhaseResult: ...
def ge_van_laar_acid_phase(
    acid_index: list[int],
    antoine_type: list[str],
    antoine_coefficients: list[float],
    antoine_tc: list[float],
    antoine_pc: list[float],
    T: float,
    P: float,
    x: list[float],
) -> GeVanLaarAcidPhaseResult: ...
def ge_wilson_phase(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    molar_mass: list[float],
    antoine_type: list[str],
    antoine_coefficients: list[float],
    antoine_tc: list[float],
    antoine_pc: list[float],
    T: float,
    P: float,
    x: list[float],
    eos: str = "pr",
    cubic_alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> GeWilsonPhaseResult: ...
def gerg2008_phase(
    components: list[str],
    T: float,
    P: float,
    z: list[float],
) -> Gerg2008PhaseResult: ...
def hayduk_minhas_diffusivity(
    form: str,
    VA: float,
    T: float,
    eta: float,
) -> HaydukMinhasDiffusivityResult: ...
def heat_of_vaporization(
    c0: float,
    c1: float,
    c2: float,
    c3: float,
    Tc: float,
    T: float,
) -> HeatOfVaporizationResult: ...
def helium_phase(T: float, P: float) -> HeliumPhaseResult: ...
def hybrid_eos_ge_flash(
    components: list[str],
    cubic: str,
    T: float,
    P: float,
    moles: list[float],
) -> HybridEosGeFlashResult: ...
def hydrate_equilibrium_line(
    components: list[str],
    P_min: float,
    P_max: float,
    z: list[float],
    eos: str,
    hydrate_model: str | None = None,
) -> HydrateEquilibriumLineResult: ...
def hydrate_formation_pressure(
    components: list[str],
    T: float,
    z: list[float],
    eos: str,
    hydrate_model: str | None = None,
) -> HydrateFormationPressureResult: ...
def hydrate_formation_temperature(
    components: list[str],
    P: float,
    z: list[float],
    eos: str,
    hydrate_model: str | None = None,
) -> HydrateFormationTemperatureResult: ...
def hydrate_fraction(
    components: list[str],
    T: float,
    P: float,
    z: list[float],
    eos: str,
    hydrate_model: str | None = None,
) -> HydrateFractionResult: ...
def hydrate_inhibitor_concentration(
    components: list[str],
    moles: list[float],
    inhibitor: str,
    T_target: float,
    P: float,
    eos: str,
    hydrate_model: str | None = None,
) -> HydrateInhibitorConcentrationResult: ...
def hydrate_inhibitor_wt(
    components: list[str],
    moles: list[float],
    inhibitor: str,
    wt_target: float,
    T: float,
    P: float,
    eos: str,
) -> HydrateInhibitorWtResult: ...
def hydrogen_phase(
    T: float,
    P: float,
    compressed_phase: str,
    hydrogen_type: str = "normal",
) -> HydrogenPhaseResult: ...
def iapws_henry_law(gas: str, T: float) -> IapwsHenryLawResult: ...
def ideal_gas_cp(
    cp_a: float,
    cp_b: float,
    cp_c: float,
    cp_d: float,
    cp_e: float,
    T: float,
) -> IdealGasCpResult: ...
def kent_eisenberg_phase(
    components: list[str],
    T: float,
    P: float,
    x: list[float],
) -> KentEisenbergPhaseResult: ...
def liquid_heat_capacity(
    c0: float,
    c1: float,
    c2: float,
    c3: float,
    c4: float,
    T: float,
) -> LiquidHeatCapacityResult: ...
def mason_saxena_conductivity(
    Cv0: list[float],
    M: list[float],
    omega: list[float],
    Tc: list[float],
    Vc: list[float],
    dipole: list[float],
    kappa: list[float],
    T: float,
    z: list[float],
) -> MasonSaxenaConductivityResult: ...
def matcop5_prumr_alpha(
    omega: float,
    mc1: float,
    mc2: float,
    mc3: float,
    mc4: float,
    mc5: float,
    Tr: float,
) -> Matcop5PrumrAlphaResult: ...
def matcop_alpha(mc1: float, mc2: float, mc3: float, Tr: float) -> MatcopAlphaResult: ...
def matcop_pr_alpha(
    omega: float,
    mc1: float,
    mc2: float,
    mc3: float,
    Tr: float,
) -> MatcopPrAlphaResult: ...
def matcop_prumr_alpha(
    omega: float,
    mc1: float,
    mc2: float,
    mc3: float,
    Tr: float,
) -> MatcopPrumrAlphaResult: ...
def matcop_prumr_new_alpha(
    omega: float,
    mc1: float,
    mc2: float,
    mc3: float,
    mc4: float,
    mc5: float,
    Tr: float,
) -> MatcopPrumrNewAlphaResult: ...
def molar_enthalpy_entropy(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    T: float,
    P: float,
    z: list[float],
    compressibility: float,
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> MolarEnthalpyEntropyResult: ...
def mollerup_alpha(p1: float, p2: float, p3: float, Tr: float) -> MollerupAlphaResult: ...
def nitric_sulfuric_acid_vapor_pressure(T: float) -> NitricSulfuricAcidVaporPressureResult: ...
def nrtl_activity_coefficients(
    alpha: list[float],
    dij: list[float],
    T: float,
    x: list[float],
) -> NrtlActivityCoefficientsResult: ...
def parachor_mixture_surface_tension(
    parachors: list[float],
    rho_gas: float,
    M_gas: float,
    x_gas: list[float],
    rho_liquid: float,
    M_liquid: float,
    x_liquid: list[float],
) -> ParachorMixtureSurfaceTensionResult: ...
def parachor_surface_tension(
    parachor: float,
    rho_l: float,
    rho_v: float,
    M: float,
) -> ParachorSurfaceTensionResult: ...
def parahydrogen_solid_phase(T: float, P: float) -> ParahydrogenSolidPhaseResult: ...
def pcsaft_rahmat_phase(
    components: list[str],
    T: float,
    P: float,
    z: list[float],
    compressed_phase: str,
) -> PcsaftRahmatPhaseResult: ...
def ph_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    P: float,
    H: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PhFlashResult: ...
def pitzer_phase(
    components: list[str],
    T: float,
    P: float,
    x: list[float],
) -> PitzerPhaseResult: ...
def pr78_kappa(omega: float) -> Pr78KappaResult: ...
def pr_alpha_ab(kappa: float, Tr: float, Pr: float) -> PrAlphaAbResult: ...
def pr_cpa_phase(
    components: list[str],
    T: float,
    P: float,
    z: list[float],
    compressed_phase: str,
) -> PrCpaPhaseResult: ...
def pr_danesh_alpha(omega: float, Tr: float) -> PrDaneshAlphaResult: ...
def pr_delft1998_alpha(omega: float, Tr: float) -> PrDelft1998AlphaResult: ...
def pr_departure(
    a_reduced: float,
    b_reduced: float,
    z: float,
    kappa: float,
    Tr: float,
) -> PrDepartureResult: ...
def pr_gassem2001_alpha(omega: float, Tr: float) -> PrGassem2001AlphaResult: ...
def pr_kappa(omega: float) -> PrKappaResult: ...
def pr_lee_kesler_alpha(omega: float, Tr: float) -> PrLeeKeslerAlphaResult: ...
def pr_mass_density(M: float, v: float) -> PrMassDensityResult: ...
def pr_molar_volume(z: float, T: float, P: float) -> PrMolarVolumeResult: ...
def pr_peneloux_shift(
    omega: float,
    Tc: float,
    Pc: float,
    z_ra: float | None = None,
) -> PrPenelouxShiftResult: ...
def pr_z_factor(a_reduced: float, b_reduced: float) -> PrZFactorResult: ...
def prsv_kappa(omega: float, Tr: float, kappa1: float) -> PrsvKappaResult: ...
def ps_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    P: float,
    S: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PsFlashResult: ...
def pt_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    T: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PtFlashResult: ...
def pt_phase_envelope(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PtPhaseEnvelopeResult: ...
def pu_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    P: float,
    U: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PuFlashResult: ...
def pure_saturation(Tc: float, Pc: float, omega: float, T: float) -> PureSaturationResult: ...
def pv_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    P: float,
    V: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PvFlashResult: ...
def pv_reflux_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    P: float,
    reflux: float,
    phase: str,
    temperature: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PvRefluxFlashResult: ...
def pvf_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    P: float,
    beta: float,
    temperature: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PvfFlashResult: ...
def rachford_rice(z: list[float], K: list[float]) -> RachfordRiceResult: ...
def rachford_rice_binary(z1: float, K1: float, K2: float) -> RachfordRiceBinaryResult: ...
def rackett_molar_volume(
    omega: float,
    Tc: float,
    Pc: float,
    T: float,
) -> RackettMolarVolumeResult: ...
def rk_alpha_ab(Tr: float, Pr: float) -> RkAlphaAbResult: ...
def rk_departure(a_reduced: float, b_reduced: float, z: float) -> RkDepartureResult: ...
def saft_vr_mie_phase(
    components: list[str],
    T: float,
    P: float,
    z: list[float],
    compressed_phase: str,
) -> SaftVrMiePhaseResult: ...
def salt_precipitation(
    components: list[str],
    z: list[float],
    salt: str,
    T: float,
    P: float,
) -> SaltPrecipitationResult: ...
def scale_saturation_ratio(
    salt: str,
    x1: float,
    x2: float,
    x_water: float,
    gamma1: float,
    gamma2: float,
    water_activity: float,
    T: float,
    P: float,
    h3o_molality: float | None = None,
) -> ScaleSaturationRatioResult: ...
def schwartzentruber_alpha(
    omega: float,
    p1: float,
    p2: float,
    p3: float,
    Tr: float,
) -> SchwartzentruberAlphaResult: ...
def siddiqi_lucas_diffusivity(
    form: str,
    VA: float,
    VB: float,
    T: float,
    eta: float,
) -> SiddiqiLucasDiffusivityResult: ...
def solid_fugacity(
    heat_of_fusion: float,
    triple_point_temperature: float,
    delta_cp_sl: float,
    delta_solid_volume: float,
    tc: float,
    pc: float,
    omega: float,
    T: float,
    P: float,
    eos: str | None = None,
) -> SolidFugacityResult: ...
def soreide_whitson_alpha(salinity: float, Tr: float) -> SoreideWhitsonAlphaResult: ...
def soreide_whitson_phase(
    components: list[str],
    T: float,
    P: float,
    x: list[float],
    salinity: float,
    compressed_phase: str,
) -> SoreideWhitsonPhaseResult: ...
def srk_alpha_ab(kappa: float, Tr: float, Pr: float) -> SrkAlphaAbResult: ...
def srk_cpa_phase(
    components: list[str],
    T: float,
    P: float,
    z: list[float],
    compressed_phase: str,
) -> SrkCpaPhaseResult: ...
def srk_departure(
    a_reduced: float,
    b_reduced: float,
    z: float,
    kappa: float,
    Tr: float,
) -> SrkDepartureResult: ...
def srk_kappa(omega: float) -> SrkKappaResult: ...
def srk_peneloux_shift(omega: float, Tc: float, Pc: float) -> SrkPenelouxShiftResult: ...
def srk_z_factor(a_reduced: float, b_reduced: float) -> SrkZFactorResult: ...
def stability_test(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    T: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> StabilityTestResult: ...
def tbp_fraction_properties(molar_mass: float, density: float) -> TbpFractionPropertiesResult: ...
def th_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    T: float,
    H: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> ThFlashResult: ...
def thermal_conductivity(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    molar_mass: list[float],
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    T: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> ThermalConductivityResult: ...
def tp_flash_saft(
    components: list[str],
    T: float,
    P: float,
    z: list[float],
) -> TpFlashSaftResult: ...
def tp_multiflash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    T: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> TpMultiflashResult: ...
def tp_multiflash_wax(
    components: list[str],
    T: float,
    P: float,
    z: list[float],
    eos: str | None = None,
) -> TpMultiflashWaxResult: ...
def tp_solid_flash(
    components: list[str],
    solid: str,
    T: float,
    P: float,
    z: list[float],
    eos: str | None = None,
) -> TpSolidFlashResult: ...
def ts_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    T: float,
    S: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> TsFlashResult: ...
def tu_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    T: float,
    U: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> TuFlashResult: ...
def tv_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    T: float,
    V: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> TvFlashResult: ...
def tv_fraction_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    T: float,
    fraction: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> TvFractionFlashResult: ...
def twu_kappa(omega: float) -> TwuKappaResult: ...
def twucoon_alpha(omega: float, Tr: float) -> TwucoonAlphaResult: ...
def twucoon_param_alpha(a: float, b: float, c: float, Tr: float) -> TwucoonParamAlphaResult: ...
def twucoon_statoil_alpha(a: float, b: float, c: float, Tr: float) -> TwucoonStatoilAlphaResult: ...
def tyn_calus_diffusivity(
    VA: float,
    VB: float,
    T: float,
    eta: float,
) -> TynCalusDiffusivityResult: ...
def umr_cpa_phase(
    components: list[str],
    T: float,
    P: float,
    z: list[float],
    compressed_phase: str,
) -> UmrCpaPhaseResult: ...
def umrpr_alpha(omega: float, Tr: float) -> UmrprAlphaResult: ...
def unifac_activity_coefficients(
    groups: list[float],
    group_r: list[float],
    group_q: list[float],
    aij: list[float],
    T: float,
    x: list[float],
) -> UnifacActivityCoefficientsResult: ...
def unifac_psrk_activity_coefficients(
    groups: list[float],
    group_r: list[float],
    group_q: list[float],
    aij: list[float],
    bij: list[float],
    cij: list[float],
    T: float,
    x: list[float],
) -> UnifacPsrkActivityCoefficientsResult: ...
def unifac_umrpru_activity_coefficients(
    groups: list[float],
    group_r: list[float],
    group_q: list[float],
    aij: list[float],
    bij: list[float],
    cij: list[float],
    T: float,
    x: list[float],
) -> UnifacUmrpruActivityCoefficientsResult: ...
def uniquac_activity_coefficients(
    r: list[float],
    q: list[float],
    T: float,
    x: list[float],
    aij: list[list[float]],
) -> UniquacActivityCoefficientsResult: ...
def van_laar_acid_activity_coefficients(
    acid_index: list[int],
    T: float,
    x: list[float],
) -> VanLaarAcidActivityCoefficientsResult: ...
def vdw1f_mix_binary(
    z1: float,
    a1: float,
    a2: float,
    b1: float,
    b2: float,
    k12: float,
) -> Vdw1fMixBinaryResult: ...
def vh_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    V: float,
    H: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> VhFlashResult: ...
def viscosity(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    molar_mass: list[float],
    T: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> ViscosityResult: ...
def vs_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    V: float,
    S: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> VsFlashResult: ...
def vu_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    V: float,
    U: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> VuFlashResult: ...
def vu_flash_single_comp(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    P: float,
    V: float,
    U: float,
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> VuFlashSingleCompResult: ...
def water_phase(T: float, P: float) -> WaterPhaseResult: ...
def wax_solid_fugacity(
    molar_mass: float,
    tc: float,
    pc: float,
    omega: float,
    heat_of_fusion: float,
    triple_point_temperature: float,
    T: float,
    P: float,
    eos: str | None = None,
) -> WaxSolidFugacityResult: ...
def wilke_chang_diffusivity(
    phi: float,
    M: float,
    T: float,
    eta: float,
    VA: float,
) -> WilkeChangDiffusivityResult: ...
def wilke_viscosity(
    Tc: list[float],
    Vc: list[float],
    M: list[float],
    omega: list[float],
    dipole: list[float],
    kappa: list[float],
    T: float,
    V: float,
    z: list[float],
) -> WilkeViscosityResult: ...
def wilson_activity_coefficients(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    association: AssociationSpec,
    molar_mass: list[float],
    T: float,
    x: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> WilsonActivityCoefficientsResult: ...
def choked_flow_area(m_dot: float, P0: float, rho0: float, k: float) -> ChokedFlowAreaResult: ...
def control_valve_cv(Cv: float, dP: float, SG: float) -> ControlValveCvResult: ...
def crane_k_factors(fittings: list[str], f_t: float) -> KFactorsResult: ...
def darcy_weisbach(
    f: float,
    L: float,
    D: float,
    rho: float,
    v: float,
    mu: float | None = None,
) -> DarcyWeisbachResult: ...
def friction_factor_colebrook(re: float, relative_roughness: float) -> ColebrookResult: ...
def friction_factor_haaland(re: float, relative_roughness: float) -> HaalandResult: ...
def friction_factor_swamee_jain(re: float, relative_roughness: float) -> SwameeJainResult: ...
def orifice_flow(d: float, dP: float, rho: float, Cd: float) -> OrificeFlowResult: ...
def pump_power(rho: float, q: float, H: float, eta: float) -> PumpPowerResult: ...
def reynolds_number(rho: float, v: float, D: float, mu: float) -> ReynoldsNumberResult: ...
def absorption_column(
    gas_components: list[str],
    solvent_components: list[str],
    gas_n: float,
    gas_z: list[float],
    gas_p: float,
    gas_t: float,
    solvent_n: float,
    solvent_z: list[float],
    solvent_p: float,
    solvent_t: float,
    number_of_stages: float,
    top_pressure: float,
    bottom_pressure: float,
    temperature_tolerance: float,
    max_iterations: float,
    tray_temperatures: list[float] | None = None,
    murphree_efficiency: float | None = None,
    component_murphree_efficiency: list[float] | None = None,
    max_allowable_gas_load_factor: float | None = None,
    solver_type: str | None = None,
) -> AbsorptionColumnResult: ...
def component_splitter(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    split_factors: list[float],
) -> ComponentSplitterResult: ...
def compressor(
    components: list[str],
    inlet_n: float,
    inlet_z: list[float],
    inlet_p: float,
    inlet_t: float,
    outlet_pressure: float,
    isentropic_efficiency: float,
) -> CompressorResult: ...
def cooler(
    components: list[str],
    inlet_n: float,
    inlet_z: list[float],
    inlet_p: float,
    inlet_t: float,
    outlet_temperature: float | None = None,
    duty: float | None = None,
    pressure_drop: float | None = None,
) -> CoolerResult: ...
def distillation_column(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    number_of_stages: float,
    feed_stage: float,
    has_reboiler: bool,
    has_condenser: bool,
    top_pressure: float,
    bottom_pressure: float,
    temperature_tolerance: float,
    max_iterations: float,
    reboiler_temperature: float | None = None,
    condenser_temperature: float | None = None,
    murphree_efficiency: float | None = None,
    solver_type: str | None = None,
    top_specification_type: str | None = None,
    top_specification_target: float | None = None,
    top_specification_component: str | None = None,
    bottom_specification_type: str | None = None,
    bottom_specification_target: float | None = None,
    bottom_specification_component: str | None = None,
    reactive: bool | None = None,
    reactive_start_tray: float | None = None,
    reactive_end_tray: float | None = None,
    gas_side_draw_fractions: list[float] | None = None,
    liquid_side_draw_fractions: list[float] | None = None,
    pumparound_fractions: list[float] | None = None,
) -> DistillationColumnResult: ...
def ejector(
    motive_components: list[str],
    suction_components: list[str],
    motive_n: float,
    motive_z: list[float],
    motive_p: float,
    motive_t: float,
    suction_n: float,
    suction_z: list[float],
    suction_p: float,
    suction_t: float,
    discharge_pressure: float,
    motive_nozzle_efficiency: float,
    suction_nozzle_efficiency: float,
    mixing_efficiency: float,
    diffuser_efficiency: float,
) -> EjectorResult: ...
def expander(
    components: list[str],
    inlet_n: float,
    inlet_z: list[float],
    inlet_p: float,
    inlet_t: float,
    outlet_pressure: float,
    isentropic_efficiency: float,
) -> ExpanderResult: ...
def filter(
    components: list[str],
    inlet_n: float,
    inlet_z: list[float],
    inlet_p: float,
    inlet_t: float,
    pressure_drop: float,
) -> FilterResult: ...
def flare(
    components: list[str],
    inlet_n: float,
    inlet_z: list[float],
    inlet_p: float,
    inlet_t: float,
) -> FlareResult: ...
def gas_scrubber(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    pressure_drop: float,
    gas_in_liquid: float,
    heat_input: float | None = None,
) -> GasScrubberResult: ...
def gibbs_reactor(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    energy_mode: str,
    damping_composition: float,
    max_iterations: float,
    convergence_tolerance: float,
    min_iterations: float,
) -> GibbsReactorResult: ...
def heat_exchanger(
    hot_components: list[str],
    cold_components: list[str],
    hot_in_n: float,
    hot_in_z: list[float],
    hot_in_p: float,
    hot_in_t: float,
    cold_in_n: float,
    cold_in_z: list[float],
    cold_in_p: float,
    cold_in_t: float,
    flow_arrangement: str,
    ua: float | None = None,
    hot_outlet_temperature: float | None = None,
    cold_outlet_temperature: float | None = None,
) -> HeatExchangerResult: ...
def heater(
    components: list[str],
    inlet_n: float,
    inlet_z: list[float],
    inlet_p: float,
    inlet_t: float,
    outlet_temperature: float | None = None,
    duty: float | None = None,
    pressure_drop: float | None = None,
) -> HeaterResult: ...
def manifold(
    components: list[str],
    feed_n: list[float],
    feed_z: list[list[float]],
    feed_p: list[float],
    feed_t: list[float],
    split_factors: list[float],
) -> ManifoldResult: ...
def mixer(
    components: list[str],
    feed_n: list[float],
    feed_z: list[list[float]],
    feed_p: list[float],
    feed_t: list[float],
    outlet_pressure: float | None = None,
) -> MixerResult: ...
def packed_column(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    packed_height: float,
    feed_stage: float,
    has_reboiler: bool,
    has_condenser: bool,
    top_pressure: float,
    bottom_pressure: float,
    temperature_tolerance: float,
    max_iterations: float,
    reboiler_temperature: float | None = None,
    condenser_temperature: float | None = None,
    packing_type: str | None = None,
    structured_packing: bool | None = None,
    design_flood_fraction: float | None = None,
    packing_hydraulic_capacity_factor: float | None = None,
    column_diameter: float | None = None,
    murphree_efficiency: float | None = None,
    solver_type: str | None = None,
    top_specification_type: str | None = None,
    top_specification_target: float | None = None,
    top_specification_component: str | None = None,
    bottom_specification_type: str | None = None,
    bottom_specification_target: float | None = None,
    bottom_specification_component: str | None = None,
) -> PackedColumnResult: ...
def pipe(
    components: list[str],
    inlet_n: float,
    inlet_z: list[float],
    inlet_p: float,
    inlet_t: float,
    length: float,
    diameter: float,
    roughness: float,
) -> PipeResult: ...
def plug_flow_reactor(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    length: float,
    diameter: float,
    number_of_tubes: float,
    energy_mode: str,
    coolant_temperature: float,
    overall_heat_transfer_coefficient: float,
    number_of_steps: float,
    integration_method: str,
    property_update_frequency: float,
    thermodynamic_coupling: str,
    reaction: str,
    reaction_orders: list[float],
    rate_type: str,
    pre_exponential_factor: float,
    activation_energy: float,
    temperature_exponent: float,
    heat_of_reaction: float,
    catalyst_bulk_density: float | None = None,
    catalyst_activity_factor: float | None = None,
    catalyst_particle_diameter: float | None = None,
    catalyst_void_fraction: float | None = None,
    catalyst_molecular_diffusivity: float | None = None,
    catalyst_effectiveness_enabled: bool | None = None,
    key_component: str | None = None,
) -> PlugFlowReactorResult: ...
def pump(
    components: list[str],
    inlet_n: float,
    inlet_z: list[float],
    inlet_p: float,
    inlet_t: float,
    outlet_pressure: float,
    isentropic_efficiency: float,
) -> PumpResult: ...
def separator(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    pressure_drop: float,
    gas_in_liquid: float,
    heat_input: float | None = None,
) -> SeparatorResult: ...
def shortcut_distillation_column(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    light_key: str,
    heavy_key: str,
    light_key_recovery_distillate: float,
    heavy_key_recovery_bottoms: float,
    reflux_ratio_multiplier: float,
    condenser_pressure: float | None = None,
    reboiler_pressure: float | None = None,
) -> ShortcutDistillationColumnResult: ...
def splitter(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    split_factors: list[float],
) -> SplitterResult: ...
def stirred_tank_reactor(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    reaction: str,
    limiting_reactant: str,
    conversion: float,
    isothermal: bool,
    reactor_temperature: float | None = None,
    reactor_pressure: float | None = None,
    pressure_drop: float | None = None,
) -> StirredTankReactorResult: ...
def stripping_column(
    stripping_gas_components: list[str],
    rich_liquid_components: list[str],
    stripping_gas_n: float,
    stripping_gas_z: list[float],
    stripping_gas_p: float,
    stripping_gas_t: float,
    rich_liquid_n: float,
    rich_liquid_z: list[float],
    rich_liquid_p: float,
    rich_liquid_t: float,
    number_of_stages: float,
    top_pressure: float,
    bottom_pressure: float,
    temperature_tolerance: float,
    max_iterations: float,
    tray_temperatures: list[float] | None = None,
    murphree_efficiency: float | None = None,
    component_murphree_efficiency: list[float] | None = None,
    max_allowable_gas_load_factor: float | None = None,
    solver_type: str | None = None,
) -> StrippingColumnResult: ...
def tank(
    components: list[str],
    feed_n: list[float],
    feed_z: list[list[float]],
    feed_p: list[float],
    feed_t: list[float],
) -> TankResult: ...
def three_phase_separator(
    components: list[str],
    feed_n: float,
    feed_z: list[float],
    feed_p: float,
    feed_t: float,
    pressure_drop: float,
    gas_in_aqueous: float,
    gas_in_oil: float,
    oil_in_aqueous: float,
    oil_in_gas: float,
    aqueous_in_gas: float,
    aqueous_in_oil: float,
    heat_input: float | None = None,
) -> ThreePhaseSeparatorResult: ...
def throttling_valve(
    components: list[str],
    inlet_n: float,
    inlet_z: list[float],
    inlet_p: float,
    inlet_t: float,
    outlet_pressure: float,
) -> ThrottlingValveResult: ...
def chemical_equilibrium(
    a_matrix: list[list[float]],
    b: list[float],
    whole_system: bool,
    moles: list[float],
    chem_ref: list[float],
    log_activity: list[float],
    T: float,
    max_iterations: float,
    tolerance: float,
    concentration_basis: str,
    solvent_weight: float,
    solvent_mask: list[float],
    phase_moles: float,
) -> ChemicalEquilibriumResult: ...
def equilibrium_constant(reaction: str, source: str, T: float) -> EquilibriumConstantResult: ...
def kinetic_rate_law(
    law: str,
    T: float,
    reference_rate: float,
    activation_energy: float,
    reference_temperature: float,
) -> KineticRateLawResult: ...
def kinetics(
    components: list[str],
    reaction_components: list[str],
    reaction_lengths: list[float],
    reaction_coefficients: list[float],
    rate_factors: list[float],
    equilibrium_constants: list[float],
    fractions: list[float],
    molar_masses: list[float],
    density: float,
    inter_fractions: list[float],
    inter_density: float,
    diffusion: list[float],
) -> KineticsResult: ...
def reactive_hybrid_eos_ge_flash(
    components: list[str],
    cubic: str,
    T: float,
    P: float,
    moles: list[float],
) -> ReactiveHybridEosGeFlashResult: ...
def reactive_ph_flash(
    components: list[str],
    T: float,
    P: float,
    moles: list[float],
    enthalpy: float,
    max_phases: float,
    cubic: str | None = None,
) -> ReactivePhFlashResult: ...
def reactive_phase_equilibrium(
    components: list[str],
    source: str,
    phase: str,
    moles: list[float],
    phase_charge: float,
    phase_moles: float,
    whole_system: bool,
    log_activity: list[float],
    T: float,
    max_iterations: float,
    tolerance: float,
    concentration_basis: str,
    seed: str,
) -> ReactivePhaseEquilibriumResult: ...
def reactive_tp_flash(
    components: list[str],
    T: float,
    P: float,
    moles: list[float],
    max_phases: float,
    cubic: str | None = None,
) -> ReactiveTpFlashResult: ...
def reference_potentials(
    components: list[str],
    source: str,
    T: float,
) -> ReferencePotentialsResult: ...
def iso6976(
    components: list[str],
    z: list[float],
    volumetric_reference_temperature: float,
    energy_reference_temperature: float,
) -> Iso6976Result: ...
def conduction_plane_wall(k: float, A: float, dT: float, L: float) -> ConductionPlaneWallResult: ...

# --- introspection --------------------------------------------------------

def batch_run(calc_id: str, inputs: dict[str, list[float]]) -> BatchResult: ...
def data_files() -> list[DataFile]: ...
def fittings_rows() -> list[FittingRow]: ...
def fluid_rows(name: str) -> list[FluidRow]: ...
def component_rows() -> list[ComponentRow]: ...
def kij_rows() -> list[KijRow]: ...
def overlay(components: list[ComponentArguments], kij: list[tuple[str, str, float]]) -> Overlay: ...
def card_overlay(text: str) -> Overlay: ...
def card_coefficients(text: str) -> list[tuple[str, str, str, int, int, list[float]]]: ...
def overlay_entry_row(name: str, overlay: Overlay) -> ComponentRow: ...
def overlay_component_rows(overlay: Overlay) -> list[ComponentRow]: ...
def overlay_kij_rows(overlay: Overlay) -> list[tuple[str, str, float]]: ...
def overlay_cpa_kij_rows(overlay: Overlay, family: str) -> list[tuple[str, str, float]]: ...
def warning_codes() -> list[str]: ...
def unit_names() -> list[str]: ...
def solver_kinds() -> list[str]: ...
def model_ids() -> list[str]: ...
def model_schemes(model_id: str) -> list[str]: ...
def model_kind(model_id: str) -> str: ...
def result_fields(calc_id: str) -> list[str]: ...
def calc_ids() -> list[str]: ...
def version() -> str: ...
def splitter_stream(feed: Stream, fractions: list[float]) -> list[Stream]: ...
def mixer_stream(inlets: list[Stream], outlet_pressure: float | None = ...) -> Stream: ...
def separator_stream(feed: Stream, pressure_drop: float, gas_in_liquid: float = ..., heat_input: float | None = ...) -> tuple[Stream, Stream]: ...
def throttling_valve_stream(feed: Stream, outlet_pressure: float) -> Stream: ...
def heat_exchanger_stream(hot: Stream, cold: Stream, ua: float | None = ..., flow_arrangement: str = ..., hot_outlet_temperature: float | None = ..., cold_outlet_temperature: float | None = ...) -> tuple[Stream, Stream]: ...
def pump_stream(feed: Stream, outlet_pressure: float, efficiency: float) -> Stream: ...
def validate_flowsheet(flowsheet: str, palette_dir: str) -> list[str]: ...
def run_flowsheet(flowsheet: str, feeds: dict[str, Stream] | None = ..., palette_dir: str = ..., execution_order: str = ...) -> str: ...
def catalogue(palette_dir: str | None = ..., with_tools: bool = ...) -> str: ...

# --- exceptions -----------------------------------------------------------
# Re-exported from azoth.core.errors, so both backends raise the same class
# objects rather than two lookalike hierarchies.

class AzothError(Exception): ...
class InvalidInputError(AzothError, ValueError): ...
class OutOfRangeError(AzothError, ValueError): ...
class PropertyUnavailableError(AzothError, LookupError): ...
class SolverNotConvergedError(AzothError, RuntimeError): ...
class UnitMismatchError(AzothError, TypeError): ...
class UnknownFittingError(AzothError, LookupError): ...
