"""Type stub for the compiled extension.

Generated by `tools/gen_stub.py` from the result dataclasses and the specs. Do
not edit by hand: the result classes below are what `azoth.core.result` says, the
signatures are what the specs declare, and both are already asserted equal to the
Rust side by tests.

Nothing here is part of the public API. `azoth.hydraulics` is, and it returns the
result dataclasses in `azoth.core.result` rather than the transport types below -
see `azoth._rust_bridge`.
"""

from typing import final

# --- transport types ------------------------------------------------------
# The values that cross the boundary and are not results. Hand-written here
# because a `cdylib` has nothing to introspect; held to the Rust structs by
# `test_the_stub_matches_the_rust_transport_types`.

@final
class DataFile:
    name: str
    path: str
    text: str

@final
class FittingRow:
    id: str
    family: str
    name: str
    n_ld: float
    f_t_basis: str
    citation: str
    verify_status: str

@final
class FluidRow:
    fluid: str
    temperature_c: float
    density_kg_m3: float
    dynamic_viscosity_pa_s: float
    citation: str
    verify_status: str

@final
class ComponentRow:
    """One row of the component databank, as the Rust core parsed it."""

    name: str
    tc_k: float
    pc_pa: float
    acentric_factor: float
    cp_a: float | None
    cp_b: float | None
    cp_c: float | None
    cp_d: float | None
    cp_e: float | None

@final
class KijRow:
    """One row of the interaction table, as the Rust core parsed it."""

    component_a: str
    component_b: str
    kij_pr: float

@final
class Overlay:
    """A keycard's sections, as the extension reads them. Built either entry by entry from the values `azoth.keycard` resolved to or by reading a card's text with `card_overlay`, and opaque: what it resolves to is read through `overlay_entry_row` and its siblings."""


@final
class Qty:
    """A physical quantity: always SI magnitude, plus a canonical unit label."""

    magnitude_si: float
    unit: str
    def __init__(self, magnitude_si: float, unit: str) -> None: ...

@final
class Warning:
    """A warning, transported. `code` is the SCREAMING_SNAKE_CASE string."""

    code: str
    message: str
    field: str | None

@final
class BatchColumn:
    name: str
    unit: str
    values: list[float] | None
    labels: list[str | None] | None

@final
class BatchResult:
    columns: list[BatchColumn]
    warnings: list[list[Warning]]

@final
class KComponent:
    """One fitting's contribution to the total resistance coefficient."""

    fitting_id: str
    n_ld: float
    k: float

# --- results --------------------------------------------------------------
# Generated from the result dataclasses, so the stub and `azoth.core.result`
# cannot disagree about a field.

@final
class BubblePressureResult:
    pressure: Qty
    incipient: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    min_t_over_tc: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class CriticalPointResult:
    tc: Qty
    pc: Qty
    vc: Qty
    z_c: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class DewPressureResult:
    pressure: Qty
    incipient: list[float]
    k: list[float]
    z_liquid: float
    z_vapour: float
    min_t_over_tc: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class HeatOfVaporizationResult:
    hov: Qty
    warnings: list[Warning]

@final
class IdealGasCpResult:
    cp: Qty
    warnings: list[Warning]

@final
class LiquidHeatCapacityResult:
    cp: Qty
    warnings: list[Warning]

@final
class MolarEnthalpyEntropyResult:
    h: Qty
    s: Qty
    h_ideal: Qty
    s_ideal: Qty
    h_departure: Qty
    s_departure: Qty
    psi_bar: float
    cp: Qty
    cp_ideal: Qty
    cp_departure: Qty
    warnings: list[Warning]

@final
class PhFlashResult:
    T: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class Pr78KappaResult:
    kappa: float
    warnings: list[Warning]

@final
class PrAlphaAbResult:
    alpha: float
    a_reduced: float
    b_reduced: float
    warnings: list[Warning]

@final
class PrDepartureResult:
    ln_phi: float
    h_dep_rt: float
    s_dep_r: float
    cp_dep_r: float
    warnings: list[Warning]

@final
class PrKappaResult:
    kappa: float
    warnings: list[Warning]

@final
class PrMassDensityResult:
    rho: Qty
    warnings: list[Warning]

@final
class PrMolarVolumeResult:
    v: Qty
    warnings: list[Warning]

@final
class PrPenelouxShiftResult:
    c: Qty
    warnings: list[Warning]

@final
class PrZFactorResult:
    z_min: float
    z_max: float
    root_structure: str
    iterations: int
    converged: bool
    residual: float
    warnings: list[Warning]

@final
class PrsvKappaResult:
    kappa: float
    warnings: list[Warning]

@final
class PsFlashResult:
    T: Qty
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    phase: str
    z_liquid: float
    z_vapour: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PtFlashResult:
    beta: float | None
    x: list[float]
    y: list[float]
    k: list[float]
    ln_phi_liquid: list[float]
    ln_phi_vapour: list[float]
    z_liquid: float
    z_vapour: float
    min_t_over_tc: float
    phase: str
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class PureSaturationResult:
    p_sat: Qty
    ln_phi: float
    iterations: int
    residual: float
    warnings: list[Warning]

@final
class RachfordRiceBinaryResult:
    beta: float
    warnings: list[Warning]

@final
class RkAlphaAbResult:
    alpha: float
    a_reduced: float
    b_reduced: float
    warnings: list[Warning]

@final
class RkDepartureResult:
    ln_phi: float
    h_dep_rt: float
    s_dep_r: float
    cp_dep_r: float
    warnings: list[Warning]

@final
class SrkAlphaAbResult:
    alpha: float
    a_reduced: float
    b_reduced: float
    warnings: list[Warning]

@final
class SrkDepartureResult:
    ln_phi: float
    h_dep_rt: float
    s_dep_r: float
    cp_dep_r: float
    warnings: list[Warning]

@final
class SrkKappaResult:
    kappa: float
    warnings: list[Warning]

@final
class SrkPenelouxShiftResult:
    c: Qty
    warnings: list[Warning]

@final
class SrkZFactorResult:
    z_min: float
    z_max: float
    root_structure: str
    iterations: int
    converged: bool
    residual: float
    warnings: list[Warning]

@final
class StabilityTestResult:
    verdict: str
    tm: list[float]
    w: list[list[float]]
    iterations: list[int]
    min_t_over_tc: float
    warnings: list[Warning]

@final
class TwuKappaResult:
    kappa: float
    warnings: list[Warning]

@final
class Vdw1fMixBinaryResult:
    a_mix: float
    b_mix: float
    warnings: list[Warning]

@final
class ChokedFlowAreaResult:
    a: Qty
    warnings: list[Warning]

@final
class ControlValveCvResult:
    q: Qty
    warnings: list[Warning]

@final
class KFactorsResult:
    k_total: float
    f_t: float
    components: list[KComponent]
    warnings: list[Warning]

@final
class DarcyWeisbachResult:
    dp: Qty
    f: float
    re: float | None
    regime: str | None
    warnings: list[Warning]

@final
class ColebrookResult:
    f: float
    iterations: int
    converged: bool
    residual: float
    warnings: list[Warning]

@final
class HaalandResult:
    f: float
    warnings: list[Warning]

@final
class SwameeJainResult:
    f: float
    warnings: list[Warning]

@final
class OrificeFlowResult:
    q: Qty
    warnings: list[Warning]

@final
class PumpPowerResult:
    power: Qty
    warnings: list[Warning]

@final
class ReynoldsNumberResult:
    re: float
    regime: str
    warnings: list[Warning]

@final
class ConductionPlaneWallResult:
    q: Qty
    warnings: list[Warning]

# --- calculations ---------------------------------------------------------
# All arguments and returns are SI magnitudes; unit handling happens once, in
# Python, before the call crosses this boundary. See crates/azoth-python.

def bubble_pressure(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    T: float,
    x: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> BubblePressureResult: ...
def critical_point(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> CriticalPointResult: ...
def dew_pressure(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    T: float,
    y: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> DewPressureResult: ...
def heat_of_vaporization(
    c0: float,
    c1: float,
    c2: float,
    c3: float,
    Tc: float,
    T: float,
) -> HeatOfVaporizationResult: ...
def ideal_gas_cp(
    cp_a: float,
    cp_b: float,
    cp_c: float,
    cp_d: float,
    cp_e: float,
    T: float,
) -> IdealGasCpResult: ...
def liquid_heat_capacity(
    c0: float,
    c1: float,
    c2: float,
    c3: float,
    c4: float,
    T: float,
) -> LiquidHeatCapacityResult: ...
def molar_enthalpy_entropy(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    T: float,
    P: float,
    z: list[float],
    compressibility: float,
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> MolarEnthalpyEntropyResult: ...
def ph_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    P: float,
    H: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PhFlashResult: ...
def pr78_kappa(omega: float) -> Pr78KappaResult: ...
def pr_alpha_ab(kappa: float, Tr: float, Pr: float) -> PrAlphaAbResult: ...
def pr_departure(
    a_reduced: float,
    b_reduced: float,
    z: float,
    kappa: float,
    Tr: float,
) -> PrDepartureResult: ...
def pr_kappa(omega: float) -> PrKappaResult: ...
def pr_mass_density(M: float, v: float) -> PrMassDensityResult: ...
def pr_molar_volume(z: float, T: float, P: float) -> PrMolarVolumeResult: ...
def pr_peneloux_shift(omega: float, Tc: float, Pc: float) -> PrPenelouxShiftResult: ...
def pr_z_factor(a_reduced: float, b_reduced: float) -> PrZFactorResult: ...
def prsv_kappa(omega: float, Tr: float, kappa1: float) -> PrsvKappaResult: ...
def ps_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    cp_a: list[float],
    cp_b: list[float],
    cp_c: list[float],
    cp_d: list[float],
    cp_e: list[float],
    P: float,
    S: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PsFlashResult: ...
def pt_flash(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    T: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> PtFlashResult: ...
def pure_saturation(Tc: float, Pc: float, omega: float, T: float) -> PureSaturationResult: ...
def rachford_rice_binary(z1: float, K1: float, K2: float) -> RachfordRiceBinaryResult: ...
def rk_alpha_ab(Tr: float, Pr: float) -> RkAlphaAbResult: ...
def rk_departure(a_reduced: float, b_reduced: float, z: float) -> RkDepartureResult: ...
def srk_alpha_ab(kappa: float, Tr: float, Pr: float) -> SrkAlphaAbResult: ...
def srk_departure(
    a_reduced: float,
    b_reduced: float,
    z: float,
    kappa: float,
    Tr: float,
) -> SrkDepartureResult: ...
def srk_kappa(omega: float) -> SrkKappaResult: ...
def srk_peneloux_shift(omega: float, Tc: float, Pc: float) -> SrkPenelouxShiftResult: ...
def srk_z_factor(a_reduced: float, b_reduced: float) -> SrkZFactorResult: ...
def stability_test(
    Tc: list[float],
    Pc: list[float],
    omega: list[float],
    kij: list[float],
    T: float,
    P: float,
    z: list[float],
    eos: str = "pr",
    alpha: str = "pr",
    alpha_params: list[list[float]] | None = None,
) -> StabilityTestResult: ...
def twu_kappa(omega: float) -> TwuKappaResult: ...
def vdw1f_mix_binary(
    z1: float,
    a1: float,
    a2: float,
    b1: float,
    b2: float,
    k12: float,
) -> Vdw1fMixBinaryResult: ...
def choked_flow_area(m_dot: float, P0: float, rho0: float, k: float) -> ChokedFlowAreaResult: ...
def control_valve_cv(Cv: float, dP: float, SG: float) -> ControlValveCvResult: ...
def crane_k_factors(fittings: list[str], f_t: float) -> KFactorsResult: ...
def darcy_weisbach(
    f: float,
    L: float,
    D: float,
    rho: float,
    v: float,
    mu: float | None = None,
) -> DarcyWeisbachResult: ...
def friction_factor_colebrook(re: float, relative_roughness: float) -> ColebrookResult: ...
def friction_factor_haaland(re: float, relative_roughness: float) -> HaalandResult: ...
def friction_factor_swamee_jain(re: float, relative_roughness: float) -> SwameeJainResult: ...
def orifice_flow(d: float, dP: float, rho: float, Cd: float) -> OrificeFlowResult: ...
def pump_power(rho: float, q: float, H: float, eta: float) -> PumpPowerResult: ...
def reynolds_number(rho: float, v: float, D: float, mu: float) -> ReynoldsNumberResult: ...
def conduction_plane_wall(k: float, A: float, dT: float, L: float) -> ConductionPlaneWallResult: ...

# --- introspection --------------------------------------------------------

def batch_run(calc_id: str, inputs: dict[str, list[float]]) -> BatchResult: ...
def data_files() -> list[DataFile]: ...
def fittings_rows() -> list[FittingRow]: ...
def fluid_rows(name: str) -> list[FluidRow]: ...
def component_rows() -> list[ComponentRow]: ...
def kij_rows() -> list[KijRow]: ...
def overlay(components: list[tuple[str, float | None, float | None, float | None]], kij: list[tuple[str, str, float]]) -> Overlay: ...
def card_overlay(text: str) -> Overlay: ...
def overlay_entry_row(name: str, overlay: Overlay) -> ComponentRow: ...
def overlay_component_rows(overlay: Overlay) -> list[ComponentRow]: ...
def overlay_kij_rows(overlay: Overlay) -> list[tuple[str, str, float]]: ...
def warning_codes() -> list[str]: ...
def unit_names() -> list[str]: ...
def solver_kinds() -> list[str]: ...
def model_ids() -> list[str]: ...
def model_schemes(model_id: str) -> list[str]: ...
def model_kind(model_id: str) -> str: ...
def result_fields(calc_id: str) -> list[str]: ...
def calc_ids() -> list[str]: ...
def version() -> str: ...

# --- exceptions -----------------------------------------------------------
# Re-exported from azoth.core.errors, so both backends raise the same class
# objects rather than two lookalike hierarchies.

class AzothError(Exception): ...
class InvalidInputError(AzothError, ValueError): ...
class OutOfRangeError(AzothError, ValueError): ...
class PropertyUnavailableError(AzothError, LookupError): ...
class SolverNotConvergedError(AzothError, RuntimeError): ...
class UnitMismatchError(AzothError, TypeError): ...
class UnknownFittingError(AzothError, LookupError): ...
