"""GENERATED FILE - DO NOT EDIT BY HAND.

Generated by `tools/gen_vocabulary.py` from
`specs/vocabulary/vocabulary.toml`.

The same data the Rust side reads from `azoth_core::unit_vocab_gen`, and
generated from the same table so the two cannot name different sets.
"""

from __future__ import annotations

from typing import Final

#: The base dimensions, in the order every exponent tuple here is written in.
#: uom::si::ISQ's order; see the table.
SLOTS: Final[tuple[str, ...]] = ("L", "M", "T", "I", "Th", "N", "J")

#: Canonical unit strings, keyed by the strings the spec schema allows, mapped
#: to the unit's name in `pint`'s registry. This is the unit a spec and its
#: generated docs speak in - what a worked example's numbers mean, and what a
#: caller gets back. It is deliberately not the unit anything is calculated
#: in: calculations work in SI base magnitudes, and `to_si`/`from_si` are the
#: only places the two representations meet.
CANONICAL_UNITS: Final[dict[str, str]] = {
    "dimensionless": "dimensionless",
    "m": "meter",
    "mm": "millimeter",
    "m**2": "meter**2",
    "m**3/s": "meter**3/second",
    "kg/s": "kilogram/second",
    "mol/s": "mole/second",
    "kg/m**3": "kilogram/meter**3",
    "m/s": "meter/second",
    "m**2/s": "meter**2/second",
    "Pa": "pascal",
    "Pa*s": "pascal*second",
    "K": "kelvin",
    "W": "watt",
    "J/(kg*K)": "joule/(kilogram*kelvin)",
    "W/(m*K)": "watt/(meter*kelvin)",
    "W/(m**2*K)": "watt/(meter**2*kelvin)",
    "kg/mol": "kilogram/mole",
    "m**3/mol": "meter**3/mole",
    "J/mol": "joule/mole",
    "J/(mol*K)": "joule/(mole*kelvin)",
    "J/(mol*K**2)": "joule/(mole*kelvin**2)",
    "J/(mol*K**3)": "joule/(mole*kelvin**3)",
    "J/(mol*K**4)": "joule/(mole*kelvin**4)",
    "J/(mol*K**5)": "joule/(mole*kelvin**5)",
}

#: The canonical unit strings, in table order. The keycard loader validates
#: against this rather than reading the schema, which is a dev-time artefact
#: and does not ship in the wheel.
UNIT_VOCABULARY: Final[tuple[str, ...]] = tuple(CANONICAL_UNITS)


#: `SLOTS` is the table's slot order, and it is here because something reads
#: it: `python/tests/test_units_cross_library.py` maps `pint`'s base dimensions
#: onto these names, and compares them with the Rust side's through
#: `azoth._core.unit_slots`. The table's *exponents* are deliberately not
#: carried here - Python's runtime need is a name and its `pint` spelling, and a
#: dimension is something only a caller asking for one needs. They arrive when
#: such a caller does, not before.
