//! The domain each card parameter has to lie in, emitted from the component schema.
//!
//! Generated by `tools/gen_parameter_bounds.py` - see its module documentation for why a
//! bound is stated in the parameter's own declared unit and why it is not a proof.
//! **Do not edit by hand.**

/// A bound on one parameter, in the unit `COMPONENT_PARAMETERS` declares it in.
#[derive(Debug, Clone, Copy)]
pub struct ParameterBound {
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub min_inclusive: bool,
    pub max_inclusive: bool,
    /// What the domain is a statement about, carried so both readers refuse in the same
    /// words rather than each writing its own sentence.
    pub rationale: &'static str,
}

/// Each bounded parameter, in the unit `COMPONENT_PARAMETERS` declares it in.
pub const PARAMETER_BOUNDS: &[(&str, ParameterBound)] = &[
    ("Tc", ParameterBound {
        min: Some(0.0),
        max: None,
        min_inclusive: false,
        max_inclusive: false,
        rationale: "A critical temperature is an absolute temperature; zero and below are not states.",
    }),
    ("Pc", ParameterBound {
        min: Some(0.0),
        max: None,
        min_inclusive: false,
        max_inclusive: false,
        rationale: "A critical pressure is an absolute pressure; zero and below are not states.",
    }),
];

/// Every parameter with no stated domain, and why - a decision, not an omission.
pub const UNBOUNDED: &[(&str, &str)] = &[
    ("omega", "the shipped table spans -0.39003 to 2.8353, so a sign bound would refuse neon, and no source states a band"),
    ("cp_a", "a fitted polynomial's constant term: the shipped table carries zeros for absent terms and both signs"),
    ("cp_b", "a fitted polynomial's linear coefficient: the shipped table carries zeros for absent terms and both signs"),
    ("cp_c", "a fitted polynomial's quadratic coefficient: the shipped table carries zeros for absent terms and both signs"),
    ("cp_d", "a fitted polynomial's cubic coefficient: the shipped table carries zeros for absent terms and both signs"),
    ("cp_e", "a fitted polynomial's quartic coefficient: the shipped table carries zeros for absent terms and both signs"),
    ("ionic_charge", "a charge is a class rather than a magnitude; 289 of the 348 shipped rows are zero"),
    ("deshmukh_mather_diameter", "28 of the 348 shipped rows are zero - a placeholder rather than a state - so a positivity bound would refuse the table this derives from"),
    ("dielectric_1", "a fitted coefficient with zeros for absent terms and both signs"),
    ("dielectric_2", "a fitted coefficient with zeros for absent terms and both signs"),
    ("dielectric_3", "a fitted coefficient with zeros for absent terms and both signs"),
    ("dielectric_4", "a fitted coefficient with zeros for absent terms and both signs"),
    ("dielectric_5", "a fitted coefficient with zeros for absent terms and both signs"),
];

/// The bound on `name`, or `None` where the domain is not stated.
#[must_use]
pub fn parameter_bound(name: &str) -> Option<&'static ParameterBound> {
    PARAMETER_BOUNDS
        .iter()
        .find(|(parameter, _)| *parameter == name)
        .map(|(_, bound)| bound)
}
