//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_vocabulary.py` from
//! `specs/vocabulary/vocabulary.toml`.

/// The base dimensions, in the order every exponent tuple here is written in.
///
/// uom::si::ISQ's order, and not cosmetic: the tuples below and the uom
/// quantity types the table's assertions are written against are both built
/// from it, so a different order permutes all of them at once.
pub const SLOTS: [&str; 7] = ["L", "M", "T", "I", "Th", "N", "J"];

/// Every canonical unit string a spec may declare.
///
/// A name here is a claim that this crate has a correct conversion path for
/// it - see `conversion`, and the tests in `crate::units` that hold the two
/// lists to each other.
pub const UNIT_NAMES: &[&str] = &[
    "dimensionless",
    "m",
    "mm",
    "m**2",
    "m**3/s",
    "kg/s",
    "mol/s",
    "kg/m**3",
    "m/s",
    "m**2/s",
    "Pa",
    "Pa*s",
    "K",
    "W",
    "J/(kg*K)",
    "W/(m*K)",
    "W/(m**2*K)",
    "kg/mol",
    "m**3/mol",
    "J/mol",
    "J/(mol*K)",
    "J/(mol*K**2)",
    "J/(mol*K**3)",
    "J/(mol*K**4)",
    "J/(mol*K**5)",
];

/// Each unit's dimension, as exponents in [`SLOTS`] order.
pub const UNIT_DIMENSIONS: &[(&str, [i8; 7])] = &[
    ("dimensionless", [0, 0, 0, 0, 0, 0, 0]),
    ("m", [1, 0, 0, 0, 0, 0, 0]),
    ("mm", [1, 0, 0, 0, 0, 0, 0]),
    ("m**2", [2, 0, 0, 0, 0, 0, 0]),
    ("m**3/s", [3, 0, -1, 0, 0, 0, 0]),
    ("kg/s", [0, 1, -1, 0, 0, 0, 0]),
    ("mol/s", [0, 0, -1, 0, 0, 1, 0]),
    ("kg/m**3", [-3, 1, 0, 0, 0, 0, 0]),
    ("m/s", [1, 0, -1, 0, 0, 0, 0]),
    ("m**2/s", [2, 0, -1, 0, 0, 0, 0]),
    ("Pa", [-1, 1, -2, 0, 0, 0, 0]),
    ("Pa*s", [-1, 1, -1, 0, 0, 0, 0]),
    ("K", [0, 0, 0, 0, 1, 0, 0]),
    ("W", [2, 1, -3, 0, 0, 0, 0]),
    ("J/(kg*K)", [2, 0, -2, 0, -1, 0, 0]),
    ("W/(m*K)", [1, 1, -3, 0, -1, 0, 0]),
    ("W/(m**2*K)", [0, 1, -3, 0, -1, 0, 0]),
    ("kg/mol", [0, 1, 0, 0, 0, -1, 0]),
    ("m**3/mol", [3, 0, 0, 0, 0, -1, 0]),
    ("J/mol", [2, 1, -2, 0, 0, -1, 0]),
    ("J/(mol*K)", [2, 1, -2, 0, -1, -1, 0]),
    ("J/(mol*K**2)", [2, 1, -2, 0, -2, -1, 0]),
    ("J/(mol*K**3)", [2, 1, -2, 0, -3, -1, 0]),
    ("J/(mol*K**4)", [2, 1, -2, 0, -4, -1, 0]),
    ("J/(mol*K**5)", [2, 1, -2, 0, -5, -1, 0]),
];

/// One row of [`CONVERSION_PATHS`]: a canonical unit string, and the
/// conversion this crate performs for it.
pub type ConversionPath = (&'static str, fn(f64) -> f64);

/// Each unit's conversion from the declared unit to the SI base magnitude.
///
/// A unit whose dimension uom carries goes through the hand-written
/// constructor in [`crate::units`]; one whose dimension it does not is
/// already its own SI base unit, so the conversion is the identity.
///
/// There is deliberately no expected magnitude beside these. A factor is a
/// number `uom` and `pint` each already know, and the check that these are
/// right is `python/tests/test_units_cross_library.py`, which compares the
/// result of calling one of these against `pint`'s answer for the same name.
/// Writing the number down here would be the defect this generated file
/// exists to remove.
pub const CONVERSION_PATHS: &[ConversionPath] = &[
    ("dimensionless", |v| v),
    ("m", |v| crate::units::meters(v).value),
    ("mm", |v| crate::units::millimeters(v).value),
    ("m**2", |v| crate::units::square_meters(v).value),
    ("m**3/s", |v| crate::units::cubic_meters_per_second(v).value),
    ("kg/s", |v| crate::units::kilograms_per_second(v).value),
    ("mol/s", |v| v),
    ("kg/m**3", |v| {
        crate::units::kilograms_per_cubic_meter(v).value
    }),
    ("m/s", |v| crate::units::meters_per_second(v).value),
    ("m**2/s", |v| {
        crate::units::square_meters_per_second(v).value
    }),
    ("Pa", |v| crate::units::pascals(v).value),
    ("Pa*s", |v| crate::units::pascal_seconds(v).value),
    ("K", |v| crate::units::kelvins(v).value),
    ("W", |v| crate::units::watts(v).value),
    ("J/(kg*K)", |v| {
        crate::units::joules_per_kilogram_kelvin(v).value
    }),
    ("W/(m*K)", |v| crate::units::watts_per_meter_kelvin(v).value),
    ("W/(m**2*K)", |v| {
        crate::units::watts_per_square_meter_kelvin(v).value
    }),
    ("kg/mol", |v| crate::units::kilograms_per_mole(v).value),
    ("m**3/mol", |v| crate::units::cubic_meters_per_mole(v).value),
    ("J/mol", |v| crate::units::joules_per_mole(v).value),
    ("J/(mol*K)", |v| {
        crate::units::joules_per_mole_kelvin(v).value
    }),
    ("J/(mol*K**2)", |v| v),
    ("J/(mol*K**3)", |v| v),
    ("J/(mol*K**4)", |v| v),
    ("J/(mol*K**5)", |v| v),
];

/// The conversion for one canonical unit, or `None` if the name is not in
/// the vocabulary.
#[must_use]
pub fn conversion(name: &str) -> Option<fn(f64) -> f64> {
    CONVERSION_PATHS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, f)| *f)
}

/// The SI base magnitude one of `name` is worth, by running the same
/// conversion a calculation runs.
///
/// This is what makes the conversion checkable from outside: the caller that
/// reads it is `azoth._core.unit_si_factor`, and what it is compared against
/// is `pint`.
#[must_use]
pub fn si_factor(name: &str) -> Option<f64> {
    conversion(name).map(|f| f(1.0))
}

/// The dimension of one canonical unit, or `None` if the name is not in the
/// vocabulary.
#[must_use]
pub fn dimension(name: &str) -> Option<[i8; 7]> {
    UNIT_DIMENSIONS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, d)| *d)
}

#[cfg(test)]
mod dimension_assertions {
    //! One assertion per unit, and the whole point of deriving the uom type
    //! from the exponents rather than declaring it beside them.
    //!
    //! Each line says: the constructor the conversion calls produces the uom
    //! quantity that THIS unit's exponents name. Change an exponent in the
    //! table and the two sides stop being the same type, so this fails to
    //! compile rather than passing on a name that happens to match.

    #[test]
    fn the_table_agrees_with_uom() {
        let _: uom::si::f64::Length = crate::units::meters(1.0);
        let _: uom::si::f64::Length = crate::units::millimeters(1.0);
        let _: uom::si::f64::Area = crate::units::square_meters(1.0);
        let _: uom::si::f64::VolumeRate = crate::units::cubic_meters_per_second(1.0);
        let _: uom::si::f64::MassRate = crate::units::kilograms_per_second(1.0);
        let _: uom::si::f64::MassDensity = crate::units::kilograms_per_cubic_meter(1.0);
        let _: uom::si::f64::Velocity = crate::units::meters_per_second(1.0);
        let _: uom::si::f64::DiffusionCoefficient = crate::units::square_meters_per_second(1.0);
        let _: uom::si::f64::Pressure = crate::units::pascals(1.0);
        let _: uom::si::f64::DynamicViscosity = crate::units::pascal_seconds(1.0);
        let _: uom::si::f64::ThermodynamicTemperature = crate::units::kelvins(1.0);
        let _: uom::si::f64::Power = crate::units::watts(1.0);
        let _: uom::si::f64::SpecificHeatCapacity = crate::units::joules_per_kilogram_kelvin(1.0);
        let _: uom::si::f64::ThermalConductivity = crate::units::watts_per_meter_kelvin(1.0);
        let _: uom::si::f64::HeatTransfer = crate::units::watts_per_square_meter_kelvin(1.0);
        let _: uom::si::f64::MolarMass = crate::units::kilograms_per_mole(1.0);
        let _: uom::si::f64::MolarVolume = crate::units::cubic_meters_per_mole(1.0);
        let _: uom::si::f64::MolarEnergy = crate::units::joules_per_mole(1.0);
        let _: uom::si::f64::MolarHeatCapacity = crate::units::joules_per_mole_kelvin(1.0);
    }
}
