//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_models.py` from:
//!   - specs/models/standards/iso6976.toml
//!
//! Regenerate with `python tools/gen_models.py`; CI runs `--check` and fails
//! on any difference.

use azoth_core::{Band, ModelSpec, RangeCheck, Severity, SpecCheck, TestCase, WarningCode};

static ISO6976_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "volumetric_reference_temperature",
            min: Some(273.15),
            min_inclusive: true,
            max: Some(293.15),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "the standard's metering temperatures, 0 to 20 C; 15.55 C is the 60 F reference and is inside this interval",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "energy_reference_temperature",
            min: Some(273.15),
            min_inclusive: true,
            max: Some(298.15),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "the standard's combustion temperatures, 0 to 25 C",
        },
    },
];

static ISO6976_CASES: &[TestCase] = &[
    TestCase {
        id: "pure_methane_15_25",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("volumetric_reference_temperature", 288.15),
            ("energy_reference_temperature", 298.15),
        ],
        flags: &[],
        lists: &[("components", &["methane"])],
        strings: &[],
        vectors: &[("z", &[1.0])],
        matrices: &[],
        expected: &[
            ("molar_mass", 0.016042999999999998),
            ("compression_factor", 0.99800191),
            ("relative_density", 0.5547423719626038),
            ("density_ideal", 0.6784954068722058),
            ("density_real", 0.679853815983384),
            ("superior_calorific_value", 890630.0),
            ("inferior_calorific_value", 802600.0),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "methane_butane_15_25",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("volumetric_reference_temperature", 288.15),
            ("energy_reference_temperature", 298.15),
        ],
        flags: &[],
        lists: &[("components", &["methane", "n-butane"])],
        strings: &[],
        vectors: &[("z", &[0.9, 0.1])],
        matrices: &[],
        expected: &[
            ("molar_mass", 0.020250999999999998),
            ("compression_factor", 0.9965260764),
            ("relative_density", 0.7012856208949791),
            ("density_ideal", 0.8564614152321285),
            ("density_real", 0.8594470686869911),
            ("superior_calorific_value", 1089307.0),
            ("inferior_calorific_value", 988072.0000000001),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "sales_gas_15_25",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("volumetric_reference_temperature", 288.15),
            ("energy_reference_temperature", 298.15),
        ],
        flags: &[],
        lists: &[(
            "components",
            &["methane", "ethane", "propane", "n-butane", "nitrogen"],
        )],
        strings: &[],
        vectors: &[("z", &[0.85, 0.07, 0.03, 0.02, 0.03])],
        matrices: &[],
        expected: &[
            ("molar_mass", 0.019067225),
            ("compression_factor", 0.997220179824),
            ("relative_density", 0.6598322847124574),
            ("density_ideal", 0.8063968449977494),
            ("density_real", 0.808644731938809),
            ("superior_calorific_value", 990406.8999999999),
            ("inferior_calorific_value", 896654.5000000001),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "sour_gas_15_25",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("volumetric_reference_temperature", 288.15),
            ("energy_reference_temperature", 298.15),
        ],
        flags: &[],
        lists: &[("components", &["methane", "CO2", "nitrogen"])],
        strings: &[],
        vectors: &[("z", &[0.8, 0.15, 0.05])],
        matrices: &[],
        expected: &[
            ("molar_mass", 0.020836575),
            ("compression_factor", 0.997710855975),
            ("relative_density", 0.7207070392979196),
            ("density_ideal", 0.8812267301906272),
            ("density_real", 0.8832486134767571),
            ("superior_calorific_value", 712504.0),
            ("inferior_calorific_value", 642080.0),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "methane_butane_0_15_55",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("volumetric_reference_temperature", 273.15),
            ("energy_reference_temperature", 288.7),
        ],
        flags: &[],
        lists: &[("components", &["methane", "n-butane"])],
        strings: &[],
        vectors: &[("z", &[0.9, 0.1])],
        matrices: &[],
        expected: &[
            ("molar_mass", 0.020250999999999998),
            ("compression_factor", 0.9958022559),
            ("relative_density", 0.7016760102400963),
            ("density_ideal", 0.9034938927297743),
            ("density_real", 0.907302516515392),
            ("superior_calorific_value", 1090322.0),
            ("inferior_calorific_value", 988179.0000000001),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "sales_gas_0_15_55",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("volumetric_reference_temperature", 273.15),
            ("energy_reference_temperature", 288.7),
        ],
        flags: &[],
        lists: &[(
            "components",
            &["methane", "ethane", "propane", "n-butane", "nitrogen"],
        )],
        strings: &[],
        vectors: &[("z", &[0.85, 0.07, 0.03, 0.02, 0.03])],
        matrices: &[],
        expected: &[
            ("molar_mass", 0.019067225),
            ("compression_factor", 0.996656963239),
            ("relative_density", 0.6600928776978187),
            ("density_ideal", 0.8506800325319478),
            ("density_real", 0.8535334261523173),
            ("superior_calorific_value", 991349.9999999999),
            ("inferior_calorific_value", 896756.7000000001),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "pure_methane_0_15_55",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-09,
        numbers: &[
            ("volumetric_reference_temperature", 273.15),
            ("energy_reference_temperature", 288.7),
        ],
        flags: &[],
        lists: &[("components", &["methane"])],
        strings: &[],
        vectors: &[("z", &[1.0])],
        matrices: &[],
        expected: &[
            ("molar_mass", 0.016042999999999998),
            ("compression_factor", 0.997599),
            ("relative_density", 0.5548720372209514),
            ("density_ideal", 0.7157549020326784),
            ("density_real", 0.7174775656678469),
            ("superior_calorific_value", 891510.0),
            ("inferior_calorific_value", 802690.0),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
];

/// Registry entry for `standards.iso6976`.
pub static ISO6976_SPEC: ModelSpec = ModelSpec {
    id: "standards.iso6976",
    kind: "direct",
    algorithm: None,
    checks: ISO6976_CHECKS,
    cases: ISO6976_CASES,
};

static ALL_MODELS: &[&ModelSpec] = &[&ISO6976_SPEC];

/// Every model in this namespace, in id order.
#[must_use]
pub fn models() -> &'static [&'static ModelSpec] {
    ALL_MODELS
}

/// One model by id, or `None`. Used by the contract tests.
#[must_use]
pub fn model(id: &str) -> Option<&'static ModelSpec> {
    ALL_MODELS.iter().copied().find(|m| m.id == id)
}
