//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_models.py` from:
//!   - specs/models/reactions/reference_potentials.toml
//!
//! Regenerate with `python tools/gen_models.py`; CI runs `--check` and fails
//! on any difference.

use azoth_core::{Band, ModelSpec, RangeCheck, Severity, SpecCheck, TestCase, WarningCode};

static REFERENCE_POTENTIALS_CHECKS: &[SpecCheck] = &[SpecCheck {
    on_input: true,
    check: RangeCheck {
        quantity: "T",
        min: Some(0.0),
        min_inclusive: false,
        max: None,
        max_inclusive: true,
        equals: None,
        band: Band::Outside,
        severity: Severity::Error,
        code: WarningCode::OutOfValidRange,
        rationale: "an absolute temperature, and the constants take its logarithm",
    },
}];

static REFERENCE_POTENTIALS_CASES: &[TestCase] = &[
    TestCase {
        id: "co2_water_standard_at_298_15",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("T", 298.15)],
        flags: &[],
        lists: &[(
            "components",
            &["CO2", "water", "OH-", "H3O+", "HCO3-", "CO3--"],
        )],
        strings: &[("source", "standard")],
        vectors: &[],
        matrices: &[],
        expected: &[("rank", 3.0)],
        expected_vectors: &[
            (
                "potentials",
                &[
                    -135846.03262887645,
                    86061.16003668531,
                    72306.22849248124,
                    199632.18316177875,
                    -127079.60827279043,
                    -154589.47136119858,
                ],
            ),
            ("independent", &[1.0, 1.0, 1.0, 0.0, 0.0, 0.0]),
            ("survivors", &[1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0]),
        ],
        expected_strings: &[],
    },
    TestCase {
        id: "co2_h2s_water_standard_at_298_15",
        kind: "case",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("T", 298.15)],
        flags: &[],
        lists: &[(
            "components",
            &[
                "CO2", "H2S", "water", "HS-", "OH-", "H3O+", "HCO3-", "S--", "CO3--",
            ],
        )],
        strings: &[("source", "standard")],
        vectors: &[],
        matrices: &[],
        expected: &[("rank", 5.0)],
        expected_vectors: &[
            (
                "potentials",
                &[
                    -135846.03262887645,
                    -15109.3096192815,
                    86061.16003668531,
                    21019.134456794694,
                    72306.22849248124,
                    199632.18316177875,
                    -127079.60827279043,
                    14528.405825181253,
                    -154589.47136119858,
                ],
            ),
            (
                "independent",
                &[1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
            ),
            ("survivors", &[1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]),
        ],
        expected_strings: &[],
    },
];

/// Registry entry for `reactions.reference_potentials`.
pub static REFERENCE_POTENTIALS_SPEC: ModelSpec = ModelSpec {
    id: "reactions.reference_potentials",
    kind: "direct",
    algorithm: None,
    checks: REFERENCE_POTENTIALS_CHECKS,
    cases: REFERENCE_POTENTIALS_CASES,
};

static ALL_MODELS: &[&ModelSpec] = &[&REFERENCE_POTENTIALS_SPEC];

/// Every model in this namespace, in id order.
#[must_use]
pub fn models() -> &'static [&'static ModelSpec] {
    ALL_MODELS
}

/// One model by id, or `None`. Used by the contract tests.
#[must_use]
pub fn model(id: &str) -> Option<&'static ModelSpec> {
    ALL_MODELS.iter().copied().find(|m| m.id == id)
}
