#!/usr/bin/env python3
"""Derive `databank/keycard.toml` (the baseline card) from the compiled component data.

    python tools/gen_keycard.py --check

The baseline card is azoth's shipped data - the components a cubic reads (`Tc`, `Pc`,
`omega`) and the Peng-Robinson interaction parameters - stated in exactly the format a
user's keycard takes. It is derived from `data/components/components.csv` and
`kij.csv`, which are themselves derived from NeqSim's `COMP.csv` and `INTER.csv`, so the
library's data and a user's data are one object: a card.

The component parameters are read from `specs/schema/component.schema.json`, the single
declaration of what a card may state and the compiled column each comes from. This file
does not re-list them. The interaction parameter is `kij_pr`, the one a cubic's
classical mixing rule reads; the card's `value` for a pair is that column.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "specs" / "schema" / "component.schema.json"
COMPONENTS_CSV = ROOT / "data" / "components" / "components.csv"
KIJ_CSV = ROOT / "data" / "components" / "kij.csv"
OUT = ROOT / "databank" / "keycard.toml"

BANNER = """\
# databank/keycard.toml - azoth's shipped data, as a keycard.
#
# Generated by tools/gen_keycard.py from data/components/. Do not edit by hand.
# The values are NeqSim v3.20.0's (Equinor/NTNU, Apache-2.0), the same source
# databank/manifest.toml names; see NOTICE for the attribution.
"""


def parameters() -> list[tuple[str, str, str]]:
    """The (card name, compiled column, unit) triples, from the single declaration."""
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    return [
        (name, props["x-azoth-column"], props["x-azoth-unit"])
        for name, props in schema["properties"].items()
    ]


def toml_key(key: str) -> str:
    """A TOML key, quoted only where a bare key would not parse.

    Component names carry spaces (`acetic acid`) and dots (`1.2-dm-cyc5`), neither of
    which a bare key admits. A JSON string is a TOML basic string, so `json.dumps` is
    the quoter for both the key and the escape rules.
    """
    if key and all(ch.isalnum() or ch in "_-" for ch in key):
        return key
    return json.dumps(key)


def render() -> str:
    parts = [BANNER, "schema_version = 2\n"]
    params = parameters()

    rows = list(csv.DictReader(COMPONENTS_CSV.read_text(encoding="utf-8").splitlines()))
    rows.sort(key=lambda r: r["name"])
    for row in rows:
        name = toml_key(row["name"])
        for card, column, unit in params:
            value = row[column]
            parts.append(
                f"\n[components.{name}.{card}]\nvalue = {value}\nunit = {json.dumps(unit)}\n"
            )

    kij = list(csv.DictReader(KIJ_CSV.read_text(encoding="utf-8").splitlines()))
    # A self-pair (`n-butane` with `n-butane`) is NeqSim's own diagonal, which the
    # databank loader carries but never reads - the kij matrix's diagonal is zero by
    # construction. The card format refuses one, so it is left out here rather than
    # shipped as a value the loader would reject.
    kij = [r for r in kij if r["component_a"] != r["component_b"]]
    kij.sort(key=lambda r: (r["component_a"], r["component_b"]))
    for row in kij:
        parts.append(
            f"\n[[kij]]\n"
            f"component_a = {json.dumps(row['component_a'])}\n"
            f"component_b = {json.dumps(row['component_b'])}\n"
            f"value = {row['kij_pr']}\n"
        )

    return "".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report drift; write nothing")
    args = parser.parse_args(argv)

    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print(f"gen_keycard: {OUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        print(f"gen_keycard: {OUT.relative_to(ROOT)} up to date")
        return 0

    OUT.write_text(text, encoding="utf-8")
    print(f"gen_keycard: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
