#!/usr/bin/env python3
"""Generate the model-input table the palette's entries are keyed by.

`gen_models.py` compiles a model's bounds and its cases into Rust and **drops its inputs**: a
bound names its quantity by string and a case names its values by position, so neither needs the
declaration. The names, the kinds (`quantity`, `vector`, `boolean`, `enum`, `components`) and the
`optional` flags therefore exist only in the spec file - and a front-end that renders a unit
operation's form cannot choose a widget without the kind. `Param` in the palette carries a unit
and no type, which is the gap this table fills.

Kept out of `gen_models.py` on purpose: that generator owns `model_gen.rs` and the Python mirror
of the same table, and a second concern in it would mean a change here regenerating files a
change there also writes.

    python tools/gen_model_inputs.py            # write
    python tools/gen_model_inputs.py --check    # fail if the tree is not what this emits
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
PALETTE_DIR = ROOT / "specs" / "unit_ops"
MODEL_DIR = ROOT / "specs" / "models" / "process"
OUT = ROOT / "crates" / "azoth-process" / "src" / "model_inputs_gen.rs"

#: A palette id and the model id it names. The rule, not a table: `unit_ops.pump` is
#: `process.pump`, and an entry whose model is not named this way has no model.
PALETTE_PREFIX = "unit_ops."
MODEL_PREFIX = "process."


def load_palette() -> list[dict[str, Any]]:
    """Every palette entry, in path order with its own path recorded."""
    entries = []
    for path in sorted(PALETTE_DIR.rglob("*.toml")):
        spec = tomllib.loads(path.read_text(encoding="utf-8"))
        spec["_path"] = path.relative_to(ROOT)
        entries.append(spec)
    if not entries:
        sys.exit(f"gen_model_inputs: no palette entries under {PALETTE_DIR}")
    return entries


def load_models() -> dict[str, dict[str, Any]]:
    """Every process model, by id, with its own path recorded."""
    models: dict[str, dict[str, Any]] = {}
    for path in sorted(MODEL_DIR.glob("*.toml")):
        spec = tomllib.loads(path.read_text(encoding="utf-8"))
        spec["_path"] = path.relative_to(ROOT)
        models[spec["id"]] = spec
    if not models:
        sys.exit(f"gen_model_inputs: no models under {MODEL_DIR}")
    return models


def model_id_for(palette_id: str) -> str:
    return MODEL_PREFIX + palette_id.removeprefix(PALETTE_PREFIX)


def rust_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def emit_rust(
    rows: list[tuple[dict[str, Any], dict[str, Any]]], palette: list[dict[str, Any]]
) -> str:
    """The input table, and the two accessors a caller needs."""
    listed = "".join(f"//!   - {entry['_path']}\n" for entry in palette)
    banner = (
        "//! GENERATED FILE - DO NOT EDIT BY HAND.\n//!\n"
        "//! Generated by `tools/gen_model_inputs.py` from:\n"
        f"{listed}"
        "//!\n"
        "//! Regenerate with `python tools/gen_model_inputs.py`; CI runs `--check` and\n"
        "//! fails on any difference.\n\n"
        "/// One input a model declares, as the spec declares it.\n"
        "///\n"
        "/// **The declaration `gen_models.py` drops.** A model's bounds and cases are compiled\n"
        "/// into `model_gen`, and neither carries the input's own name, so the kind a form\n"
        "/// chooses a widget from exists only in the spec file this table is generated from.\n"
        "pub struct ModelInput {\n"
        "    /// The input's name in the spec, e.g. `outlet_pressure`.\n"
        "    pub name: &'static str,\n"
        "    /// The spec's `type`, or `quantity` where it carries none.\n"
        "    pub kind: &'static str,\n"
        "    /// An `enum`'s allowed values, in the spec's order; empty for every other kind.\n"
        "    pub values: &'static [&'static str],\n"
        "    /// Whether the spec marks the input `optional = true`.\n"
        "    pub optional: bool,\n"
        "}\n\n"
        "/// The inputs one palette entry's model declares.\n"
        "pub struct ModelInputs {\n"
        "    /// The palette id, e.g. `unit_ops.compressor`.\n"
        "    pub unit_op: &'static str,\n"
        "    /// The model id, e.g. `process.compressor`.\n"
        "    pub model: &'static str,\n"
        "    /// The declared inputs, in the spec's order.\n"
        "    pub inputs: &'static [ModelInput],\n"
        "}\n\n"
        "static ALL: &[ModelInputs] = &[\n"
    )

    rows_text = []
    for palette_entry, model in rows:
        inputs = "".join(
            "            ModelInput {{ name: {}, kind: {}, values: &[{}],"
            " optional: {} }},\n".format(
                rust_str(name),
                rust_str(declaration.get("type", "quantity")),
                ", ".join(rust_str(value) for value in declaration.get("values", [])),
                "true" if declaration.get("optional") else "false",
            )
            for name, declaration in model.get("inputs", {}).items()
        )
        rows_text.append(
            "    ModelInputs {{\n"
            "        unit_op: {},\n"
            "        model: {},\n"
            "        inputs: &[\n"
            "{}"
            "        ],\n"
            "    }},\n".format(rust_str(palette_entry["id"]), rust_str(model["id"]), inputs)
        )

    return (
        banner + "".join(rows_text) + "];\n\n"
        "/// Every palette entry that names a model, in palette-id order.\n"
        "#[must_use]\n"
        "pub fn model_inputs() -> &'static [ModelInputs] {\n"
        "    ALL\n"
        "}\n\n"
        "/// One entry's model inputs, or `None` for an entry with no model.\n"
        "///\n"
        "/// Two of the twenty-nine are in that state and `executor::dispatch::UNRUNNABLE` names\n"
        "/// both, so `None` here and a refusal there are the same fact stated twice.\n"
        "#[must_use]\n"
        "pub fn inputs_for(unit_op: &str) -> Option<&'static ModelInputs> {\n"
        "    ALL.iter().find(|entry| entry.unit_op == unit_op)\n"
        "}\n"
    )


def format_rust(text: str, generator: str) -> str:
    """Run the emitted Rust through rustfmt, which every generated file is compared against.

    **A missing rustfmt is a refusal rather than a fallback**, where `gen_vocabulary.py` emits
    unformatted source and lets `cargo fmt --check` catch it. That fallback cannot work here: these
    generators are checked by comparing their output to the *committed* file, so emitting
    unformatted text would report the file as stale and send a reader looking for a drift that is
    not there. The toolchain is the prerequisite, and the message says so.
    """
    try:
        proc = subprocess.run(
            ["rustfmt", "--edition", "2024"],
            input=text,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        sys.exit(
            f"{generator}: rustfmt is not on PATH, and the generated file is compared against "
            f"rustfmt's own output - install the Rust toolchain"
        )
    if proc.returncode != 0:
        sys.exit(f"{generator}: rustfmt refused the output:\n{proc.stderr}")
    return proc.stdout


def main() -> None:
    check = "--check" in sys.argv
    palette = load_palette()
    models = load_models()

    rows: list[tuple[dict[str, Any], dict[str, Any]]] = []
    unmodelled: list[str] = []
    for entry in palette:
        model = models.get(model_id_for(entry["id"]))
        if model is None:
            unmodelled.append(entry["id"])
            continue
        rows.append((entry, model))
    rows.sort(key=lambda row: row[0]["id"])

    # A model no palette entry can reach is a spec nothing runs, which is a defect rather than
    # a curiosity - so it stops the generator rather than being left out of the table.
    claimed = {model_id_for(entry["id"]) for entry in palette}
    orphans = sorted(set(models) - claimed)
    if orphans:
        sys.exit(
            "gen_model_inputs: these models are named by no palette entry, so nothing can run "
            f"them: {', '.join(orphans)}"
        )

    rendered = format_rust(emit_rust(rows, palette), "gen_model_inputs")

    existing = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if existing != rendered:
        if check:
            print(f"gen_model_inputs: {OUT.relative_to(ROOT)} is out of date")
            sys.exit("gen_model_inputs: generated file is stale; run tools/gen_model_inputs.py")
        OUT.write_text(rendered, encoding="utf-8")
        print(f"gen_model_inputs: wrote {OUT.relative_to(ROOT)}")

    print(
        f"gen_model_inputs: {len(rows)} of {len(palette)} palette entries name a model"
        + (f"; no model: {', '.join(unmodelled)}" if unmodelled else "")
        + (", generated file up to date" if check else "")
    )


if __name__ == "__main__":
    main()
