#!/usr/bin/env python3
"""Generate the promises the kernels' own checks make, so that Lean holds them.

`docs/src/calculus/numerics.md` requires a partial function to be total, clamped or deliberately
`NaN`, and the code states which at the call site. Eleven of those statements are guarded: a
check above the arithmetic makes the domain condition hold. Nothing read the sentence, so it is
the class of claim this repository makes that no mechanism held.

`tools/guards.py` is the reader - it derives each guard's hypotheses from the spec's own
`severity = "error"` rows, so deleting a bound makes the proof fail, and takes the conclusion and
the proof from `lean/guards.toml`, because which bound discharges which expression is the one
thing neither the spec nor the source can be read for.

Two files, both wholly generated:

    lean/Azoth/Guards.lean      one theorem per `owner = "lean"` guard
    lean/Azoth/GuardGate.lean   one `#print axioms` per theorem, so the axiom gate covers them

A new gate file rather than a line in `Axioms.lean`, which is hand-written and whose own docstring
says a theorem it does not name is a theorem nothing gates - a hand-maintained list of guard
theorems would go stale exactly that way. And not `Gate.lean`, which `gen_vocabulary.py` owns: a
second writer is the drift `gen_model_inputs.py` was split out of `gen_models.py` to avoid.

    python tools/gen_guard_theorems.py            # write
    python tools/gen_guard_theorems.py --check    # fail if the tree is not what this emits
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import guards

ROOT = Path(__file__).resolve().parent.parent
THEOREMS = ROOT / "lean" / "Azoth" / "Guards.lean"
GATE = ROOT / "lean" / "Azoth" / "GuardGate.lean"

THEOREM_BANNER = """-- GENERATED FILE - DO NOT EDIT BY HAND.
--
-- Generated by `tools/gen_guard_theorems.py` from `lean/guards.toml` and the specs.
--
-- Each theorem says one thing: the checks the site performs discharge the domain condition its
-- arithmetic needs. The hypotheses are the spec's own `severity = "error"` rows, so deleting a
-- bound makes the proof fail; the condition and the proof are declared in the manifest.
--
-- **The hypotheses are the checks the site performs, not the ones the conclusion happens to
-- need.** An unused hypothesis is kept, and the linter silenced below, because removing a check
-- the site performs has to be visible in the statement.
"""

GATE_BANNER = """-- GENERATED FILE - DO NOT EDIT BY HAND.
--
-- Generated by `tools/gen_guard_theorems.py` from `lean/guards.toml`.
--
-- One `#print axioms` per guard theorem, so the gate covers every guard rather than the ones
-- somebody remembered. Run by `tools/check_lean_axioms.py`.
"""

LINTER = """
-- The hypotheses are the site's checks; a conclusion uses the ones it needs.
set_option linter.unusedVariables false
"""


def emit_theorems() -> str:
    """`Guards.lean`: one theorem per `owner = "lean"` guard, in key order."""
    guards_list, _ = guards.manifest()
    specs = guards.specs()
    body = []
    for guard in sorted(guards_list, key=lambda entry: entry.key):
        if guard.owner != "lean":
            continue
        spec = specs.get(guard.spec or "")
        if spec is None:
            sys.exit(
                f"gen_guard_theorems: {guard.key} names the spec {guard.spec!r}, "
                "which is not in specs/"
            )
        body.append(guards.theorem(guard, spec))
    return (
        THEOREM_BANNER
        + "\nimport Mathlib.Tactic\n"
        + LINTER
        + "\nnamespace Azoth.Guards\n\n"
        + "\n".join(body)
        + "\nend Azoth.Guards\n"
    )


def emit_gate() -> str:
    """`GuardGate.lean`: the `#print axioms` line for each theorem, in key order."""
    guards_list, _ = guards.manifest()
    lines = [
        f"#print axioms Azoth.Guards.{guard.name}"
        for guard in sorted(guards_list, key=lambda entry: entry.key)
        if guard.owner == "lean"
    ]
    return GATE_BANNER + "\nimport Azoth.Guards\n\n" + "\n".join(lines) + "\n"


def main() -> None:
    check = "--check" in sys.argv
    rendered = {THEOREMS: emit_theorems(), GATE: emit_gate()}
    if check:
        stale = [
            path.relative_to(ROOT)
            for path, text in rendered.items()
            if (path.read_text(encoding="utf-8") if path.exists() else None) != text
        ]
        if stale:
            sys.exit(
                "gen_guard_theorems: out of date - run tools/gen_guard_theorems.py: "
                + ", ".join(str(path) for path in stale)
            )
        print("gen_guard_theorems: both files are current")
        return
    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8")
        print(f"gen_guard_theorems: wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
