#!/usr/bin/env python3
"""Generate the model-input table the palette's entries are keyed by.

`gen_models.py` compiles a model's bounds and its cases into Rust and **drops its inputs**: a
bound names its quantity by string and a case names its values by position, so neither needs the
declaration. The names, the kinds (`quantity`, `vector`, `boolean`, `enum`, `components`) and the
`optional` flags therefore exist only in the spec file - and a front-end that renders a unit
operation's form cannot choose a widget without the kind. `Param` in the palette carries a unit
and no type, which is the gap this table fills.

Kept out of `gen_models.py` on purpose: that generator owns `model_gen.rs` and the Python mirror
of the same table, and a second concern in it would mean a change here regenerating files a
change there also writes.

    python tools/gen_model_inputs.py            # write
    python tools/gen_model_inputs.py --check    # fail if the tree is not what this emits
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from vocabulary_table import dimension_of, load_vocabulary

ROOT = Path(__file__).resolve().parent.parent
PALETTE_DIR = ROOT / "specs" / "unit_ops"
MODEL_DIR = ROOT / "specs" / "models" / "process"
VOCABULARY = ROOT / "specs" / "vocabulary" / "vocabulary.toml"
OUT = ROOT / "crates" / "azoth-process" / "src" / "model_inputs_gen.rs"

#: The same table as Lean data, with one theorem over it. **Not a second copy of the
#: vocabulary**: `gen_vocabulary.py` owns the unit-to-dimension map and this reads it, so the
#: theorem is what holds this generator's reading to that table rather than restating it.
LEAN_OUT = ROOT / "lean" / "Azoth" / "Inputs.lean"

#: A palette id and the model id it names. The rule, not a table: `unit_ops.pump` is
#: `process.pump`, and an entry whose model is not named this way has no model.
PALETTE_PREFIX = "unit_ops."
MODEL_PREFIX = "process."


def load_palette() -> list[dict[str, Any]]:
    """Every palette entry, in path order with its own path recorded."""
    entries = []
    for path in sorted(PALETTE_DIR.rglob("*.toml")):
        spec = tomllib.loads(path.read_text(encoding="utf-8"))
        spec["_path"] = path.relative_to(ROOT)
        entries.append(spec)
    if not entries:
        sys.exit(f"gen_model_inputs: no palette entries under {PALETTE_DIR}")
    return entries


def load_models() -> dict[str, dict[str, Any]]:
    """Every process model, by id, with its own path recorded."""
    models: dict[str, dict[str, Any]] = {}
    for path in sorted(MODEL_DIR.glob("*.toml")):
        spec = tomllib.loads(path.read_text(encoding="utf-8"))
        spec["_path"] = path.relative_to(ROOT)
        models[spec["id"]] = spec
    if not models:
        sys.exit(f"gen_model_inputs: no models under {MODEL_DIR}")
    return models


def model_id_for(palette_id: str) -> str:
    return MODEL_PREFIX + palette_id.removeprefix(PALETTE_PREFIX)


def rust_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def emit_rust(
    rows: list[tuple[dict[str, Any], dict[str, Any]]], palette: list[dict[str, Any]]
) -> str:
    """The input table, and the two accessors a caller needs."""
    listed = "".join(f"//!   - {entry['_path']}\n" for entry in palette)
    banner = (
        "//! GENERATED FILE - DO NOT EDIT BY HAND.\n//!\n"
        "//! Generated by `tools/gen_model_inputs.py` from:\n"
        f"{listed}"
        "//!\n"
        "//! Regenerate with `python tools/gen_model_inputs.py`; CI runs `--check` and\n"
        "//! fails on any difference.\n\n"
        "/// One input a model declares, as the spec declares it.\n"
        "///\n"
        "/// **The declaration `gen_models.py` drops.** A model's bounds and cases are compiled\n"
        "/// into `model_gen`, and neither carries the input's own name, so the kind a form\n"
        "/// chooses a widget from exists only in the spec file this table is generated from.\n"
        "pub struct ModelInput {\n"
        "    /// The input's name in the spec, e.g. `outlet_pressure`.\n"
        "    pub name: &'static str,\n"
        "    /// The spec's `type`, or `quantity` where it carries none.\n"
        "    pub kind: &'static str,\n"
        "    /// An `enum`'s allowed values, in the spec's order; empty for every other kind.\n"
        "    pub values: &'static [&'static str],\n"
        "    /// Whether the spec marks the input `optional = true`.\n"
        "    pub optional: bool,\n"
        "    /// The dimension the spec's `unit` carries, or `None` where the input has no\n"
        "    /// unit: a boolean, an enum, a substance list, or a matrix.\n"
        "    ///\n"
        "    /// **The declaration and the arithmetic meet here.** A spec states an input's\n"
        "    /// unit and the implementation takes a typed quantity, and before this field\n"
        "    /// the two were compared by nothing - so `an_input_of_the_wrong_dimension` in\n"
        "    /// this table's own test is what says they agree, input by input.\n"
        "    pub dimension: Option<&'static str>,\n"
        "}\n\n"
        "/// The inputs one palette entry's model declares.\n"
        "pub struct ModelInputs {\n"
        "    /// The palette id, e.g. `unit_ops.compressor`.\n"
        "    pub unit_op: &'static str,\n"
        "    /// The model id, e.g. `process.compressor`.\n"
        "    pub model: &'static str,\n"
        "    /// The declared inputs, in the spec's order.\n"
        "    pub inputs: &'static [ModelInput],\n"
        "}\n\n"
        "static ALL: &[ModelInputs] = &[\n"
    )

    vocabulary = load_vocabulary()
    rows_text = []
    for palette_entry, model in rows:
        inputs = "".join(
            "            ModelInput {{ name: {}, kind: {}, values: &[{}],"
            " optional: {}, dimension: {} }},\n".format(
                rust_str(name),
                rust_str(declaration.get("type", "quantity")),
                ", ".join(rust_str(value) for value in declaration.get("values", [])),
                "true" if declaration.get("optional") else "false",
                dimension_text(
                    dimension_of(
                        declaration.get("unit"),
                        vocabulary,
                        f"{model['id']}.{name}",
                    )
                ),
            )
            for name, declaration in model.get("inputs", {}).items()
        )
        rows_text.append(
            "    ModelInputs {{\n"
            "        unit_op: {},\n"
            "        model: {},\n"
            "        inputs: &[\n"
            "{}"
            "        ],\n"
            "    }},\n".format(rust_str(palette_entry["id"]), rust_str(model["id"]), inputs)
        )

    return (
        banner + "".join(rows_text) + "];\n\n"
        "/// Every palette entry that names a model, in palette-id order.\n"
        "#[must_use]\n"
        "pub fn model_inputs() -> &'static [ModelInputs] {\n"
        "    ALL\n"
        "}\n\n"
        "/// One entry's model inputs, or `None` for an entry with no model.\n"
        "///\n"
        "/// One of the twenty-nine is in that state and `executor::dispatch::UNRUNNABLE` names\n"
        "/// it, so `None` here and a refusal there are the same fact stated twice.\n"
        "#[must_use]\n"
        "pub fn inputs_for(unit_op: &str) -> Option<&'static ModelInputs> {\n"
        "    ALL.iter().find(|entry| entry.unit_op == unit_op)\n"
        "}\n"
    )


def dimension_text(dimension: str | None) -> str:
    """A dimension as a Rust expression: `Some("pressure")`, or `None`."""
    return f"Some({rust_str(dimension)})" if dimension else "None"



def dimension_exponents() -> dict[str, list[int]]:
    """Every dimension's exponents, by name, from the vocabulary table.

    The Lean side writes a dimension as `Dim.ofExponents [...]`, which is the vocabulary's own
    form - so this reads the table rather than the `dimension:` name an input declaration
    carries.
    """
    table = tomllib.loads(VOCABULARY.read_text(encoding="utf-8"))
    return {dimension["id"]: dimension["exponents"] for dimension in table["dimensions"]}


def emit_lean(rows: list[tuple[dict[str, Any], dict[str, Any]]]) -> str:
    """The input table as Lean data, and the theorem that holds it to the vocabulary.

    **Why a theorem, when both sides are generated.** The dimension here and
    `Azoth.Vocabulary.dimOf` are two derivations from one table - this generator's and
    `gen_vocabulary.py`'s - so a bug in this one (the wrong exponents, a unit resolved to
    another dimension) is a *difference between two artefacts* rather than a contradiction
    inside one. `decide` closes the theorem only when the two agree, and the row count is
    emitted so a generator that wrote no rows is visible rather than proving over nothing.
    """
    vocabulary = load_vocabulary()
    exponents = dimension_exponents()
    out = [
        "-- GENERATED FILE - DO NOT EDIT BY HAND.",
        "--",
        "-- Generated by `tools/gen_model_inputs.py` from the palette's specs.",
        "--",
        "-- One entry per model input that declares a unit, with the dimension this",
        "-- generator read out of `specs/vocabulary/vocabulary.toml` for it. The theorem",
        "-- is what holds that reading to `Azoth.Vocabulary.dimOf`.",
        "",
        "import Azoth.Vocabulary",
        "",
        "namespace Azoth.Inputs",
        "",
        "open Units (Dimension)",
        "",
        "-- The table is one literal per input and the theorem computes over all of them, which",
        "-- is more than the default budgets allow - measured, the `rows` list alone exhausts",
        "-- 200,000 heartbeats and a `decide` over it the recursion depth. Raised rather than",
        "-- split: the work is real and bounded by the palette.",
        "set_option maxHeartbeats 4000000 in",
        "set_option maxRecDepth 100000 in",
        "/-- Every model input that declares a unit: `(palette id, input, unit, exponents)`.",
        "",
        "The exponents are the ones this generator read out of the vocabulary for that unit,",
        "written as the integers `Azoth.Vocabulary.exponents` carries - not as a `Dimension`,",
        "whose equality is not computable and would make the theorem below unprovable by",
        "computation. -/",
        "def rows : List (String × String × String × List Int) :=",
        "  [",
    ]
    for palette_entry, model in rows:
        for name, declaration in model.get("inputs", {}).items():
            dimension = dimension_of(
                declaration.get("unit"), vocabulary, f"{model['id']}.{name}"
            )
            if dimension is None:
                continue
            vector = ", ".join(str(value) for value in exponents[dimension])
            out.append(
                f'    ("{palette_entry["id"]}", "{name}", "{declaration["unit"]}", '
                f"[{vector}]),"
            )
    out += [
        "  ]",
        "",
        "/-- The number of rows, so a generator that emitted nothing is a difference rather",
        "than a theorem about no inputs. -/",
        "def rowCount : Nat := rows.length",
        "",
        "set_option maxHeartbeats 4000000 in",
        "set_option maxRecDepth 100000 in",
        "/-- **Every input's dimension is the dimension of its own unit.**",
        "",
        "The input table says what `tools/gen_model_inputs.py` read; `exponentsOf` says what",
        "`gen_vocabulary.py` wrote. A row whose exponents disagreed with its unit's - a unit",
        "resolved to another dimension, exponents read against the wrong row - makes `decide`",
        "fail to close this rather than passing on a name that happens to match. -/",
        "theorem every_input_dimension_is_its_units :",
        "    rows.all (fun row => decide (row.2.2.2 = Azoth.Vocabulary.exponentsOf row.2.2.1))",
        "      = true :=",
        "  by decide",
        "",
        "end Azoth.Inputs",
        "",
    ]
    return "\n".join(out)

def format_rust(text: str, generator: str) -> str:
    """Run the emitted Rust through rustfmt, which every generated file is compared against.

    **A missing rustfmt is a refusal rather than a fallback**, where `gen_vocabulary.py` emits
    unformatted source and lets `cargo fmt --check` catch it. That fallback cannot work here: these
    generators are checked by comparing their output to the *committed* file, so emitting
    unformatted text would report the file as stale and send a reader looking for a drift that is
    not there. The toolchain is the prerequisite, and the message says so.
    """
    try:
        proc = subprocess.run(
            ["rustfmt", "--edition", "2024"],
            input=text,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        sys.exit(
            f"{generator}: rustfmt is not on PATH, and the generated file is compared against "
            f"rustfmt's own output - install the Rust toolchain"
        )
    if proc.returncode != 0:
        sys.exit(f"{generator}: rustfmt refused the output:\n{proc.stderr}")
    return proc.stdout


def main() -> None:
    check = "--check" in sys.argv
    palette = load_palette()
    models = load_models()

    rows: list[tuple[dict[str, Any], dict[str, Any]]] = []
    unmodelled: list[str] = []
    for entry in palette:
        model = models.get(model_id_for(entry["id"]))
        if model is None:
            unmodelled.append(entry["id"])
            continue
        rows.append((entry, model))
    rows.sort(key=lambda row: row[0]["id"])

    # A model no palette entry can reach is a spec nothing runs, which is a defect rather than
    # a curiosity - so it stops the generator rather than being left out of the table.
    claimed = {model_id_for(entry["id"]) for entry in palette}
    orphans = sorted(set(models) - claimed)
    if orphans:
        sys.exit(
            "gen_model_inputs: these models are named by no palette entry, so nothing can run "
            f"them: {', '.join(orphans)}"
        )

    rendered = format_rust(emit_rust(rows, palette), "gen_model_inputs")

    lean = emit_lean(rows)

    stale = []
    for path, content in ((OUT, rendered), (LEAN_OUT, lean)):
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == content:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
            continue
        path.write_text(content, encoding="utf-8")
        print(f"gen_model_inputs: wrote {path.relative_to(ROOT)}")
    if stale:
        print(f"gen_model_inputs: {', '.join(stale)} is out of date")
        sys.exit("gen_model_inputs: generated file is stale; run tools/gen_model_inputs.py")

    print(
        f"gen_model_inputs: {len(rows)} of {len(palette)} palette entries name a model"
        + (f"; no model: {', '.join(unmodelled)}" if unmodelled else "")
        + (", generated file up to date" if check else "")
    )


if __name__ == "__main__":
    main()
