#!/usr/bin/env python3
"""Derive `databank/keycard.toml` (the baseline card) from the compiled component data.

    python tools/gen_keycard.py --check

The baseline card is azoth's shipped data - the components a cubic reads (`Tc`, `Pc`,
`omega`) and the Peng-Robinson interaction parameters - stated in exactly the format a
user's keycard takes. It is derived from `data/components/components.csv` and
`kij.csv`, which are themselves derived from NeqSim's `COMP.csv` and `INTER.csv`, so the
library's data and a user's data are one object: a card.

The component parameters are read from `specs/schema/component.schema.json` and the
association's from `specs/schema/association.schema.json`, the single declarations of what
a card may state and the compiled column each comes from. This file does not re-list them.
The interaction parameter is `kij_pr`, the one a cubic's classical mixing rule reads; the
card's `value` for a pair is that column.

**The association's fitted values are converted on the way out.** The compiled table
carries NeqSim's internal scale for `acpa_*` and `bcpa_*`; the card format states them in
SI, as it states every other parameter. So this is the direction of the crossing that
`azoth_eos::databank::AssociationOverride::applied_to` makes back.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "specs" / "schema" / "component.schema.json"
ASSOCIATION_SCHEMA = ROOT / "specs" / "schema" / "association.schema.json"
COMPONENTS_CSV = ROOT / "data" / "components" / "components.csv"
KIJ_CSV = ROOT / "data" / "components" / "kij.csv"
OUT = ROOT / "databank" / "keycard.toml"

#: The compiled columns that carry NeqSim's internal scale, and the factor to SI -
#: `Component.java:526-531`. Named here rather than by "every column beginning `a`" because
#: the association's energy and bounding volume are *not* in that scale, and a rule that
#: inferred the scale from the value would be the defect it is meant to prevent.
INTERNAL_COLUMNS = frozenset({"acpa_srk", "bcpa_srk", "acpa_pr", "bcpa_pr"})
NEQSIM_INTERNAL_TO_SI = 1.0e-5

BANNER = """\
# databank/keycard.toml - azoth's shipped data, as a keycard.
#
# Generated by tools/gen_keycard.py from data/components/. Do not edit by hand.
# The values are NeqSim master's (Equinor/NTNU, Apache-2.0), the same source
# databank/manifest.toml names; see NOTICE for the attribution. That page carries the
# commit, because the version alone names both the release tag and master.
#
# The fitted association values in the `associations` sections are stated in SI -
# `Pa*m**6/mol**2` and `m**3/mol` - as every parameter in this format is. The table
# they are generated from carries NeqSim's own scale for those two columns only.
"""


def parameters(schema_path: Path = SCHEMA) -> list[tuple[str, str, str]]:
    """The (card name, compiled column, unit) triples, from a single declaration.

    One function for both schemas, because they declare the same three things per
    parameter - a name, a canonical unit and the compiled column - and a second reader
    would be a second place the shape is written down.
    """
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    return [
        (name, props["x-azoth-column"], props["x-azoth-unit"])
        for name, props in schema["properties"].items()
        # `scheme` is a name from a closed vocabulary and not a number in a unit, so it has
        # no column and no unit to convert to. The card states it as written.
        if "x-azoth-column" in props
        # **`ion` has a column and no unit**, because it is a class rather than a
        # parameter: the card states `true` or `false`, and there is nothing to convert.
        # The baseline card carries the compiled table, so it has no ion to state either -
        # an ion is not a cubic component, which is what this file is a subset of.
        and "x-azoth-unit" in props
    ]


def to_card_value(column: str, raw: str) -> str:
    """One compiled cell as the card states it, converting the internal scale.

    A converted number is written as Python's shortest round-trip repr rather than by
    formatting, so the value is the same float a reader resolves it back to. Ten thousand
    copies of a rounding error would be a card whose values are not the table's.

    **A blank cell is a zero**, which is the rule both readers apply to the same table and
    the reason this is not a passthrough: the two blanks in the compiled table are
    `associationboundingvolume_pr` on `h2so4` and `hno3`, whose every sibling association
    cell is already `0.0`. A card cannot carry a blank - TOML has no value for one - so a
    generator that passed it through would emit a file no reader can parse.
    """
    if not raw.strip():
        return "0.0"
    if column in INTERNAL_COLUMNS:
        return repr(float(raw) * NEQSIM_INTERNAL_TO_SI)
    return raw


def toml_key(key: str) -> str:
    """A TOML key, quoted only where a bare key would not parse.

    Component names carry spaces (`acetic acid`) and dots (`1.2-dm-cyc5`), neither of
    which a bare key admits. A JSON string is a TOML basic string, so `json.dumps` is
    the quoter for both the key and the escape rules.
    """
    if key and all(ch.isalnum() or ch in "_-" for ch in key):
        return key
    return json.dumps(key)


def render() -> str:
    parts = [BANNER, "schema_version = 2\n"]
    params = parameters()

    rows = list(csv.DictReader(COMPONENTS_CSV.read_text(encoding="utf-8").splitlines()))
    rows.sort(key=lambda r: r["name"])
    for row in rows:
        name = toml_key(row["name"])
        for card, column, unit in params:
            value = to_card_value(column, row[column])
            parts.append(
                f"\n[components.{name}.{card}]\nvalue = {value}\nunit = {json.dumps(unit)}\n"
            )

    # The association, one section per associating component. The scheme is written as the
    # table spells it, and it has to be written at all: it is what says whether the
    # substance associates, and a card carrying only the numbers beside it would be one
    # whose values are read by nothing.
    associations = parameters(ASSOCIATION_SCHEMA)
    for row in rows:
        scheme = row["associationscheme"].strip()
        if scheme in ("", "0"):
            continue
        name = toml_key(row["name"])
        parts.append(f"\n[associations.{name}]\nscheme = {json.dumps(scheme)}\n")
        for card, column, unit in associations:
            value = to_card_value(column, row[column])
            parts.append(
                f"\n[associations.{name}.{card}]\nvalue = {value}\nunit = {json.dumps(unit)}\n"
            )

    kij = list(csv.DictReader(KIJ_CSV.read_text(encoding="utf-8").splitlines()))
    # A self-pair (`n-butane` with `n-butane`) is NeqSim's own diagonal, which the
    # databank loader carries but never reads - the kij matrix's diagonal is zero by
    # construction. The card format refuses one, so it is left out here rather than
    # shipped as a value the loader would reject.
    kij = [r for r in kij if r["component_a"] != r["component_b"]]
    kij.sort(key=lambda r: (r["component_a"], r["component_b"]))
    for row in kij:
        # The associating columns only where the table has one: a stated zero would be a
        # card overriding a pair back to ideal mixing, which is a claim, and the table's
        # own zero is already the default.
        associating = "".join(
            f"{card} = {row[column]}\n"
            for card, column in (("cpa_value_srk", "cpakij_srk"), ("cpa_value_pr", "cpakij_pr"))
            if float(row[column]) != 0.0
        )
        parts.append(
            f"\n[[kij]]\n"
            f"component_a = {json.dumps(row['component_a'])}\n"
            f"component_b = {json.dumps(row['component_b'])}\n"
            f"value = {row['kij_pr']}\n"
            f"{associating}"
        )

    return "".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report drift; write nothing")
    args = parser.parse_args(argv)

    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print(f"gen_keycard: {OUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        print(f"gen_keycard: {OUT.relative_to(ROOT)} up to date")
        return 0

    OUT.write_text(text, encoding="utf-8")
    print(f"gen_keycard: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
