#!/usr/bin/env python3
"""Generate the type stub for the compiled extension.

`python/src/azoth/_core.pyi` is what a type checker reads in place of `azoth._core`,
which does not exist until the bindings are built. The result classes come from the
result dataclasses in `azoth.core.result`, which the Rust transport types are asserted
to match field for field; the signatures come from the specs' declared inputs, which
both implementations are held to.

The vocabulary below is data in this file rather than in the stub, because it mirrors
Rust types a new calculation does not change - a `cdylib` has nothing to introspect -
and `test_the_stub_matches_the_rust_transport_types` holds it to the Rust source.

Usage:
    python tools/gen_stub.py            # write the file
    python tools/gen_stub.py --check    # fail if it is out of date
"""

from __future__ import annotations

import argparse
import dataclasses
import sys
from pathlib import Path
from typing import Any, get_args, get_origin, get_type_hints

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "python" / "src"))

from azoth._dispatch import result_type  # noqa: E402
from azoth._models_gen import MODELS  # noqa: E402
from azoth._registry_gen import CALCS  # noqa: E402

#: The model ids, so a spec can be told from a calc spec by more than a flag. A model's
#: extension signature is the transport shape; a calc's is its declared inputs.
MODEL_IDS = frozenset(model["id"] for model in MODELS)

#: The models whose mixture transport carries the per-component molar mass beside the
#: critical constants. A model that resolves names against the databank gets the mass
#: for free; the stub has to say it does, or the bridge's extra vector would be a
#: signature mismatch.
MOLAR_MASS_MODELS = frozenset({"eos.viscosity", "eos.thermal_conductivity"})

STUB = ROOT / "python" / "src" / "azoth" / "_core.pyi"

DOCSTRING = """Type stub for the compiled extension.

Generated by `tools/gen_stub.py` from the result dataclasses and the specs. Do
not edit by hand: the result classes below are what `azoth.core.result` says, the
signatures are what the specs declare, and both are already asserted equal to the
Rust side by tests.

Nothing here is part of the public API. `azoth.hydraulics` is, and it returns the
result dataclasses in `azoth.core.result` rather than the transport types below -
see `azoth._rust_bridge`.
"""

#: The types that cross the boundary but are not results. `(name, docstring, fields)`,
#: where a field is `(name, type)`. Mirrors the `#[pyclass]` structs in
#: `crates/azoth-python/src/data.rs` and `results.rs`.
VOCABULARY: tuple[tuple[str, str | None, tuple[tuple[str, str], ...]], ...] = (
    ("DataFile", None, (("name", "str"), ("path", "str"), ("text", "str"))),
    (
        "FittingRow",
        None,
        (
            ("id", "str"),
            ("family", "str"),
            ("name", "str"),
            ("n_ld", "float"),
            ("f_t_basis", "str"),
            ("citation", "str"),
            ("verify_status", "str"),
        ),
    ),
    (
        "FluidRow",
        None,
        (
            ("fluid", "str"),
            ("temperature_c", "float"),
            ("density_kg_m3", "float"),
            ("dynamic_viscosity_pa_s", "float"),
            ("citation", "str"),
            ("verify_status", "str"),
        ),
    ),
    (
        "ComponentRow",
        "One row of the component databank, as the Rust core parsed it.",
        (
            ("name", "str"),
            ("tc_k", "float"),
            ("pc_pa", "float"),
            ("acentric_factor", "float"),
            # Optional because the row shape is also what an overlay reports, and a
            # substance a keycard adds has no polynomial. Every row of the shipped
            # table has all five.
            ("cp_a", "float | None"),
            ("cp_b", "float | None"),
            ("cp_c", "float | None"),
            ("cp_d", "float | None"),
            ("cp_e", "float | None"),
        ),
    ),
    (
        "KijRow",
        "One row of the interaction table, as the Rust core parsed it.",
        (("component_a", "str"), ("component_b", "str"), ("kij_pr", "float")),
    ),
    (
        "Overlay",
        "A keycard's sections, as the extension reads them. Built either entry by entry "
        "from the values `azoth.keycard` resolved to or by reading a card's text with "
        "`card_overlay`, and opaque: what it resolves to is read through "
        "`overlay_entry_row` and its siblings.",
        (),
    ),
    (
        "Qty",
        "A physical quantity: always SI magnitude, plus a canonical unit label.",
        (("magnitude_si", "float"), ("unit", "str")),
    ),
    (
        "Warning",
        "A warning, transported. `code` is the SCREAMING_SNAKE_CASE string.",
        (("code", "str"), ("message", "str"), ("field", "str | None")),
    ),
    (
        "BatchColumn",
        None,
        (
            ("name", "str"),
            ("unit", "str"),
            ("values", "list[float] | None"),
            ("labels", "list[str | None] | None"),
        ),
    ),
    ("BatchResult", None, (("columns", "list[BatchColumn]"), ("warnings", "list[list[Warning]]"))),
    (
        "KComponent",
        "One fitting's contribution to the total resistance coefficient.",
        (("fitting_id", "str"), ("n_ld", "float"), ("k", "float")),
    ),
    (
        "Stream",
        "A material stream: composition, molar flow, pressure, temperature and molar "
        "enthalpy. All SI magnitudes - `p` in pascals, `t` in kelvin, `h` in J/mol, "
        "`n` in mol/s.",
        (
            ("components", "list[str]"),
            ("z", "list[float]"),
            ("n", "float"),
            ("p", "float"),
            ("t", "float"),
            ("h", "float"),
        ),
    ),
)

#: Functions the extension exports that are not a calculation. `(signature, return)`.
INTROSPECTION: tuple[tuple[str, str], ...] = (
    ("batch_run(calc_id: str, inputs: dict[str, list[float]])", "BatchResult"),
    ("data_files()", "list[DataFile]"),
    ("fittings_rows()", "list[FittingRow]"),
    ("fluid_rows(name: str)", "list[FluidRow]"),
    ("component_rows()", "list[ComponentRow]"),
    ("kij_rows()", "list[KijRow]"),
    (
        "overlay(components: list[tuple[str, float | None, float | None, float | None]],"
        " kij: list[tuple[str, str, float]])",
        "Overlay",
    ),
    ("card_overlay(text: str)", "Overlay"),
    ("overlay_entry_row(name: str, overlay: Overlay)", "ComponentRow"),
    ("overlay_component_rows(overlay: Overlay)", "list[ComponentRow]"),
    ("overlay_kij_rows(overlay: Overlay)", "list[tuple[str, str, float]]"),
    ("warning_codes()", "list[str]"),
    ("unit_names()", "list[str]"),
    ("solver_kinds()", "list[str]"),
    ("model_ids()", "list[str]"),
    ("model_schemes(model_id: str)", "list[str]"),
    ("model_kind(model_id: str)", "str"),
    ("result_fields(calc_id: str)", "list[str]"),
    ("calc_ids()", "list[str]"),
    ("version()", "str"),
    # The process layer: a stream value and the unit-operation kernels, plus the
    # flowsheet checker.
    ("splitter(feed: Stream, fractions: list[float])", "list[Stream]"),
    ("mixer(inlets: list[Stream], outlet_pressure: float | None = ...)", "Stream"),
    ("separator(feed: Stream, temperature: float)", "tuple[Stream, Stream]"),
    ("throttling_valve(feed: Stream, outlet_pressure: float)", "Stream"),
    ("heat_exchanger(hot: Stream, cold: Stream, duty: float)", "tuple[Stream, Stream]"),
    ("pump(feed: Stream, outlet_pressure: float, efficiency: float)", "Stream"),
    ("validate_flowsheet(flowsheet: str, palette_dir: str)", "list[str]"),
)

#: The exception hierarchy, re-exported from `azoth.core.errors` so both backends raise
#: the same class objects rather than two lookalike hierarchies.
EXCEPTIONS: tuple[tuple[str, str], ...] = (
    ("AzothError", "Exception"),
    ("InvalidInputError", "AzothError, ValueError"),
    ("OutOfRangeError", "AzothError, ValueError"),
    ("PropertyUnavailableError", "AzothError, LookupError"),
    ("SolverNotConvergedError", "AzothError, RuntimeError"),
    ("UnitMismatchError", "AzothError, TypeError"),
    ("UnknownFittingError", "AzothError, LookupError"),
)

#: How a Python result field's type is spelled in the stub.
#:
#: `Q` becomes `Qty` because that is what crosses the boundary; an enum becomes `str`
#: because the bridge rebuilds it. A `tuple[X, ...]` is a `list[X]` on the Rust side, so
#: the stub says `list` - the shape a caller gets, not the shape the dataclass stores.
SCALARS = {"float": "float", "int": "int", "bool": "bool", "str": "str", "Q": "Qty"}
ENUMS = {"Phase", "RootStructure", "StabilityVerdict", "FlowRegime"}


def stub_type(annotation: Any) -> str:
    """How one result field's type is spelled in the stub."""
    if annotation is None or annotation is type(None):
        return "None"
    name = getattr(annotation, "__name__", None)
    if name in SCALARS:
        return SCALARS[name]
    if name in ENUMS:
        return "str"

    origin = get_origin(annotation)
    if origin in (tuple, list, set):
        args = get_args(annotation)
        return f"list[{stub_type(args[0] if args else Any)}]"

    if type(annotation).__name__ == "UnionType":
        parts = get_args(annotation)
        rendered = stub_type(next(part for part in parts if part is not type(None)))
        if any(part is type(None) for part in parts):
            return f"{rendered} | None"
        return rendered

    return str(getattr(annotation, "__name__", annotation))


def parameter_type(declaration: dict[str, Any]) -> str:
    """How one declared input is spelled in the stub."""
    kind = declaration.get("type", "quantity")
    if kind == "fitting_list":
        return "list[str]"
    if kind == "vector":
        return "list[float]"
    if kind == "matrix":
        return "list[list[float]]"
    if kind == "boolean":
        return "bool"
    if kind in ("enum", "string"):
        return "str"
    return "float"


def render_parameter(name: str, declaration: dict[str, Any]) -> str:
    base = parameter_type(declaration)
    if declaration.get("optional", False):
        return f"{name}: {base} | None = None"
    return f"{name}: {base}"


def render_result_class(calc_id: str) -> str:
    """One `@final class <Name>Result:` block."""
    resolved = result_type(calc_id)
    hints = get_type_hints(resolved)
    out = ["@final", f"class {resolved.__name__}:"]
    for field in dataclasses.fields(resolved):
        out.append(f"    {field.name}: {stub_type(hints[field.name])}")
    if len(out) == 2:
        out.append("    ...")
    return "\n".join(out)


def transport_parameters(model: dict[str, Any]) -> list[str]:
    """The arguments a model's extension function takes, in the transport vocabulary.

    **Not the spec's declared inputs.** A calc's function takes the scalars its spec
    declares, so for a calc the two are the same. A model's takes *objects* - a
    `Mixture` and, where an enthalpy is involved, an `IdealGasModel` - and a `cdylib`
    has nothing to hold one in, so `_rust_bridge` flattens the mixture into four
    vectors and the ideal-gas model into five before it crosses. The stub describes
    the extension, so it has to describe that, not the spec.

    Which objects is a fact about the implementation's signature, so that is where
    this asks - the same question `python/tests/_helpers.py::parameters_of` asks, and
    for the same reason. A model that takes the critical constants themselves rather
    than a mixture (`eos.pure_saturation`) gets them as scalars, which is the same
    flattening with nothing to flatten.

    `components` is dropped: the resolved constants replace it, and a name list has
    no transport form of its own.
    """
    import importlib
    import inspect

    namespace, _, name = model["id"].partition(".")
    module = importlib.import_module(f"azoth.{namespace}")
    taken = set(inspect.signature(getattr(module, name)).parameters)

    params: list[str] = []
    if "components" in model["inputs"]:
        # A model that names a fluid resolves the names into a flattened mixture
        # (four vectors) or, for a pure-component model, the critical constants as
        # scalars. A model with no `components` input - one that takes per-component
        # vectors directly - has no such prefix to add.
        if "mixture" in taken:
            params += [
                "Tc: list[float]",
                "Pc: list[float]",
                "omega: list[float]",
                "kij: list[float]",
            ]
            if model["id"] in MOLAR_MASS_MODELS:
                params.append("molar_mass: list[float]")
        elif "coeffs" in taken:
            # A non-cubic reference EOS resolves the names into per-component coefficient
            # sets, flattened into the 32-coefficient `a` and the critical density.
            params += ["a: list[float]", "rhoc: list[float]"]
        elif "params" in taken:
            # An activity model resolves the names into a parameter set of its own
            # rather than a `Mixture`: critical constants are not what NRTL reads, so
            # the matrices cross flattened and the kernel rebuilds them by shape.
            params += ["alpha: list[float]", "dij: list[float]"]
        elif "components" in taken:
            # The EOS-CG mixture maps its own fixed component names, so the names cross
            # the boundary verbatim rather than as a flattened mixture.
            params.append("components: list[str]")
        else:
            params += ["Tc: float", "Pc: float", "omega: float"]
    if "ideal_gas" in taken:
        params += [f"{n}: list[float]" for n in ("cp_a", "cp_b", "cp_c", "cp_d", "cp_e")]
    for parameter, declaration in model["inputs"].items():
        if parameter == "components":
            continue
        params.append(render_parameter(parameter, declaration))
    if "hydrogen_type" in taken:
        # The hydrogen spin-isomer is a boundary-only choice carried as a string, not a
        # declared input: the spec names `T` and `P`, and the isomer is the caller's.
        params.append('hydrogen_type: str = "normal"')
    if "mixture" in taken:
        # The cubic and the alpha correlation the mixture is evaluated under, the two
        # boundary arguments the spec does not declare (they travel *inside* the
        # mixture, not beside it).
        params.append('eos: str = "pr"')
        params.append('alpha: str = "pr"')
        params.append("alpha_params: list[list[float]] | None = None")
    return params


def render_signature(entry: dict[str, Any]) -> str:
    """One `def <name>(...) -> <Name>Result: ...` block."""
    function = entry["id"].rpartition(".")[2]
    result_name = result_type(entry["id"]).__name__
    params = (
        transport_parameters(entry)
        if entry["id"] in MODEL_IDS
        else [render_parameter(name, d) for name, d in entry["inputs"].items()]
    )
    if not params:
        return f"def {function}() -> {result_name}: ..."
    single = f"def {function}({', '.join(params)}) -> {result_name}: ..."
    if len(single) <= 100:
        return single
    body = ",\n".join(f"    {param}" for param in params)
    return f"def {function}(\n{body},\n) -> {result_name}: ..."


def render_vocabulary() -> str:
    """The block of non-result types."""
    blocks = []
    for name, doc, fields in VOCABULARY:
        out = ["@final", f"class {name}:"]
        if doc:
            out.append(f'    """{doc}"""')
            out.append("")
        out.extend(f"    {field}: {annotation}" for field, annotation in fields)
        if name == "Qty":
            out.append("    def __init__(self, magnitude_si: float, unit: str) -> None: ...")
        if name == "Stream":
            out.append(
                "    def __init__(self, components: list[str], z: list[float], n: float,"
                " p: float, t: float) -> None: ..."
            )
            out.append("    @staticmethod")
            out.append(
                "    def from_ph(components: list[str], z: list[float], n: float, p: float,"
                " h: float) -> Stream: ..."
            )
        blocks.append("\n".join(out))
    return "\n\n".join(blocks)


def render() -> str:
    entries = sorted([*CALCS, *MODELS], key=lambda e: e["id"])
    classes = "\n\n".join(render_result_class(entry["id"]) for entry in entries)
    signatures = "\n".join(render_signature(entry) for entry in entries)
    introspection = "\n".join(
        f"def {signature} -> {result}: ..." for signature, result in INTROSPECTION
    )
    exceptions = "\n".join(f"class {name}({base}): ..." for name, base in EXCEPTIONS)

    return (
        f'"""{DOCSTRING}"""\n\n'
        "from typing import final\n\n"
        "# --- transport types ------------------------------------------------------\n"
        "# The values that cross the boundary and are not results. Hand-written here\n"
        "# because a `cdylib` has nothing to introspect; held to the Rust structs by\n"
        "# `test_the_stub_matches_the_rust_transport_types`.\n\n"
        f"{render_vocabulary()}\n\n"
        "# --- results --------------------------------------------------------------\n"
        "# Generated from the result dataclasses, so the stub and `azoth.core.result`\n"
        "# cannot disagree about a field.\n\n"
        f"{classes}\n\n"
        "# --- calculations ---------------------------------------------------------\n"
        "# All arguments and returns are SI magnitudes; unit handling happens once, in\n"
        "# Python, before the call crosses this boundary. See crates/azoth-python.\n\n"
        f"{signatures}\n\n"
        "# --- introspection --------------------------------------------------------\n\n"
        f"{introspection}\n\n"
        "# --- exceptions -----------------------------------------------------------\n"
        "# Re-exported from azoth.core.errors, so both backends raise the same class\n"
        "# objects rather than two lookalike hierarchies.\n\n"
        f"{exceptions}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    content = render()
    if args.check:
        current = STUB.read_text(encoding="utf-8") if STUB.exists() else ""
        if current != content:
            sys.exit(f"gen_stub: {STUB} is out of date - run `python tools/gen_stub.py`")
        print(f"gen_stub: {STUB} is up to date")
        return 0

    STUB.write_text(content, encoding="utf-8")
    print(f"gen_stub: wrote {STUB}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
