#!/usr/bin/env python3
"""Generate the extension's two id tables from the tree.

`crates/azoth-python/src/results.rs` carried two hand-maintained tables: `result_fields`, whose
194 arms map a calc id to its result's public field names, and `calc_ids`, the 73 ids of the
calculations this extension implements. **Both are derivable** - the first from the `impl
CalcResult` blocks, whatever `FIELDS` each declares, and the second from `specs/calcs/` - and
keeping them hand-written meant a new calculation cost an edit there besides its spec, its two
kernels and its test. `test_the_extension_registers_exactly_the_registry`'s failure message said
so in as many words.

The fields come from `rust_index` rather than from the spec's `outputs`, because they are the same
list only in the sense that `test_rust_index` holds them to each other; what the extension must
publish is what the Rust type declares.

    python tools/gen_python_registry.py            # write
    python tools/gen_python_registry.py --check    # fail if the tree is not what this emits
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rust_index

ROOT = Path(__file__).resolve().parent.parent
CALC_DIR = ROOT / "specs" / "calcs"
OUT = ROOT / "crates" / "azoth-python" / "src" / "registry_tables_gen.rs"


def calc_ids() -> list[str]:
    """The ids under `specs/calcs/`, sorted - the models ship through `model_ids` instead."""
    ids = [
        tomllib.loads(path.read_text(encoding="utf-8"))["id"]
        for path in sorted(CALC_DIR.rglob("*.toml"))
    ]
    if not ids:
        sys.exit(f"gen_python_registry: no calculations under {CALC_DIR}")
    return sorted(ids)


def emit() -> str:
    """The two tables, with the arms and ids in id order so the file is a stable diff."""
    rust_index.check()
    arms = "".join(
        f'        "{result.calc_id}" => {result.item_path}::FIELDS.to_vec(),\n'
        for result in rust_index.result_types()
    )
    ids = "".join(f'        "{calc_id}".to_string(),\n' for calc_id in calc_ids())
    return (
        "//! GENERATED FILE - DO NOT EDIT BY HAND.\n"
        "//!\n"
        "//! Generated by `tools/gen_python_registry.py` from:\n"
        "//!   - specs/calcs/**/*.toml and specs/models/**/*.toml, for the ids and the\n"
        "//!     set `result_fields` answers for\n"
        "//!   - the `impl CalcResult` blocks under `crates/*/src`, for the fields\n"
        "//!\n"
        "//! Regenerate with `python tools/gen_python_registry.py`; CI runs `--check`\n"
        "//! and fails on any difference.\n"
        "\n"
        "use azoth_core::CalcResult;\n"
        "use pyo3::prelude::*;\n"
        "\n"
        "/// The public field names of a calc's result, in declaration order.\n"
        "///\n"
        "/// Returns an empty list for an unknown id rather than raising: this is an\n"
        "/// introspection helper for tests and diagnostics, and a missing calc should\n"
        '/// read as "no fields" rather than as an error to handle.\n'
        "#[pyfunction]\n"
        "#[must_use]\n"
        "pub fn result_fields(calc_id: &str) -> Vec<String> {\n"
        "    match calc_id {\n"
        f"{arms}"
        "        _ => Vec::new(),\n"
        "    }\n"
        "    .into_iter()\n"
        "    .map(str::to_string)\n"
        "    .collect()\n"
        "}\n"
        "\n"
        "/// The calc ids this extension implements.\n"
        "#[pyfunction]\n"
        "#[must_use]\n"
        "pub fn calc_ids() -> Vec<String> {\n"
        "    vec![\n"
        f"{ids}"
        "    ]\n"
        "}\n"
    )


def format_rust(text: str) -> str:
    """Run the emitted Rust through rustfmt, which the committed file is compared against.

    A missing rustfmt is a refusal rather than a fallback: this file is checked by comparing
    generator output to the committed bytes, so unformatted text would report a drift that is not
    there.
    """
    try:
        proc = subprocess.run(
            ["rustfmt", "--edition", "2024"],
            input=text,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        sys.exit(
            "gen_python_registry: rustfmt is not on PATH, and the generated file is compared "
            "against rustfmt's own output - install the Rust toolchain"
        )
    if proc.returncode != 0:
        sys.exit(f"gen_python_registry: rustfmt refused the output:\n{proc.stderr}")
    return proc.stdout


def main() -> None:
    check = "--check" in sys.argv
    rendered = format_rust(emit())
    existing = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if existing == rendered:
        print(f"gen_python_registry: {OUT.relative_to(ROOT)} is current")
        return
    if check:
        sys.exit(
            f"gen_python_registry: {OUT.relative_to(ROOT)} is out of date; run "
            "tools/gen_python_registry.py"
        )
    OUT.write_text(rendered, encoding="utf-8")
    print(f"gen_python_registry: wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
