#!/usr/bin/env python3
"""Compile the palette into the crate, as the text it is written in.

A browser has no filesystem, so a wasm module cannot walk `specs/unit_ops/`. Embedding the 29
files with `include_str!` is the same thing the component databank, the reaction tables and the
ISO 6976 constants already do, and for the same reason: a build that carries its own data has no
second copy to disagree with the first.

**Embedded as text rather than as parsed specs**, so that `load_palette` and this bundle go
through the *one* loader. A generated `UnitOpSpec` table would be a second place the palette's
shape is declared, and the type would have to be reconstructible from a literal.

    python tools/gen_palette.py            # write
    python tools/gen_palette.py --check    # fail if the tree is not what this emits
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PALETTE_DIR = ROOT / "specs" / "unit_ops"
OUT = ROOT / "crates" / "azoth-process" / "src" / "palette_gen.rs"


def main() -> None:
    check = "--check" in sys.argv
    entries = sorted(PALETTE_DIR.rglob("*.toml"))
    if not entries:
        sys.exit(f"gen_palette: no palette entries under {PALETTE_DIR}")

    listed = "".join(f"//!   - {path.relative_to(ROOT)}\n" for path in entries)
    rows = "".join(
        "    (\n"
        f'        "{path.relative_to(PALETTE_DIR)}",\n'
        f'        include_str!("../../../specs/unit_ops/{path.relative_to(PALETTE_DIR)}"),\n'
        "    ),\n"
        for path in entries
    )
    text = (
        "//! GENERATED FILE - DO NOT EDIT BY HAND.\n//!\n"
        "//! Generated by `tools/gen_palette.py` from:\n"
        f"{listed}"
        "//!\n"
        "//! Regenerate with `python tools/gen_palette.py`; CI runs `--check` and fails on\n"
        "//! any difference.\n\n"
        "/// Every shipped palette entry, as the text it is written in.\n"
        "///\n"
        "/// **Embedded because a browser has no filesystem.** `load_palette` walks a directory,\n"
        "/// which a wasm module cannot do, so this is the same files as text and the one loader\n"
        "/// parses both. `the_embedded_palette_is_the_directory` holds them to each other byte\n"
        "/// for byte, so a bundle that drifted from the tree fails rather than shipping.\n"
        "pub static PALETTE: &[(&str, &str)] = &[\n"
        f"{rows}"
        "];\n"
    )

    rendered = text
    if text:
        proc = subprocess.run(
            ["rustfmt", "--edition", "2024"],
            input=text,
            capture_output=True,
            text=True,
            check=False,
        )
        if proc.returncode != 0:
            sys.exit(f"gen_palette: rustfmt refused the output:\n{proc.stderr}")
        rendered = proc.stdout

    existing = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if existing != rendered:
        if check:
            print(f"gen_palette: {OUT.relative_to(ROOT)} is out of date")
            sys.exit("gen_palette: generated file is stale; run tools/gen_palette.py")
        OUT.write_text(rendered, encoding="utf-8")
        print(f"gen_palette: wrote {OUT.relative_to(ROOT)}")

    print(
        f"gen_palette: {len(entries)} palette entries"
        + (", generated file up to date" if check else "")
    )


if __name__ == "__main__":
    main()
