#!/usr/bin/env python3
"""Generate the executor's palette-id to kernel table.

`crates/azoth-process/src/executor/dispatch.rs` carried a hand-written `DISPATCH` list: one
`("<palette id>", <adapter>)` line per unit operation. The *key* is the palette's own id and the
*value* is an adapter the same file declares, so the list is a join of two things already written —
and a palette entry added without its line is a flowsheet that fails at run time with "no kernel",
which is the drift this removes.

**The adapter stays hand-written and the table does not.** An adapter parses the entry's declared
parameters out of a flowsheet and calls the kernel, and what it does is per operation rather than
per shape; the generator reads which ones exist and emits the join. An adapter with no palette
entry, or a palette entry whose leaf names no adapter, is a refusal here rather than a line
somebody has to remember.

`UNRUNNABLE` stays in `dispatch.rs`: its one entry carries a *reason* — a sentence about the
chemistry a faithful port would need — and nothing in the palette declares one.

    python tools/gen_dispatch.py            # write
    python tools/gen_dispatch.py --check    # fail if the tree is not what this emits
"""

from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PALETTE = ROOT / "specs" / "unit_ops"
SOURCE = ROOT / "crates" / "azoth-process" / "src" / "executor" / "dispatch.rs"
OUT = ROOT / "crates" / "azoth-process" / "src" / "executor" / "dispatch_gen.rs"

#: An adapter's signature. Read as a whole rather than line by line, because two of them wrap.
_ADAPTER = re.compile(
    r"fn (\w+)\(\s*\n?\s*inlets: &\[Stream\],\s*\n?\s*_?p: &Parameters<'_>\s*,?\s*\n?\s*\)"
    r"\s*->\s*Result<KernelOutcome>"
)


def palette_ids() -> list[str]:
    """Every entry the palette declares, sorted - the table's keys."""
    out = []
    for path in sorted(PALETTE.rglob("*.toml")):
        out.append(tomllib.loads(path.read_text(encoding="utf-8"))["id"])
    if not out:
        sys.exit(f"gen_dispatch: no palette entries under {PALETTE.relative_to(ROOT)}")
    return sorted(out)


def adapters() -> set[str]:
    """The adapter functions `dispatch.rs` declares, by name."""
    found = set(_ADAPTER.findall(SOURCE.read_text(encoding="utf-8")))
    if not found:
        sys.exit(
            "gen_dispatch: no adapter functions parsed from "
            f"{SOURCE.relative_to(ROOT)} - the signature this reader matches has moved"
        )
    return found


def emit() -> str:
    """`dispatch_gen.rs`: the table, with one line per palette entry that has an adapter."""
    ids = palette_ids()
    known = adapters()
    entries = {calc_id: calc_id.rsplit(".", 1)[-1] for calc_id in ids}
    orphaned = sorted(name for name in known if name not in set(entries.values()))
    if orphaned:
        sys.exit(
            f"gen_dispatch: {SOURCE.relative_to(ROOT)} declares adapter(s) no palette entry names: "
            f"{orphaned} - an adapter nothing dispatches to is dead code"
        )
    listed = [(calc_id, leaf) for calc_id, leaf in entries.items() if leaf in known]
    imports = ", ".join(leaf for _, leaf in listed)
    body = "".join(f'    ("{calc_id}", {leaf}),\n' for calc_id, leaf in listed)
    return (
        "//! GENERATED FILE - DO NOT EDIT BY HAND.\n"
        "//!\n"
        "//! Generated by `tools/gen_dispatch.py` from the palette's own ids and the adapters\n"
        "//! `executor/dispatch.rs` declares.\n"
        "//!\n"
        "//! One entry per palette id that has an adapter, each returning its outlets in\n"
        "//! the order the declaration names them.\n"
        "//!\n"
        "//! Regenerate with `python tools/gen_dispatch.py`; CI runs `--check` and fails on any\n"
        "//! difference.\n"
        "\n"
        "use crate::executor::dispatch::{\n"
        f"    Kernel, {imports},\n"
        "};\n"
        "\n"
        "/// **The table.** One entry per palette id that has a kernel.\n"
        "pub const DISPATCH: &[(&str, Kernel)] = &[\n"
        f"{body}"
        "];\n"
    )


def format_rust(text: str) -> str:
    """Run the emitted Rust through rustfmt, which the committed file is compared against."""
    try:
        proc = subprocess.run(
            ["rustfmt", "--edition", "2024"],
            input=text,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        sys.exit(
            "gen_dispatch: rustfmt is not on PATH, and the generated file is compared against "
            "rustfmt's own output - install the Rust toolchain"
        )
    if proc.returncode != 0:
        sys.exit(f"gen_dispatch: rustfmt refused the output:\n{proc.stderr}")
    return proc.stdout


def main() -> None:
    check = "--check" in sys.argv
    rendered = format_rust(emit())
    existing = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if existing == rendered:
        print(f"gen_dispatch: {OUT.relative_to(ROOT)} is current")
        return
    if check:
        sys.exit(f"gen_dispatch: {OUT.relative_to(ROOT)} is out of date; run tools/gen_dispatch.py")
    OUT.write_text(rendered, encoding="utf-8")
    print(f"gen_dispatch: wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
