#!/usr/bin/env python3
"""Generate the documentation from the calc specs.

Reads every spec under specs/calcs/ and writes:

  docs/src/SUMMARY.md              the mdBook table of contents
  docs/src/hydraulics/index.md     an index of the calcs
  docs/src/hydraulics/<id>.md      one page per calc

CI regenerates these and fails if `git diff` is non-empty, which is what makes
"the docs are generated from the registry" a property of the build rather than a
claim in the README.

# Why this imports the runtime

Bounds are rendered by `chemeng.core.range.RangeCheck`, the same code that
produces the text inside a runtime warning. Re-implementing the rendering here
would be a second definition of what a bound means, and the two would eventually
disagree - so a user would read one bound in the docs and see a different one in
a warning. Importing it means there is exactly one renderer.

Usage:
    python tools/gen_docs.py            # write the files
    python tools/gen_docs.py --check    # fail if they are out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("gen_docs requires PyYAML")

ROOT = Path(__file__).resolve().parent.parent
SPEC_DIR = ROOT / "specs" / "calcs"
DOCS_SRC = ROOT / "docs" / "src"
CALCS_DIR = DOCS_SRC / "hydraulics"

# The runtime's own bound renderer, so the docs and the warnings cannot disagree
# about how a bound reads.
sys.path.insert(0, str(ROOT / "python" / "src"))
from chemeng.core.range import RangeCheck  # noqa: E402

BANNER = "<!-- Generated by tools/gen_docs.py from {source}. Do not edit by hand. -->"

#: Namespace -> display title, for the summary sections.
NAMESPACES = {"hydraulics": "Hydraulics"}


def namespace_dir(namespace: str) -> Path:
    """Where a namespace's pages live.

    Hydraulics is a section of the book; a future namespace would be too. Kept as
    one function so the summary, the index and the pages cannot disagree about
    where a file is.
    """
    return CALCS_DIR if namespace == "hydraulics" else DOCS_SRC / namespace


def source_of(spec: dict[str, Any]) -> str:
    """Repo-relative path of a calc's spec file."""
    parts = spec["id"].split(".")
    return f"specs/calcs/{parts[0]}/{parts[-1]}.yaml"


def describe_source(spec: dict[str, Any]) -> str:
    """One line naming where the equation came from."""
    source = spec["source"]
    bits = [f"**{source['standard']}**"]
    if source.get("edition"):
        bits.append(f"({source['edition']})")
    if source.get("equation"):
        bits.append(f"- {source['equation']}")
    line = " ".join(bits)
    if source.get("doi"):
        line += f"\n\nDOI: [{source['doi']}](https://doi.org/{source['doi']})"
    return line


def render_verification(spec: dict[str, Any]) -> str:
    """The verification status, stated plainly rather than buried.

    A reader deciding whether to trust a number needs this above the fold, not in
    a footnote. `source_needed` in particular means the calc should not be used.
    """
    status = spec["verification"]["status"]
    label = {
        "verified": "Verified against the primary source.",
        "unverified": (
            "**Unverified.** The equation is standard, but its citation has not been "
            "checked against the primary source by a person."
        ),
        "source_needed": ("**No adequate source found.** Do not rely on this calculation."),
    }[status]
    notes = spec["verification"].get("notes", "").strip()
    out = f"{label}\n"
    if notes:
        out += f"\n{notes}\n"
    return out


def render_table(rows: list[tuple[str, str, str]], headers: tuple[str, str, str]) -> str:
    out = f"| {headers[0]} | {headers[1]} | {headers[2]} |\n"
    out += "|---|---|---|\n"
    for row in rows:
        out += f"| {row[0]} | {row[1]} | {row[2]} |\n"
    return out


def describe_quantity(declaration: dict[str, Any]) -> tuple[str, str]:
    """The unit and description columns for an input or output."""
    kind = declaration.get("type", "quantity")
    if kind == "fitting_list":
        unit = "-"
    elif kind == "enum":
        unit = " / ".join(declaration.get("values", []))
    else:
        unit = declaration.get("unit", "-")
    description = " ".join(str(declaration.get("description", "")).split())
    if declaration.get("optional"):
        description = f"*Optional.* {description}"
    return unit, description


def render_range(spec: dict[str, Any]) -> str:
    """The validated range, rendered by the same code that emits the warnings."""
    rows: list[tuple[str, str, str]] = []
    for raw in spec["valid_range"]:
        check = RangeCheck.from_spec(raw)
        bound = check.describe()
        effect = "raises" if check.severity.value == "error" else f"warns `{check.code.value}`"
        rows.append((f"`{bound}`", effect, check.rationale))
    return render_table(rows, ("Bound", "On violation", "Why"))


def render_solver(spec: dict[str, Any]) -> str:
    """The solver block, for implicit equations only."""
    solver = spec.get("solver")
    if not solver:
        return ""
    return f"""## Solver

This equation is implicit, so it is solved rather than evaluated. The scheme is
part of the specification because both implementations must run the *same* one:

| Setting | Value |
|---|---|
| Kind | `{solver["kind"]}` |
| Tolerance | `{solver["tolerance"]}` |
| Convergence | `{solver["convergence"]}` |
| Max iterations | `{solver["max_iterations"]}` |
| Initial guess | `{solver["initial_guess"]}` |

Two implementations running the same algorithm converge to the same value; two
running different-but-equally-valid algorithms agree only to within their
difference, which is far larger than the agreed tolerance allows.

"""


def render_worked_example(spec: dict[str, Any]) -> str:
    example = spec["worked_example"]
    inputs = "\n".join(f"| `{k}` | {v} |" for k, v in example["inputs"].items())
    outputs = "\n".join(f"| `{k}` | {v} |" for k, v in example["expected"].items())
    derivation = " ".join(str(example.get("derivation", "")).split())

    out = "## Worked example\n\n"
    out += f"Source: {example['source']}\n\n"
    out += f"| Input | Value |\n|---|---|\n{inputs}\n\n"
    out += f"| Output | Expected |\n|---|---|\n{outputs}\n\n"
    out += f"Relative tolerance: `{example['tolerance']}`\n"
    if derivation:
        out += f"\n{derivation}\n"
    return out


def render_tests(spec: dict[str, Any]) -> str:
    rows: list[tuple[str, str, str]] = []
    worked = next((t for t in spec["tests"] if t["type"] == "worked_example"), None)
    entries: list[dict[str, Any]] = []
    if worked:
        entries.append(worked)
    entries.extend(t for t in spec["tests"] if t["type"] != "worked_example")

    for test in entries:
        status = test["status"]
        if status == "skipped":
            reason = " ".join(str(test.get("skip_reason", "")).split())
            status = f"**skipped** - {reason}"
        detail = test.get("property") or {
            "worked_example": "the example above",
            "reference": "an independent value",
        }.get(test["type"], "")
        rows.append((f"`{test['id']}`", f"`{test['type']}`", f"{detail}; {status}"))
    return render_table(rows, ("Test", "Type", "What it does"))


def render_calc(spec: dict[str, Any]) -> str:
    source = source_of(spec)
    namespace = spec["id"].split(".")[0]

    parts: list[str] = []
    parts.append(BANNER.format(source=source))
    parts.append(f"\n# {spec['name']}\n")
    parts.append(f"`{spec['id']}`\n")
    parts.append("## Equation\n")
    parts.append(f"$$\n{spec['latex']}\n$$\n")
    parts.append(f"In the form the library evaluates:\n\n```python\n{spec['equation']}\n```\n")
    parts.append("## Source\n")
    parts.append(describe_source(spec) + "\n")
    parts.append("## Verification\n")
    parts.append(render_verification(spec))

    rows = [(f"`{name}`", *describe_quantity(d)) for name, d in spec["inputs"].items()]
    parts.append("## Inputs\n")
    parts.append(render_table(rows, ("Name", "Unit", "Description")))

    rows = [(f"`{name}`", *describe_quantity(d)) for name, d in spec["outputs"].items()]
    parts.append("\n## Outputs\n")
    parts.append(render_table(rows, ("Name", "Unit", "Description")))

    parts.append("\n## Valid range\n")
    parts.append(render_range(spec))

    parts.append("\n## Assumptions\n")
    parts.append(
        "These are **not** checked at runtime. They are what the caller has to\n"
        "satisfy for the result to mean what it says.\n\n"
    )
    parts.append("\n".join(f"- {a}" for a in spec["assumptions"]) + "\n")

    parts.append("\n" + render_solver(spec))
    parts.append(render_worked_example(spec))
    parts.append("\n## Tests\n")
    parts.append(render_tests(spec))

    if spec.get("data"):
        parts.append("\n## Data\n")
        for key, path in spec["data"].items():
            parts.append(f"- `{key}`: `{path}`\n")

    parts.append("\n## Implementation\n")
    parts.append(f"- Python: `{spec['implementations']['python']}`\n")
    parts.append(f"- Rust: `{spec['implementations']['rust']}`\n")

    parts.append("\n## References\n")
    parts.append("\n".join(f"- {r}" for r in spec["references"]) + "\n")

    parts.append(f"\n---\n\n[Back to {NAMESPACES.get(namespace, namespace)}](./index.md)\n")
    return "\n".join(parts)


def render_namespace_index(calcs: list[dict[str, Any]], namespace: str) -> str:
    title = NAMESPACES.get(namespace, namespace)
    out = BANNER.format(source=f"specs/calcs/{namespace}/") + "\n"
    out += f"\n# {title}\n\n"
    out += (
        "Every calculation in this section is generated from its specification. "
        "Each page shows the equation, where it came from, the range in which it is "
        "validated, its assumptions, a worked example, and the tests that exercise "
        "it.\n\n"
    )
    out += "| Calculation | Equation | Source |\n|---|---|---|\n"
    for calc in calcs:
        equation = calc["latex"].replace("|", r"\|")
        standard = calc["source"]["standard"].replace("|", r"\|")
        out += (
            f"| [`{calc['id']}`](./{calc['id'].split('.')[-1]}.md) | ${equation}$ | {standard} |\n"
        )
    return out


def render_summary(calcs: list[dict[str, Any]]) -> str:
    out = "# Summary\n\n- [chemeng](./index.md)\n"
    by_namespace: dict[str, list[dict[str, Any]]] = {}
    for calc in calcs:
        by_namespace.setdefault(calc["id"].split(".")[0], []).append(calc)

    for namespace in sorted(by_namespace):
        title = NAMESPACES.get(namespace, namespace)
        out += f"- [{title}](./{namespace}/index.md)\n"
        for calc in by_namespace[namespace]:
            out += f"  - [{calc['name']}](./{namespace}/{calc['id'].split('.')[-1]}.md)\n"
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    paths = sorted(SPEC_DIR.rglob("*.yaml"))
    if not paths:
        sys.exit(f"gen_docs: no specs found under {SPEC_DIR}")
    calcs = [yaml.safe_load(p.read_text(encoding="utf-8")) for p in paths]
    calcs.sort(key=lambda c: c["id"])

    outputs: dict[Path, str] = {DOCS_SRC / "SUMMARY.md": render_summary(calcs)}
    for namespace in sorted({c["id"].split(".")[0] for c in calcs}):
        in_namespace = [c for c in calcs if c["id"].split(".")[0] == namespace]
        directory = namespace_dir(namespace)
        outputs[directory / "index.md"] = render_namespace_index(in_namespace, namespace)
        for calc in in_namespace:
            outputs[directory / f"{calc['id'].split('.')[-1]}.md"] = render_calc(calc)

    stale: list[Path] = []
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                stale.append(path)
        else:
            path.write_text(content, encoding="utf-8")

    if args.check:
        if stale:
            for path in stale:
                print(f"gen_docs: {path.relative_to(ROOT)} is out of date", file=sys.stderr)
            print("Run `python tools/gen_docs.py` to regenerate.", file=sys.stderr)
            return 1
        print(f"gen_docs: {len(outputs)} file(s), up to date")
        return 0

    print(f"gen_docs: wrote {len(outputs)} file(s) for {len(calcs)} calc(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
