#!/usr/bin/env python3
"""Generate the extension's registration of every calculation and every result class.

`crates/azoth-python/src/lib.rs`'s `_core` module opened with 194 `add_function(wrap_pyfunction!(
...))` lines and a hand-picked list of `add_class` lines. Both are a function of the registry:
a spec names its Rust implementation as `azoth_hydraulics::reynolds_number`, so the namespace and
the function name are declared, and every registered id has exactly one Rust result type
(`tools/rust_index.py`).

**The namespace map is exhaustive and refuses a seventh.** Six crates carry registered ids -
`azoth-hydraulics`, `azoth-eos`, `azoth-thermal`, `azoth-reactions`, `azoth-standards` and
`azoth-process` - and each maps to a module of this crate. A spec whose `implementations.rust`
names a crate that is not in the map is a refusal here rather than a silently unregistered
function, which is what "and nothing else" is supposed to mean.

**Every result class is registered**, not the subset that was there before. `add_class` is what
makes a type reachable as `azoth._core.<Name>`; pyo3 returns an instance of an unregistered
`#[pyclass]` perfectly well, so the old list was a selection with no rule behind it - 56 of 194,
and no test read `dir(azoth._core)` to say which. The registered set is now the whole set, and
the ratchet in `python/tests/test_gen_python_register.py` holds the number of hand-written
`add_class`/`add_function` lines in `lib.rs` to the ones this file cannot derive.

    python tools/gen_python_register.py            # write
    python tools/gen_python_register.py --check    # fail if the tree is not what this emits
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rust_index

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates" / "azoth-python" / "src" / "register_gen.rs"

#: The crate a spec's `implementations.rust` names, to the module of this crate that carries the
#: `#[pyfunction]` it wraps. Exhaustive by intent: a seventh crate is a refusal, because a
#: function this file could not place would be a calculation the extension does not register.
NAMESPACES = {
    "azoth_hydraulics": "hydraulics",
    "azoth_eos": "eos",
    "azoth_thermal": "thermal",
    "azoth_reactions": "reactions",
    "azoth_standards": "standards",
    "azoth_process": "process",
}


def implementations() -> list[tuple[str, str, str]]:
    """Every registered id as `(calc_id, module, function)`, in id order.

    The function name is the last segment of the spec's own Rust path, which is the name the
    `#[pyfunction]` carries - the two are written once, in the spec and in the module, and this
    asserts they are the same word rather than assuming a naming rule.
    """
    out: list[tuple[str, str, str]] = []
    for namespace in ("calcs", "models"):
        for path in sorted((ROOT / "specs" / namespace).rglob("*.toml")):
            document = tomllib.loads(path.read_text(encoding="utf-8"))
            calc_id = document["id"]
            crate, _, rest = document["implementations"]["rust"].partition("::")
            module = NAMESPACES.get(crate)
            if module is None:
                sys.exit(
                    f"gen_python_register: {calc_id} names the crate {crate!r}, which is not one "
                    f"of the six namespaces {sorted(NAMESPACES)}"
                )
            if not rest:
                sys.exit(f"gen_python_register: {calc_id}'s rust path has no item after the crate")
            out.append((calc_id, module, rest.split("::")[-1]))
    return sorted(out)


def emit() -> str:
    """The whole file, in id order so it is a stable diff."""
    rust_index.check()
    results = rust_index.result_types()
    known = {result.calc_id for result in results}
    functions = implementations()
    unknown = [calc_id for calc_id, _, _ in functions if calc_id not in known]
    if unknown:
        sys.exit(f"gen_python_register: no result type for {unknown}")

    classes = "".join(
        f"    m.add_class::<crate::transport_gen::Py{result.rust_name}>()?;\n" for result in results
    )
    registrations = "".join(
        f"    m.add_function(wrap_pyfunction!(crate::{module}::{function}, m)?)?;\n"
        for _, module, function in functions
    )
    header = (
        "//! GENERATED FILE - DO NOT EDIT BY HAND.\n"
        "//!\n"
        "//! Generated by `tools/gen_python_register.py` from:\n"
        "//!   - specs/calcs/**/*.toml and specs/models/**/*.toml, for each id's\n"
        "//!     `implementations.rust` path - the namespace and the function name\n"
        "//!   - the `impl CalcResult` blocks under `crates/*/src`, for the result types\n"
        "//!     (`tools/rust_index.py`)\n"
        "//!\n"
        "//! Regenerate with `python tools/gen_python_register.py`; CI runs `--check` and\n"
        "//! fails on any difference.\n"
        "\n"
        "use pyo3::prelude::*;\n"
        "use pyo3::types::PyModule;\n"
        "\n"
        "/// Every registered calculation, model and result class.\n"
        "///\n"
        "/// Called once by `crate::_core`, which adds the names this file cannot derive - the\n"
        "/// data-transport classes, the card overlay, the stream and session bindings and the\n"
        "/// introspection helpers.\n"
        "pub(crate) fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {\n"
    )
    return (
        header
        + "    // The result class each registered id answers with.\n"
        + classes
        + "\n    // The calculations and models themselves.\n"
        + registrations
        + "    Ok(())\n"
        + "}\n"
    )


def format_rust(text: str) -> str:
    """Run the emitted Rust through rustfmt, which the committed file is compared against."""
    try:
        proc = subprocess.run(
            ["rustfmt", "--edition", "2024"],
            input=text,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        sys.exit(
            "gen_python_register: rustfmt is not on PATH, and the generated file is compared "
            "against rustfmt's own output - install the Rust toolchain"
        )
    if proc.returncode != 0:
        sys.exit(f"gen_python_register: rustfmt refused the output:\n{proc.stderr}")
    return proc.stdout


def main() -> None:
    check = "--check" in sys.argv
    rendered = format_rust(emit())
    existing = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if existing == rendered:
        print(f"gen_python_register: {OUT.relative_to(ROOT)} is current")
        return
    if check:
        sys.exit(
            f"gen_python_register: {OUT.relative_to(ROOT)} is out of date; run "
            "tools/gen_python_register.py"
        )
    OUT.write_text(rendered, encoding="utf-8")
    print(f"gen_python_register: wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
