#!/usr/bin/env python3
"""Fail the build on prose that narrates the code's own history.

A comment either explains the code in front of the reader, or reports something that
belongs in the commit that makes the change, or narrates the
code's history or the author's process. The last of those is the one this catches.

**This is a backstop and it is deliberately narrow.** The phrase list below is every
candidate phrasing that occurs **zero times** in the files this tool reads. The
measurement has to exclude `tools/prose_lint.py` itself, which is a literal list of the
phrases and therefore matches all of them - a detail the first version of this paragraph
left out, and the reason the tool shipped failing on its own tree:

    grep -rniI --include='*.rs' --include='*.py' --include='*.toml' -- '<phrase>' \\
        crates python/src python/tests specs tools --exclude=prose_lint.py

Phrasings that occur in the existing tree are **not** here, however much they read like
spam, because they are part of how this repository writes: `deliberately` occurs 105
times, `no longer` 31, `the whole point` 11, and `load-bearing` 9 - including twice in
`docs/src/architecture/specification.md`. A check that fires on those would be a check
that has to be switched off, which is worse than no check.

**What that leaves out is the point.** The phrases that actually needed catching -
`deliberately`, `the whole point`, `the load-bearing` - cannot be caught by a phrase list
without catching the house style with them. They are caught by a second reader instead:
see P2, which requires verification by something other than the author.

Usage:
    python tools/prose_lint.py            # check
    python tools/prose_lint.py --quiet    # only report problems
    python tools/prose_lint.py --path <dir>   # check a different tree

Exit status is non-zero when any occurrence is found.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: Prose that narrates the code's own history. Every entry is a phrasing measured to
#: occur nowhere in this tree outside the change set that prompted this tool, so a hit is
#: a hit rather than a disagreement about style. See the module docstring for the command
#: that establishes it, and re-run it before adding an entry.
HISTORY_PHRASES: tuple[str, ...] = (
    "did not exist",
    "formerly",
    "was renamed",
    "this branch did not",
    "had to change",
    "used to be called",
    "used to be named",
    "before this existed",
    "had already diverged",
)

#: Files whose prose is generated and therefore not written by anyone.
GENERATED_MARKERS: tuple[str, ...] = (
    "GENERATED FILE - DO NOT EDIT BY HAND",
    "Generated by tools/",
)

#: Where prose lives. The docs are prose by definition and are not checked; `docs/src`
#: carries the pages that the standard is *about*.
#:
#: `lean/Azoth` and not `lean`: the vendored `lean-units` under `lean/vendor/` is
#: third-party code that travels unmodified, so a phrase in it is not this
#: repository's to remove - and a check that demanded an edit there would be a
#: check that could only be satisfied by untracking the vendor.
SEARCH: tuple[tuple[str, str], ...] = (
    ("crates", "*.rs"),
    ("lean/Azoth", "*.lean"),
    ("python/src", "*.py"),
    ("python/tests", "*.py"),
    ("specs", "*.toml"),
    ("tools", "*.py"),
)


def is_generated(path: Path) -> bool:
    """Whether a file is emitted by a generator rather than written by hand."""
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:2000]
    except OSError:
        return False
    return any(marker in head for marker in GENERATED_MARKERS)


#: This file, resolved, so it can be excluded from its own scan.
SELF = Path(__file__).resolve()


def sources(root: Path) -> list[Path]:
    """Every file the standard applies to, in a stable order.

    `prose_lint.py` is skipped: `HISTORY_PHRASES` is a literal list of the phrases being
    searched for, so the file matches every entry in it. That list is the tool's data
    rather than its prose, and there is no way to state it without writing the phrases
    down. Until this exclusion existed the tool reported itself seven times, exited 1 on
    every tree, and could not have been wired into anything.
    """
    found: list[Path] = []
    for directory, pattern in SEARCH:
        base = root / directory
        if not base.is_dir():
            continue
        found.extend(
            path
            for path in base.rglob(pattern)
            if not is_generated(path) and path.resolve() != SELF
        )
    return sorted(found)


def offending_lines(path: Path) -> list[tuple[int, str, str]]:
    """Every line carrying a history phrase: line number, phrase, and the line itself."""
    hits: list[tuple[int, str, str]] = []
    for number, line in enumerate(
        path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1
    ):
        lowered = line.lower()
        for phrase in HISTORY_PHRASES:
            if phrase in lowered:
                hits.append((number, phrase, line.strip()))
    return hits


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--quiet", action="store_true", help="only print problems")
    parser.add_argument(
        "--path",
        type=Path,
        default=ROOT,
        help="tree to check (default: the repository root)",
    )
    args = parser.parse_args()

    checked = sources(args.path)
    problems = 0
    for path in checked:
        for number, phrase, line in offending_lines(path):
            problems += 1
            print(f"{path.relative_to(args.path)}:{number}: history phrase {phrase!r}")
            print(f"    {line}")

    if not args.quiet:
        print(f"prose_lint: {len(checked)} file(s) checked")

    if problems:
        print(
            f"prose_lint: {problems} line(s) narrate the code's history. The comment "
            f"either explains the code in front of the reader, or it reports something "
            f"as a defect report in the commit that fixes it, or it does not belong in "
            f"the file."
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
