"""Equations of state.

The third namespace, and the first that is not a correlation over pipe or wall
geometry. It exists because a cubic equation of state decomposes the same way every
other calculation here does - into constitutive coefficients, each with a published
source and a worked example - and the decomposition is worth having explicitly,
since a wrong coefficient is invisible downstream.

* :func:`pr_kappa` - the Peng-Robinson alpha-function coefficient
* :func:`pr_alpha_ab` - the alpha function and the reduced attraction parameters
* :func:`pr_departure` - fugacity coefficient and departure functions
* :func:`pr_z_factor` - the compressibility factor, the cubic's real roots
* :func:`pr_molar_volume` - molar volume, the one dimensional quantity here
* :func:`pr_mass_density` - mass density, and the end of the path to something useful

# Models

:func:`pure_saturation` is a *model* rather than a calculation: its spec fixes a
procedure rather than an equation, and it lives in ``specs/models/`` with a table
generated by ``tools/gen_models.py`` instead of ``gen_registry.py``. It composes the
kernels above and adds a search.
* :func:`prsv_kappa` - the Stryjek-Vera coefficient, for the same alpha function
* :func:`vdw1f_mix_binary` - van der Waals one-fluid mixing for a binary
* :func:`rachford_rice_binary` - the vapour fraction that solves Rachford-Rice

# Why the coefficients come first

The obvious shape for this namespace is one calc per equation of state, taking a
component and returning a Z factor. That shape hides the constants: a transposed
digit in the ``omega**2`` coefficient produces an equation that still runs, still
converges and is slightly wrong everywhere, and no check on the Z factor can see
it, because the Z factor is computed *from* the coefficient.

Splitting the constitutive coefficients out gives each one its own spec, its own
worked example and its own cross-language test. It also makes a modification cheap:
Peng-Robinson-Stryjek-Vera changes the temperature dependence of ``kappa`` and
nothing else, so under this decomposition it is one new calc rather than a fork of
the whole chain.

# Where the components come from

:mod:`azoth.eos.components` ships a databank: 173 substances read from
``data/components/components.csv``, generated from NeqSim (Apache-2.0) by
``tools/gen_databank.py`` and attributed in ``NOTICE``. Every pure-component
constant is still an argument - the acentric factor here, and the critical
temperature and pressure that go with it - so the databank is a default a caller
can replace, and nothing checks that a caller's values agree with it.

# Dimensionless by construction

Everything here works in reduced variables - ``Tr``, ``Pr``, and the dimensionless
coefficients that follow from them. ``A = 0.45724 * alpha * Pr / Tr**2`` needs no
gas constant, no pressure unit and no temperature unit, and the vapour-liquid
mixing rule is linear in ``A`` and ``B`` exactly as it is in ``a`` and ``b``. So
these functions take and return ``pint`` quantities that carry no unit, and the
dimensional conversion happens once, at the boundary, where it can be tested once.

# Which implementation answers

As in every other namespace, each function dispatches to the Rust extension when it
is built and to :mod:`azoth.eos.reference` otherwise. Both are always reachable -
see :func:`azoth.backends` and :func:`azoth.use_backend`.
"""

from __future__ import annotations

from collections.abc import Sequence

from azoth._dispatch import resolve
from azoth.core.result import (
    AntoineVaporPressureResult,
    BubblePressureResult,
    ChungConductivityResult,
    ChungViscosityResult,
    Co2WaterDiffusivityResult,
    CostaldMolarVolumeResult,
    CriticalPointResult,
    DewPressureResult,
    HaydukMinhasDiffusivityResult,
    HeatOfVaporizationResult,
    IdealGasCpResult,
    LiquidHeatCapacityResult,
    MasonSaxenaConductivityResult,
    MolarEnthalpyEntropyResult,
    NrtlActivityCoefficientsResult,
    PhFlashResult,
    Pr78KappaResult,
    PrAlphaAbResult,
    PrDepartureResult,
    PrKappaResult,
    PrMassDensityResult,
    PrMolarVolumeResult,
    PrPenelouxShiftResult,
    PrsvKappaResult,
    PrZFactorResult,
    PsFlashResult,
    PtFlashResult,
    PuFlashResult,
    PureSaturationResult,
    PvFlashResult,
    RachfordRiceBinaryResult,
    RackettMolarVolumeResult,
    RkAlphaAbResult,
    RkDepartureResult,
    SiddiqiLucasDiffusivityResult,
    SrkAlphaAbResult,
    SrkDepartureResult,
    SrkKappaResult,
    SrkPenelouxShiftResult,
    SrkZFactorResult,
    StabilityTestResult,
    ThFlashResult,
    TsFlashResult,
    TuFlashResult,
    TvFlashResult,
    TwuKappaResult,
    TynCalusDiffusivityResult,
    UnifacActivityCoefficientsResult,
    UniquacActivityCoefficientsResult,
    Vdw1fMixBinaryResult,
    WilkeChangDiffusivityResult,
    WilkeViscosityResult,
    WilsonActivityCoefficientsResult,
)
from azoth.core.units import Q
from azoth.eos.components import available as available_components
from azoth.eos.components import component, from_model, from_names, wilke_chang_phi
from azoth.eos.mixture import Component, Mixture, mixture
from azoth.eos.reference.molar_enthalpy_entropy import IdealGasModel

__all__ = [
    "Component",
    "IdealGasModel",
    "Mixture",
    "antoine_vapor_pressure",
    "available_components",
    "bubble_pressure",
    "chung_conductivity",
    "chung_viscosity",
    "component",
    "costald_molar_volume",
    "critical_point",
    "dew_pressure",
    "from_model",
    "from_names",
    "hayduk_minhas_diffusivity",
    "heat_of_vaporization",
    "ideal_gas_cp",
    "liquid_heat_capacity",
    "mason_saxena_conductivity",
    "mixture",
    "molar_enthalpy_entropy",
    "nrtl_activity_coefficients",
    "ph_flash",
    "pr78_kappa",
    "pr_alpha_ab",
    "pr_departure",
    "pr_kappa",
    "pr_mass_density",
    "pr_molar_volume",
    "pr_peneloux_shift",
    "pr_z_factor",
    "prsv_kappa",
    "pt_flash",
    "pu_flash",
    "pure_saturation",
    "pv_flash",
    "rachford_rice_binary",
    "rackett_molar_volume",
    "rk_alpha_ab",
    "rk_departure",
    "siddiqi_lucas_diffusivity",
    "srk_alpha_ab",
    "srk_departure",
    "srk_kappa",
    "srk_peneloux_shift",
    "srk_z_factor",
    "stability_test",
    "th_flash",
    "ts_flash",
    "tu_flash",
    "tv_flash",
    "twu_kappa",
    "tyn_calus_diffusivity",
    "unifac_activity_coefficients",
    "uniquac_activity_coefficients",
    "vdw1f_mix_binary",
    "wilke_chang_diffusivity",
    "wilke_chang_phi",
    "wilke_viscosity",
    "wilson_activity_coefficients",
]

_PR_KAPPA = "eos.pr_kappa"
_PR_MOLAR_VOLUME = "eos.pr_molar_volume"
_PR_MASS_DENSITY = "eos.pr_mass_density"
_PR_PENELOUX_SHIFT = "eos.pr_peneloux_shift"
_SRK_PENELOUX_SHIFT = "eos.srk_peneloux_shift"
_HEAT_OF_VAPORIZATION = "eos.heat_of_vaporization"
_ANTOINE_VAPOR_PRESSURE = "eos.antoine_vapor_pressure"
_LIQUID_HEAT_CAPACITY = "eos.liquid_heat_capacity"
_MASON_SAXENA_CONDUCTIVITY = "eos.mason_saxena_conductivity"
_IDEAL_GAS_CP = "eos.ideal_gas_cp"
_MOLAR_ENTHALPY_ENTROPY = "eos.molar_enthalpy_entropy"
_NRTL_ACTIVITY_COEFFICIENTS = "eos.nrtl_activity_coefficients"
_BUBBLE_PRESSURE = "eos.bubble_pressure"
_CHUNG_CONDUCTIVITY = "eos.chung_conductivity"
_CHUNG_VISCOSITY = "eos.chung_viscosity"
_COSTALD_MOLAR_VOLUME = "eos.costald_molar_volume"
_CRITICAL_POINT = "eos.critical_point"
_DEW_PRESSURE = "eos.dew_pressure"
_PH_FLASH = "eos.ph_flash"
_PS_FLASH = "eos.ps_flash"
_TH_FLASH = "eos.th_flash"
_TS_FLASH = "eos.ts_flash"
_TU_FLASH = "eos.tu_flash"
_PU_FLASH = "eos.pu_flash"
_TV_FLASH = "eos.tv_flash"
_PV_FLASH = "eos.pv_flash"
_PT_FLASH = "eos.pt_flash"
_STABILITY_TEST = "eos.stability_test"
_PURE_SATURATION = "eos.pure_saturation"
_PR_ALPHA_AB = "eos.pr_alpha_ab"
_PR_DEPARTURE = "eos.pr_departure"
_PR_Z_FACTOR = "eos.pr_z_factor"
_PRSV_KAPPA = "eos.prsv_kappa"
_PR78_KAPPA = "eos.pr78_kappa"
_TWU_KAPPA = "eos.twu_kappa"
_TYN_CALUS_DIFFUSIVITY = "eos.tyn_calus_diffusivity"
_UNIFAC_ACTIVITY_COEFFICIENTS = "eos.unifac_activity_coefficients"
_UNIQUAC_ACTIVITY_COEFFICIENTS = "eos.uniquac_activity_coefficients"
_WILSON_ACTIVITY_COEFFICIENTS = "eos.wilson_activity_coefficients"
_WILKE_CHANG_DIFFUSIVITY = "eos.wilke_chang_diffusivity"
_HAYDUK_MINHAS_DIFFUSIVITY = "eos.hayduk_minhas_diffusivity"
_SIDDIQI_LUCAS_DIFFUSIVITY = "eos.siddiqi_lucas_diffusivity"
_CO2_WATER_DIFFUSIVITY = "eos.co2_water_diffusivity"
_VDW1F_MIX_BINARY = "eos.vdw1f_mix_binary"
_WILKE_VISCOSITY = "eos.wilke_viscosity"
_RACHFORD_RICE_BINARY = "eos.rachford_rice_binary"
_RACKETT_MOLAR_VOLUME = "eos.rackett_molar_volume"
_SRK_KAPPA = "eos.srk_kappa"
_SRK_ALPHA_AB = "eos.srk_alpha_ab"
_SRK_Z_FACTOR = "eos.srk_z_factor"
_SRK_DEPARTURE = "eos.srk_departure"
_RK_ALPHA_AB = "eos.rk_alpha_ab"
_RK_DEPARTURE = "eos.rk_departure"


def pr_kappa(omega: float) -> PrKappaResult:
    """The Peng-Robinson alpha-function coefficient for a pure component.

    ``omega`` is the acentric factor, and a plain float rather than a ``pint``
    quantity because it is genuinely dimensionless - the same rule that makes
    ``Re``, ``f`` and ``epsilon/D`` plain floats in the hydraulics calcs. A
    ``kappa`` below zero comes back carrying ``OUT_OF_VALID_RANGE`` rather than
    raising: the coefficient is negative for any acentric factor below about
    -0.2334, which helium is, and a value out of range is still a value.

    See :func:`azoth.eos.reference.pr_kappa`.
    """
    return resolve(_PR_KAPPA)(omega=omega)  # type: ignore[no-any-return]


def pr_alpha_ab(kappa: float, Tr: float, Pr: float) -> PrAlphaAbResult:
    """The Peng-Robinson alpha function and the reduced attraction parameters.

    ``a_reduced`` is the cubic's ``A`` and ``b_reduced`` its ``B`` - the form the
    equation of state is solved in, which needs no gas constant and no unit.

    Raises:
        OutOfRangeError: if ``Tr <= 0`` or ``Pr <= 0``.

    See :func:`azoth.eos.reference.pr_alpha_ab`.
    """
    return resolve(_PR_ALPHA_AB)(kappa=kappa, Tr=Tr, Pr=Pr)  # type: ignore[no-any-return]


def pr_z_factor(a_reduced: float, b_reduced: float) -> PrZFactorResult:
    """The Peng-Robinson compressibility factor, for one state.

    Returns the smallest and largest *admissible* real roots, where admissible means
    ``z > b_reduced``, plus how many there were. The middle root is deliberately not
    returned: it is a root of the polynomial and not a state the equation describes.

    Raises:
        OutOfRangeError: if ``b_reduced <= 0`` or ``a_reduced < 0``.

    See :func:`azoth.eos.reference.pr_z_factor`.
    """
    return resolve(_PR_Z_FACTOR)(a_reduced=a_reduced, b_reduced=b_reduced)  # type: ignore[no-any-return]


def prsv_kappa(omega: float, Tr: float, kappa1: float) -> PrsvKappaResult:
    """The PRSV alpha-function coefficient for a pure component.

    ``kappa1`` is the pure-compound parameter PRSV adds, and **this library ships no
    values for it** - a table of fitted parameters is the databank this library
    deliberately has none of. Passing a real one is the caller's job, and passing
    zero does not reproduce Peng-Robinson.

    Raises:
        OutOfRangeError: if ``Tr <= 0``.

    See :func:`azoth.eos.reference.prsv_kappa`.
    """
    return resolve(_PRSV_KAPPA)(omega=omega, Tr=Tr, kappa1=kappa1)  # type: ignore[no-any-return]


def pr78_kappa(omega: float) -> Pr78KappaResult:
    """The 1978 Peng-Robinson alpha-function coefficient for a pure component.

    The 1976 form for light components, a heavier-acentric branch for ``omega`` above
    0.49. Both feed the same Soave alpha function.

    See :func:`azoth.eos.reference.pr78_kappa`.
    """
    return resolve(_PR78_KAPPA)(omega=omega)  # type: ignore[no-any-return]


def twu_kappa(omega: float) -> TwuKappaResult:
    """Twu's alpha-function coefficient for a pure component.

    Differs from Soave's only in the last constant, 0.175 against 0.176.

    See :func:`azoth.eos.reference.twu_kappa`.
    """
    return resolve(_TWU_KAPPA)(omega=omega)  # type: ignore[no-any-return]


def pr_departure(
    a_reduced: float, b_reduced: float, z: float, kappa: float, Tr: float
) -> PrDepartureResult:
    """The Peng-Robinson fugacity coefficient and departure functions.

    ``kappa`` may come from :func:`pr_kappa` or :func:`prsv_kappa` - this calc uses it
    only through the logarithmic derivative of the alpha function, which both
    correlations feed.

    Raises:
        OutOfRangeError: if ``b_reduced <= 0`` or ``z <= b_reduced``.

    See :func:`azoth.eos.reference.pr_departure`.
    """
    return resolve(_PR_DEPARTURE)(  # type: ignore[no-any-return]
        a_reduced=a_reduced, b_reduced=b_reduced, z=z, kappa=kappa, Tr=Tr
    )


def srk_kappa(omega: float) -> SrkKappaResult:
    """The Soave-Redlich-Kwong alpha-function coefficient for a pure component.

    Soave's coefficient, the same *form* as Peng-Robinson's with different constants:
    ``0.48 + 1.574*omega - 0.176*omega**2``.

    See :func:`azoth.eos.reference.srk_kappa`.
    """
    return resolve(_SRK_KAPPA)(omega=omega)  # type: ignore[no-any-return]


def srk_alpha_ab(kappa: float, Tr: float, Pr: float) -> SrkAlphaAbResult:
    """The Soave-Redlich-Kwong alpha function and the reduced attraction parameters.

    Raises:
        OutOfRangeError: if ``Tr <= 0`` or ``Pr <= 0``.

    See :func:`azoth.eos.reference.srk_alpha_ab`.
    """
    return resolve(_SRK_ALPHA_AB)(kappa=kappa, Tr=Tr, Pr=Pr)  # type: ignore[no-any-return]


def srk_z_factor(a_reduced: float, b_reduced: float) -> SrkZFactorResult:
    """The Soave-Redlich-Kwong compressibility factor, for one state.

    Raises:
        OutOfRangeError: if ``b_reduced <= 0`` or ``a_reduced < 0``.

    See :func:`azoth.eos.reference.srk_z_factor`.
    """
    return resolve(_SRK_Z_FACTOR)(a_reduced=a_reduced, b_reduced=b_reduced)  # type: ignore[no-any-return]


def srk_departure(
    a_reduced: float, b_reduced: float, z: float, kappa: float, Tr: float
) -> SrkDepartureResult:
    """The Soave-Redlich-Kwong fugacity coefficient and departure functions.

    Raises:
        OutOfRangeError: if ``b_reduced <= 0`` or ``z <= b_reduced``.

    See :func:`azoth.eos.reference.srk_departure`.
    """
    return resolve(_SRK_DEPARTURE)(  # type: ignore[no-any-return]
        a_reduced=a_reduced, b_reduced=b_reduced, z=z, kappa=kappa, Tr=Tr
    )


def rk_alpha_ab(Tr: float, Pr: float) -> RkAlphaAbResult:
    """The Redlich-Kwong alpha function and the reduced attraction parameters.

    Kappa-free: ``alpha = 1/sqrt(Tr)``, the original Redlich-Kwong temperature
    dependence.

    Raises:
        OutOfRangeError: if ``Tr <= 0`` or ``Pr <= 0``.

    See :func:`azoth.eos.reference.rk_alpha_ab`.
    """
    return resolve(_RK_ALPHA_AB)(Tr=Tr, Pr=Pr)  # type: ignore[no-any-return]


def rk_departure(a_reduced: float, b_reduced: float, z: float) -> RkDepartureResult:
    """The Redlich-Kwong fugacity coefficient and departure functions.

    Raises:
        OutOfRangeError: if ``b_reduced <= 0`` or ``z <= b_reduced``.

    See :func:`azoth.eos.reference.rk_departure`.
    """
    return resolve(_RK_DEPARTURE)(  # type: ignore[no-any-return]
        a_reduced=a_reduced, b_reduced=b_reduced, z=z
    )


def vdw1f_mix_binary(
    z1: float, a1: float, a2: float, b1: float, b2: float, k12: float
) -> Vdw1fMixBinaryResult:
    """The van der Waals one-fluid mixture parameters for a binary.

    ``k12`` is the binary interaction parameter, and **this library ships no values
    for it** - a table of fitted binary parameters is the databank it deliberately
    does not have.

    Raises:
        OutOfRangeError: if ``z1`` is outside ``[0, 1]`` or the resulting ``a_mix``
            would be negative.

    See :func:`azoth.eos.reference.vdw1f_mix_binary`.
    """
    return resolve(_VDW1F_MIX_BINARY)(  # type: ignore[no-any-return]
        z1=z1, a1=a1, a2=a2, b1=b1, b2=b2, k12=k12
    )


def rachford_rice_binary(z1: float, K1: float, K2: float) -> RachfordRiceBinaryResult:
    """The vapour fraction that solves the Rachford-Rice equation for two components.

    A ``beta`` outside ``[0, 1]`` comes back carrying ``OUT_OF_VALID_RANGE`` rather
    than raising: it says the feed is single phase, which is a real answer.

    Raises:
        OutOfRangeError: if ``z1`` is outside ``[0, 1]``, either K-value is not
            positive, or either equals 1.

    See :func:`azoth.eos.reference.rachford_rice_binary`.
    """
    return resolve(_RACHFORD_RICE_BINARY)(z1=z1, K1=K1, K2=K2)  # type: ignore[no-any-return]


def pr_molar_volume(z: float, T: Q, P: Q) -> PrMolarVolumeResult:
    """Molar volume at a state, from its compressibility factor.

    Either admissible root may be passed to ``z`` - the vapour one gives the vapour
    volume and the liquid one the liquid volume.

    Raises:
        OutOfRangeError: if ``z <= 0`` or if ``T`` or ``P`` is not positive.

    See :func:`azoth.eos.reference.pr_molar_volume`.
    """
    return resolve(_PR_MOLAR_VOLUME)(z=z, T=T, P=P)  # type: ignore[no-any-return]


def pr_mass_density(M: Q, v: Q) -> PrMassDensityResult:
    """Mass density from a molar mass and a molar volume.

    ``M`` is the caller's - ``azoth.eos.component(name)`` looks it up - and note the unit
    is ``kg/mol``, not the ``g/mol`` tables usually quote.

    Raises:
        OutOfRangeError: if ``M <= 0`` or ``v <= 0``.

    See :func:`azoth.eos.reference.pr_mass_density`.
    """
    return resolve(_PR_MASS_DENSITY)(M=M, v=v)  # type: ignore[no-any-return]


def pr_peneloux_shift(omega: float, Tc: Q, Pc: Q) -> PrPenelouxShiftResult:
    """The Peng-Robinson Peneloux volume-translation parameter.

    The shift is subtracted from the untranslated molar volume: ``v_corr = v - c``,
    with ``v`` from :func:`pr_molar_volume`. It corrects the volume and density and
    does not change phase equilibrium.

    Raises:
        OutOfRangeError: if ``Tc`` or ``Pc`` is not positive.

    See :func:`azoth.eos.reference.pr_peneloux_shift`.
    """
    return resolve(_PR_PENELOUX_SHIFT)(omega=omega, Tc=Tc, Pc=Pc)  # type: ignore[no-any-return]


def srk_peneloux_shift(omega: float, Tc: Q, Pc: Q) -> SrkPenelouxShiftResult:
    """The Soave-Redlich-Kwong Peneloux volume-translation parameter.

    The shift is subtracted from the untranslated molar volume: ``v_corr = v - c``,
    with ``v`` from :func:`pr_molar_volume`. It corrects the volume and density and
    does not change phase equilibrium.

    Raises:
        OutOfRangeError: if ``Tc`` or ``Pc`` is not positive.

    See :func:`azoth.eos.reference.srk_peneloux_shift`.
    """
    return resolve(_SRK_PENELOUX_SHIFT)(omega=omega, Tc=Tc, Pc=Pc)  # type: ignore[no-any-return]


def heat_of_vaporization(
    c0: float, c1: float, c2: float, c3: float, Tc: Q, T: Q
) -> HeatOfVaporizationResult:
    """The pure-component heat of vaporisation at a temperature.

    ``c0..c3`` are the raw ``heatofvaporizationcoefs1..4`` NeqSim ships, in its
    internal scale, and ``Tc`` the critical temperature.

    Raises:
        OutOfRangeError: if ``Tc`` or ``T`` is not positive.

    See :func:`azoth.eos.reference.heat_of_vaporization`.
    """
    return resolve(_HEAT_OF_VAPORIZATION)(c0=c0, c1=c1, c2=c2, c3=c3, Tc=Tc, T=T)  # type: ignore[no-any-return]


def liquid_heat_capacity(
    c0: float, c1: float, c2: float, c3: float, c4: float, T: Q
) -> LiquidHeatCapacityResult:
    """The pure-component liquid heat capacity at a temperature.

    ``c0..c4`` are the raw ``cpliquid1..5`` NeqSim ships, in its internal scale.

    Raises:
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.liquid_heat_capacity`.
    """
    return resolve(_LIQUID_HEAT_CAPACITY)(c0=c0, c1=c1, c2=c2, c3=c3, c4=c4, T=T)  # type: ignore[no-any-return]


def antoine_vapor_pressure(
    A: float, B: float, C: float, D: float, E: float, form: str, Tc: Q, Pc: Q, T: Q
) -> AntoineVaporPressureResult:
    """The pure-component vapour pressure at a temperature.

    ``A``-``E`` are the raw ``ANTOINEA``-``ANTOINEE`` NeqSim ships, ``form`` one of
    ``"pow10"``, ``"pow10kpa"``, ``"exp"`` or ``"wagner"``, and ``Tc``/``Pc`` the
    critical constants.

    Raises:
        OutOfRangeError: if ``T``, ``Tc`` or ``Pc`` is not positive.

    See :func:`azoth.eos.reference.antoine_vapor_pressure`.
    """
    return resolve(_ANTOINE_VAPOR_PRESSURE)(A=A, B=B, C=C, D=D, E=E, form=form, Tc=Tc, Pc=Pc, T=T)  # type: ignore[no-any-return]


def rackett_molar_volume(omega: float, Tc: Q, Pc: Q, T: Q) -> RackettMolarVolumeResult:
    """The saturated liquid molar volume of a pure component, from the Rackett equation.

    Raises:
        OutOfRangeError: if ``Tc``, ``Pc`` or ``T`` is not positive.

    See :func:`azoth.eos.reference.rackett_molar_volume`.
    """
    return resolve(_RACKETT_MOLAR_VOLUME)(omega=omega, Tc=Tc, Pc=Pc, T=T)  # type: ignore[no-any-return]


def costald_molar_volume(
    omega: float, Tc: Q, Vc: Q, M: Q, rho_normal: Q, T: Q
) -> CostaldMolarVolumeResult:
    """The saturated liquid molar volume of a pure component, from the COSTALD equation.

    Raises:
        OutOfRangeError: if ``Tc``, ``Vc`` or ``T`` is not positive.

    See :func:`azoth.eos.reference.costald_molar_volume`.
    """
    return resolve(_COSTALD_MOLAR_VOLUME)(  # type: ignore[no-any-return]
        omega=omega, Tc=Tc, Vc=Vc, M=M, rho_normal=rho_normal, T=T
    )


def chung_viscosity(
    omega: float, Tc: Q, Vc: Q, M: Q, dipole: float, kappa: float, T: Q, V: Q
) -> ChungViscosityResult:
    """The gas dynamic viscosity of a pure component, from the Chung correlation.

    ``dipole`` is in debye and ``kappa`` the dimensionless viscosity correction
    factor; ``V`` is the gas's molar volume, which the dense-gas correction
    ``y = Vc/(6*V)`` consumes.

    Raises:
        OutOfRangeError: if ``Tc``, ``Vc``, ``T`` or ``V`` is not positive.

    See :func:`azoth.eos.reference.chung_viscosity`.
    """
    return resolve(_CHUNG_VISCOSITY)(  # type: ignore[no-any-return]
        omega=omega, Tc=Tc, Vc=Vc, M=M, dipole=dipole, kappa=kappa, T=T, V=V
    )


def chung_conductivity(
    Cv0: Q, M: Q, omega: float, Tc: Q, Vc: Q, dipole: float, kappa: float, T: Q
) -> ChungConductivityResult:
    """The gas thermal conductivity of a pure component, from the Chung correlation.

    ``Cv0`` is the ideal-gas heat capacity at constant volume at ``T`` (``Cp0 - R``;
    take ``Cp0`` from :func:`ideal_gas_cp`). ``dipole`` is in debye and ``kappa`` the
    dimensionless viscosity correction factor. The viscosity inside the correlation
    is the *dilute-gas* Chung viscosity, not :func:`chung_viscosity`'s dense-gas form.

    Raises:
        OutOfRangeError: if ``Tc``, ``Vc`` or ``T`` is not positive.

    See :func:`azoth.eos.reference.chung_conductivity`.
    """
    return resolve(_CHUNG_CONDUCTIVITY)(  # type: ignore[no-any-return]
        Cv0=Cv0, M=M, omega=omega, Tc=Tc, Vc=Vc, dipole=dipole, kappa=kappa, T=T
    )


def tyn_calus_diffusivity(VA: Q, VB: Q, T: Q, eta: Q) -> TynCalusDiffusivityResult:
    """The binary diffusion coefficient at infinite dilution, from the Tyn-Calus correlation.

    ``VA`` and ``VB`` are the solute and solvent liquid molar volumes at the normal
    boiling point (``M/rho_normal``, or the Tyn-Calus estimate ``0.285*Vc**1.048``
    when the density is unknown); ``eta`` is the solvent viscosity. All three are
    clamped to NeqSim's limits before the correlation is applied.

    Raises:
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.tyn_calus_diffusivity`.
    """
    return resolve(_TYN_CALUS_DIFFUSIVITY)(  # type: ignore[no-any-return]
        VA=VA, VB=VB, T=T, eta=eta
    )


def wilke_chang_diffusivity(phi: float, M: Q, T: Q, eta: Q, VA: Q) -> WilkeChangDiffusivityResult:
    """The binary diffusion coefficient at infinite dilution, from the Wilke-Chang correlation.

    ``phi`` is the solvent association parameter - resolve it from the solvent's
    name with :func:`wilke_chang_phi` (water 2.26, methanol 1.9, non-associated
    1.0). ``VA`` is the solute molar volume at the normal boiling point, and
    ``eta`` the solvent viscosity; both are clamped to NeqSim's limits before the
    correlation is applied.

    Raises:
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.wilke_chang_diffusivity`.
    """
    return resolve(_WILKE_CHANG_DIFFUSIVITY)(  # type: ignore[no-any-return]
        phi=phi, M=M, T=T, eta=eta, VA=VA
    )


def hayduk_minhas_diffusivity(form: str, VA: Q, T: Q, eta: Q) -> HaydukMinhasDiffusivityResult:
    """The binary diffusion coefficient at infinite dilution, from Hayduk-Minhas.

    ``form`` is ``"paraffin"`` (hydrocarbon solvent) or ``"aqueous"``. ``VA`` is
    the solute molar volume at the normal boiling point and ``eta`` the solvent
    viscosity; both are clamped to NeqSim's limits before the correlation is
    applied.

    Raises:
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.hayduk_minhas_diffusivity`.
    """
    return resolve(_HAYDUK_MINHAS_DIFFUSIVITY)(  # type: ignore[no-any-return]
        form=form, VA=VA, T=T, eta=eta
    )


def siddiqi_lucas_diffusivity(
    form: str, VA: Q, VB: Q, T: Q, eta: Q
) -> SiddiqiLucasDiffusivityResult:
    """The binary diffusion coefficient at infinite dilution, from Siddiqi-Lucas.

    ``form`` is ``"aqueous"`` or ``"organic"``. ``VA`` and ``VB`` are the solute
    and solvent molar volumes and ``eta`` the solvent viscosity.

    Raises:
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.siddiqi_lucas_diffusivity`.
    """
    return resolve(_SIDDIQI_LUCAS_DIFFUSIVITY)(  # type: ignore[no-any-return]
        form=form, VA=VA, VB=VB, T=T, eta=eta
    )


def co2_water_diffusivity(T: Q) -> Co2WaterDiffusivityResult:
    """The CO2-in-water binary diffusivity, from NeqSim's `CO2water` correlation.

    Temperature-only: the correlation carries no solute or solvent argument.

    Raises:
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.co2_water_diffusivity`.
    """
    return resolve(_CO2_WATER_DIFFUSIVITY)(T=T)  # type: ignore[no-any-return]


def wilke_viscosity(
    Tc: Sequence[Q],
    Vc: Sequence[Q],
    M: Sequence[Q],
    omega: Sequence[float],
    dipole: Sequence[float],
    kappa: Sequence[float],
    T: Q,
    V: Q,
    z: Sequence[float],
) -> WilkeViscosityResult:
    """The gas mixture dynamic viscosity, from Wilke's rule over Chung viscosities.

    Each pure-component viscosity is :func:`chung_viscosity`'s at the *mixture*
    molar volume ``V``, then mixed: ``mu = sum_i z_i mu_i / sum_j z_j phi_ij``.
    ``z`` is checked rather than renormalised - a composition that does not sum to
    one is a mistake, not a request to renormalise.

    The six per-component constants are the caller's: resolve them from a name with
    :func:`azoth.eos.components.entry`, which is what this model's own spec leaves to
    the caller.

    Raises:
        InvalidInputError: if the vectors disagree in length, or ``z`` is not a
            composition.
        OutOfRangeError: if ``T`` or ``V`` is not positive, or a component's
            ``Tc``/``Vc`` is not positive.

    See :func:`azoth.eos.reference.wilke_viscosity`.
    """
    return resolve(_WILKE_VISCOSITY)(  # type: ignore[no-any-return]
        Tc=Tc, Vc=Vc, M=M, omega=omega, dipole=dipole, kappa=kappa, T=T, V=V, z=z
    )


def mason_saxena_conductivity(
    Cv0: Sequence[Q],
    M: Sequence[Q],
    omega: Sequence[float],
    Tc: Sequence[Q],
    Vc: Sequence[Q],
    dipole: Sequence[float],
    kappa: Sequence[float],
    T: Q,
    z: Sequence[float],
) -> MasonSaxenaConductivityResult:
    """The gas mixture thermal conductivity, by Mason-Saxena mixing over Chung values.

    Each pure-component conductivity is :func:`chung_conductivity`'s at ``T``,
    then mixed: ``k = sum_i z_i k_i / sum_j z_j A_ij`` with
    ``A_ij = (1 + sqrt(k_i/k_j) (M_i/M_j)**0.25)**2 / sqrt(8 (1 + M_i/M_j))``.
    ``z`` is checked rather than renormalised.

    The seven per-component constants are the caller's: resolve them from a name
    with :func:`azoth.eos.components.entry`.

    Raises:
        InvalidInputError: if the vectors disagree in length, or ``z`` is not a
            composition.
        OutOfRangeError: if ``T`` is not positive, or a component's ``Tc``/``Vc``
            is not positive.

    See :func:`azoth.eos.reference.mason_saxena_conductivity`.
    """
    return resolve(_MASON_SAXENA_CONDUCTIVITY)(  # type: ignore[no-any-return]
        Cv0=Cv0, M=M, omega=omega, Tc=Tc, Vc=Vc, dipole=dipole, kappa=kappa, T=T, z=z
    )


def nrtl_activity_coefficients(
    T: Q,
    x: Sequence[float],
    Dij: Sequence[Sequence[Q]],
    alpha: Sequence[Sequence[float]],
) -> NrtlActivityCoefficientsResult:
    """The activity coefficients of a mixture, from NRTL (Renon-Prausnitz).

    ``Dij[i][j] = g_ij`` in Kelvin, ``tau_ij = g_ij / T`` and
    ``G_ij = exp(-alpha_ij tau_ij)``. ``alpha`` is symmetric and both matrices have a
    zero diagonal; ``x`` is checked rather than renormalised.

    The two matrices are the caller's: resolve them from name pairs with
    :func:`azoth.eos.components.nrtl_parameters`, which is what this model's own spec
    leaves to the caller.

    Raises:
        InvalidInputError: if the matrices are not ``N x N``, ``alpha`` is not
            symmetric, a diagonal is not zero, or ``x`` is not a composition.
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.nrtl_activity_coefficients`.
    """
    return resolve(_NRTL_ACTIVITY_COEFFICIENTS)(  # type: ignore[no-any-return]
        T=T, x=x, Dij=Dij, alpha=alpha
    )


def unifac_activity_coefficients(
    T: Q,
    x: Sequence[float],
    groups: Sequence[Sequence[float]],
    group_r: Sequence[float],
    group_q: Sequence[float],
    aij: Sequence[Sequence[Q]],
) -> UnifacActivityCoefficientsResult:
    """The activity coefficients of a mixture, from UNIFAC.

    ``groups[i][k]`` is the count of group ``k`` in component ``i`` over the union of
    the named components' groups, ``group_r``/``group_q`` are the per-group volume and
    surface area, and ``aij[m][n] = a_{main(m), main(n)}`` in Kelvin. The component
    volume and area follow from the group sums, the combinatorial term uses ``Z = 10``,
    and the residual is the standard ``ln gamma^R_i`` sum. ``x`` is checked rather than
    renormalised.

    The group tables are the caller's: resolve them from names with
    :func:`azoth.eos.components.unifac_parameters`, which is what this model's own spec
    leaves to the caller.

    Raises:
        InvalidInputError: if the shapes disagree, a group count is negative, or ``x``
            is not a composition.
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.unifac_activity_coefficients`.
    """
    return resolve(_UNIFAC_ACTIVITY_COEFFICIENTS)(  # type: ignore[no-any-return]
        T=T, x=x, groups=groups, group_r=group_r, group_q=group_q, aij=aij
    )


def uniquac_activity_coefficients(
    T: Q,
    x: Sequence[float],
    r: Sequence[float],
    q: Sequence[float],
    aij: Sequence[Sequence[Q]],
) -> UniquacActivityCoefficientsResult:
    """The activity coefficients of a mixture, from UNIQUAC (Abrams-Prausnitz).

    ``phi_i = r_i x_i / sum r_j x_j`` and ``theta_i = q_i x_i / sum q_j x_j`` are the
    volume and surface fractions, ``tau_ij = exp(-aij[i][j] / T)``, and the
    combinatorial and residual terms are the standard sums. ``aij`` is directional with
    a zero diagonal; ``x`` is checked rather than renormalised.

    The three parameters are the caller's: the van der Waals ``r``/``q`` are the group
    sums `eos.unifac_activity_coefficients` computes, and ``aij`` has no NeqSim table,
    so it is supplied directly.

    Raises:
        InvalidInputError: if the vectors disagree in length, ``aij`` is not ``N x N``
            with a zero diagonal, or ``x`` is not a composition.
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.uniquac_activity_coefficients`.
    """
    return resolve(_UNIQUAC_ACTIVITY_COEFFICIENTS)(  # type: ignore[no-any-return]
        T=T, x=x, r=r, q=q, aij=aij
    )


def wilson_activity_coefficients(
    T: Q,
    x: Sequence[float],
    M: Sequence[Q],
    Tc: Sequence[Q],
) -> WilsonActivityCoefficientsResult:
    """The activity coefficients of a mixture, from the paraffin-wax Wilson model.

    ``M`` is molar mass in kg/mol and ``Tc`` the critical temperature in K; ``Lambda_ij``
    is ``1.0`` for ``i == j`` or the heavier first component, else
    ``exp(-(lambda_j - lambda_i) / (R T))``. ``x`` is checked rather than renormalised;
    a supercritical component yields NaN, as in NeqSim.

    The two per-component constants are the caller's: resolve them from a name with
    :func:`azoth.eos.components.entry`.

    Raises:
        InvalidInputError: if the vectors disagree in length, or ``x`` is not a
            composition.
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.wilson_activity_coefficients`.
    """
    return resolve(_WILSON_ACTIVITY_COEFFICIENTS)(  # type: ignore[no-any-return]
        T=T, x=x, M=M, Tc=Tc
    )


def th_flash(
    mixture: Mixture, ideal_gas: IdealGasModel, T: Q, H: Q, z: list[float]
) -> ThFlashResult:
    """The pressure a mixture reaches at a temperature for a given molar enthalpy.

    The temperature-enthalpy companion to :func:`ph_flash`, with the specified pair
    exchanged: ``T`` is held fixed and ``P`` is solved for.

    Raises:
        InvalidInputError: if ``z`` or any ideal-gas vector is the wrong length, or if
            ``z`` is not a composition.
        OutOfRangeError: if ``T`` is not positive.
        SolverNotConvergedError: if the iteration reaches its cap.

    See :func:`azoth.eos.reference.th_flash`.
    """
    return resolve(_TH_FLASH)(  # type: ignore[no-any-return]
        mixture=mixture, ideal_gas=ideal_gas, T=T, H=H, z=z
    )


def ts_flash(
    mixture: Mixture, ideal_gas: IdealGasModel, T: Q, S: Q, z: list[float]
) -> TsFlashResult:
    """The pressure a mixture reaches at a temperature for a given molar entropy.

    Raises:
        InvalidInputError: if ``z`` or any ideal-gas vector is the wrong length, or if
            ``z`` is not a composition.
        OutOfRangeError: if ``T`` is not positive.
        SolverNotConvergedError: if the iteration reaches its cap.

    See :func:`azoth.eos.reference.ts_flash`.
    """
    return resolve(_TS_FLASH)(  # type: ignore[no-any-return]
        mixture=mixture, ideal_gas=ideal_gas, T=T, S=S, z=z
    )


def tu_flash(
    mixture: Mixture, ideal_gas: IdealGasModel, T: Q, U: Q, z: list[float]
) -> TuFlashResult:
    """The pressure a mixture reaches at a temperature for a given molar internal energy.

    Raises:
        InvalidInputError: if ``z`` or any ideal-gas vector is the wrong length, or if
            ``z`` is not a composition.
        OutOfRangeError: if ``T`` is not positive.
        SolverNotConvergedError: if the iteration reaches its cap.

    See :func:`azoth.eos.reference.tu_flash`.
    """
    return resolve(_TU_FLASH)(  # type: ignore[no-any-return]
        mixture=mixture, ideal_gas=ideal_gas, T=T, U=U, z=z
    )


def pu_flash(
    mixture: Mixture, ideal_gas: IdealGasModel, P: Q, U: Q, z: list[float]
) -> PuFlashResult:
    """The temperature a mixture reaches at a pressure for a given molar internal energy.

    Raises:
        InvalidInputError: if ``z`` or any ideal-gas vector is the wrong length, or if
            ``z`` is not a composition.
        OutOfRangeError: if ``P`` is not positive.
        SolverNotConvergedError: if the iteration reaches its cap.

    See :func:`azoth.eos.reference.pu_flash`.
    """
    return resolve(_PU_FLASH)(  # type: ignore[no-any-return]
        mixture=mixture, ideal_gas=ideal_gas, P=P, U=U, z=z
    )


def bubble_pressure(mixture: Mixture, T: Q, x: list[float]) -> BubblePressureResult:
    """The pressure at which a liquid of composition ``x`` first gives off vapour.

    The companion of :func:`dew_pressure`: the same iteration with the other phase
    held, which is why the argument is ``x`` here and ``y`` there. A shared name
    would have to be ``z``, which means the feed and would be wrong.

    ``x`` is the liquid's composition and is taken as given - whether that liquid is
    stable is not asked.

    Raises:
        InvalidInputError: if the mixture has one component - a pure component's
            bubble point is its saturation pressure, which :func:`pure_saturation`
            computes - or if ``x`` is not a composition.
        OutOfRangeError: if ``T`` is not positive, or if the mixture has no bubble
            point at this temperature. That is a real state and not a solver
            failure: a mixture above its critical condition has neither a bubble nor
            a dew point, and the error names ``min_t_over_tc``.

    See :func:`azoth.eos.reference.bubble_pressure`.
    """
    return resolve(_BUBBLE_PRESSURE)(mixture=mixture, T=T, x=x)  # type: ignore[no-any-return]


def critical_point(mixture: Mixture, z: list[float]) -> CriticalPointResult:
    """The critical point of a mixture of composition ``z``.

    ``z`` is the composition of the single phase whose critical point is wanted, not a
    feed being split - so unlike the flash's, this model does not decide what happens
    to it. Whether that composition could exist at the returned state is a different
    question and is not asked.

    The result is a **mixture** critical point, and its ``Z_c`` is what shows it: a pure
    component's is ``(1 - omega_b)/3`` exactly, and a mixture's varies with composition.
    Solving ``dP/dV = d2P/dV2 = 0`` instead - the obvious route - gives that same
    constant for every mixture there is, which is why this does not use it.

    Raises:
        InvalidInputError: if ``z`` is the wrong length, has a negative entry, or does
            not sum to one. It is checked rather than renormalised.
        SolverNotConvergedError: if the two conditions do not reach the tolerance in
            the spec's iteration cap. A critical point that is nearly one is not one.
        OutOfRangeError: if the state the iteration converged on is not a state.

    See :func:`azoth.eos.reference.critical_point`.
    """
    return resolve(_CRITICAL_POINT)(mixture=mixture, z=z)  # type: ignore[no-any-return]


def dew_pressure(mixture: Mixture, T: Q, y: list[float]) -> DewPressureResult:
    """The pressure at which a vapour of composition ``y`` first condenses.

    Raises:
        InvalidInputError: if the mixture has one component, or if ``y`` is not a
            composition.
        OutOfRangeError: if ``T`` is not positive, or if the mixture has no dew point
            at this temperature.

    See :func:`azoth.eos.reference.dew_pressure`.
    """
    return resolve(_DEW_PRESSURE)(mixture=mixture, T=T, y=y)  # type: ignore[no-any-return]


def ideal_gas_cp(
    cp_a: float, cp_b: float, cp_c: float, cp_d: float, cp_e: float, T: Q
) -> IdealGasCpResult:
    """The ideal-gas heat capacity at a temperature, from a caller-supplied polynomial.

    ``cp = cp_a + cp_b*T + cp_c*T**2 + cp_d*T**3 + cp_e*T**4``, dimensional throughout:
    the coefficients carry the powers of temperature in their units, so ``cp_a`` is a
    heat capacity and ``cp_b`` is one per kelvin. Those are the units the ``CPA``-``CPE``
    columns of NeqSim's ``COMP.csv`` are stored in, which is where they come from.

    ``T`` must lie inside the range the coefficients were fitted over, and that is not
    checked. A polynomial evaluated outside it turns over, ``cp`` goes negative, and
    the result carries ``OUT_OF_VALID_RANGE`` - which is the case this catches, not the
    more likely one where the value is simply a few per cent wrong.

    Raises:
        OutOfRangeError: if ``T`` is not positive.

    See :func:`azoth.eos.reference.ideal_gas_cp`.
    """
    return resolve(_IDEAL_GAS_CP)(  # type: ignore[no-any-return]
        cp_a=cp_a, cp_b=cp_b, cp_c=cp_c, cp_d=cp_d, cp_e=cp_e, T=T
    )


def molar_enthalpy_entropy(
    mixture: Mixture,
    ideal_gas: IdealGasModel,
    T: Q,
    P: Q,
    z: list[float],
    compressibility: float,
) -> MolarEnthalpyEntropyResult:
    """The absolute molar enthalpy and entropy of a mixture at a state.

    ``H = H_ig(T_ref) + integral Cp dT + H_dep`` and
    ``S = S_ig(T_ref) + integral Cp/T dT - R ln(P/P_ref) - R sum z_i ln z_i + S_dep``.

    **``ideal_gas`` carries the datum and nothing checks it.** Two enthalpies computed
    from different reference values are not comparable, and subtracting them gives a
    plausible number rather than an error - so a caller computing a difference must
    know both calls used the same one.

    ``compressibility`` is the cubic's root for the phase wanted, taken as given rather
    than solved for: which root describes the phase is a choice, and a caller holding a
    ``Z`` from :func:`pr_z_factor` or from :func:`pt_flash` has already made it.

    Raises:
        InvalidInputError: if the composition or any ideal-gas vector is the wrong
            length, or if ``z`` is not a composition.
        OutOfRangeError: if a temperature or pressure is not positive, or if the root
            is not admissible.

    See :func:`azoth.eos.reference.molar_enthalpy_entropy`.
    """
    return resolve(_MOLAR_ENTHALPY_ENTROPY)(  # type: ignore[no-any-return]
        mixture=mixture, ideal_gas=ideal_gas, T=T, P=P, z=z, compressibility=compressibility
    )


def pt_flash(mixture: Mixture, T: Q, P: Q, z: list[float]) -> PtFlashResult:
    """The two-phase flash of a mixture at a temperature and pressure.

    The deliverable of this namespace: how much of a feed is vapour, what the two
    phases are made of, and the fugacity coefficients that make it so::

        fluid = azoth.eos.mixture(
            [propane, butane], kij={(0, 1): 0.0}
        )
        r = azoth.eos.pt_flash(fluid, T=q(330, "K"), P=q(2.5e6, "Pa"), z=[0.6, 0.4])
        r.beta, r.x, r.y, r.phase

    ``z`` is **checked rather than renormalised** - a composition that does not sum
    to one is a mistake, and silently correcting it would make it invisible in every
    number downstream.

    **Read ``phase``, not ``beta``.** ``beta`` is ``None`` where there is no vapour
    fraction to report, which is one of two things: the feed has no two-phase
    solution at all (every K-value on the same side of one, and the result says
    ``all_liquid`` or ``all_vapour``), or the iteration converged to ``x = y = z``
    and the model cannot tell which single phase the feed is (``TRIVIAL``). A
    ``beta`` outside ``[0, 1]`` but present is the negative flash - a real reading,
    reported with ``OUT_OF_VALID_RANGE``.

    There is **no stability test**: a converged split is a stationary point of the
    flash equations, not a proof that the feed was unstable. See the model spec.

    Raises:
        InvalidInputError: if ``z`` is the wrong length, has a negative entry, or
            does not sum to one, or if the mixture's ``kij`` is malformed.
        OutOfRangeError: if ``T`` or ``P`` is not positive.
        SolverNotConvergedError: if the iteration hits its cap.

    See :func:`azoth.eos.reference.pt_flash`.
    """
    return resolve(_PT_FLASH)(mixture=mixture, T=T, P=P, z=z)  # type: ignore[no-any-return]


def ph_flash(
    mixture: Mixture, ideal_gas: IdealGasModel, P: Q, H: Q, z: list[float]
) -> PhFlashResult:
    """The temperature a mixture reaches at a pressure when given a duty.

    The model the process layer needs. A heater, a cooler, a compressor, a valve: each
    knows the pressure a stream leaves at and the energy it added, and none of them
    knows the temperature that results. This is that temperature, and the phase split
    at it::

        r = azoth.eos.ph_flash(fluid, ig, P=q(20, "bar"), H=q(-6723.0, "J/mol"), z=[0.6, 0.4])
        r.T, r.phase, r.beta

    **``H`` is a difference from the datum ``ideal_gas`` carries**, not an absolute
    quantity. Two calls with different reference values are not comparable, and their
    difference is a plausible number rather than an error - the same caveat
    :func:`molar_enthalpy_entropy` carries, for the same reason.

    **Read ``phase``, not ``beta``.** ``beta`` is ``None`` for a single-phase feed.
    That is not a missing value: the flash reports an *extrapolated* split below the
    bubble point or above the dew point - values like 1.9 are ordinary - and it is not
    the vapour fraction of anything.

    Raises:
        InvalidInputError: if ``z`` or any ideal-gas vector is the wrong length, or if
            ``z`` is not a composition.
        OutOfRangeError: if ``P`` is not positive, or a range check on the answer fails.
        SolverNotConvergedError: if no temperature on the model's bracket produces the
            requested enthalpy, or if the bisection hits its cap.

    See :func:`azoth.eos.reference.ph_flash`.
    """
    return resolve(_PH_FLASH)(  # type: ignore[no-any-return]
        mixture=mixture, ideal_gas=ideal_gas, P=P, H=H, z=z
    )


def ps_flash(
    mixture: Mixture, ideal_gas: IdealGasModel, P: Q, S: Q, z: list[float]
) -> PsFlashResult:
    """The temperature a mixture reaches at a pressure when expanded isentropically.

    The companion to :func:`ph_flash`, for the unit operations that conserve entropy
    rather than energy: a compressor or an expander assumed ideal, a turbine, a nozzle::

        r = azoth.eos.ps_flash(fluid, ig, P=q(20, "bar"), S=q(-39.078, "J/(mol*K)"), z=[0.6, 0.4])
        r.T, r.phase, r.beta

    **``S`` is a difference from the datum ``ideal_gas`` carries**, not an absolute
    quantity - the same caveat :func:`molar_enthalpy_entropy` carries, for the same
    reason.

    The two phases are summed at *their own* compositions, so the result carries the
    entropy of mixing. That is the physically correct assembly and it is not optional:
    summing the phases at the feed composition would conserve entropy across a phase
    change, which is wrong.

    Raises:
        InvalidInputError: if ``z`` or any ideal-gas vector is the wrong length, or if
            ``z`` is not a composition.
        OutOfRangeError: if ``P`` is not positive, or a range check on the answer fails.
        SolverNotConvergedError: if no temperature on the model's bracket produces the
            requested entropy, or if the bisection hits its cap.

    See :func:`azoth.eos.reference.ps_flash`.
    """
    return resolve(_PS_FLASH)(  # type: ignore[no-any-return]
        mixture=mixture, ideal_gas=ideal_gas, P=P, S=S, z=z
    )


def tv_flash(
    mixture: Mixture, ideal_gas: IdealGasModel, T: Q, V: Q, z: list[float]
) -> TvFlashResult:
    """The pressure a mixture reaches at a temperature for a given molar volume.

    The volume companion to :func:`ph_flash`, for a closed vessel at a known temperature
    and volume: ``V`` is the one-mole-basis molar volume, and the answer is the pressure
    the equilibrium split produces at it.

    **Read ``phase``, not ``beta``**, for the same reason as :func:`ph_flash`.

    Raises:
        InvalidInputError: if ``z`` or any ideal-gas vector is the wrong length, or if
            ``z`` is not a composition.
        OutOfRangeError: if ``T`` or ``V`` is not positive.
        SolverNotConvergedError: if the iteration reaches its cap.

    See :func:`azoth.eos.reference.tv_flash`.
    """
    return resolve(_TV_FLASH)(  # type: ignore[no-any-return]
        mixture=mixture, ideal_gas=ideal_gas, T=T, V=V, z=z
    )


def pv_flash(
    mixture: Mixture, ideal_gas: IdealGasModel, P: Q, V: Q, z: list[float]
) -> PvFlashResult:
    """The temperature a mixture reaches at a pressure for a given molar volume.

    The companion to :func:`tv_flash` with the specified pair exchanged: ``P`` is held
    fixed and ``T`` is solved for.

    Raises:
        InvalidInputError: if ``z`` or any ideal-gas vector is the wrong length, or if
            ``z`` is not a composition.
        OutOfRangeError: if ``P`` or ``V`` is not positive.
        SolverNotConvergedError: if the iteration reaches its cap.

    See :func:`azoth.eos.reference.pv_flash`.
    """
    return resolve(_PV_FLASH)(  # type: ignore[no-any-return]
        mixture=mixture, ideal_gas=ideal_gas, P=P, V=V, z=z
    )


def stability_test(mixture: Mixture, T: Q, P: Q, z: list[float]) -> StabilityTestResult:
    """Whether a mixture at a temperature and pressure is stable as a single phase.

    The question :func:`pt_flash` cannot ask. Successive substitution finds *a*
    stationary point; whether the feed was stable to begin with is a different
    question, and a flash that converges to ``x = y = z`` has demonstrated that its
    own starting point was not a split - not that the feed is single phase. This is
    the model that answers it, by Michelsen's tangent-plane criterion: two trial
    phases, seeded from Wilson K-values, are each iterated to a stationary point of
    the tangent-plane distance, and the feed is unstable if either lands below the
    tangent plane through the feed::

        r = azoth.eos.stability_test(fluid, T=q(330, "K"), P=q(25, "bar"), z=[0.6, 0.4])
        r.verdict, r.tm, r.iterations

    **``stable`` means these two trials found nothing, not that no split exists.**
    Both trials are placed by a gas-liquid correlation, so a feed unstable to a
    *liquid-liquid* split comes back ``stable`` and nothing here detects it. And
    ``unstable`` says a split exists without saying what it is or how many phases it
    has - that is :func:`pt_flash`'s question, and for three phases neither model
    answers it.

    ``tm`` and ``w`` are one entry per trial in a fixed order - **vapour-like first**,
    then liquid-like - and two entries always, so a caller reads ``tm[0]`` as the
    vapour-like trial. A row of ``w`` equal to the feed is a trivial stationary
    point: the trial found the feed's own and says nothing about whether another
    exists. Its ``tm`` is zero to rounding, which is why the instability threshold is
    ``-1e-8`` rather than zero - and why the verdict cannot be read off a single
    distance.

    ``z`` is **checked rather than renormalised**, as everywhere in this namespace.

    Raises:
        InvalidInputError: if ``z`` is the wrong length, has a negative entry, or
            does not sum to one, or if the mixture's ``kij`` is malformed.
        OutOfRangeError: if ``T`` or ``P`` is not positive.
        SolverNotConvergedError: if a trial hits its cap. A tangent-plane distance
            bounds stability only at a stationary point, so an unconverged trial is
            an error rather than a trial quietly discarded.

    See :func:`azoth.eos.reference.stability_test`.
    """
    return resolve(_STABILITY_TEST)(mixture=mixture, T=T, P=P, z=z)  # type: ignore[no-any-return]


def pure_saturation(Tc: Q, Pc: Q, omega: float, T: Q) -> PureSaturationResult:
    """The saturation pressure of a pure component at a temperature.

    ``T`` must be below ``Tc`` - above the critical temperature there is no saturation
    pressure, and this refuses rather than returning an extrapolation.

    Raises:
        OutOfRangeError: if ``T``, ``Tc`` or ``Pc`` is not positive, or if
            ``T >= Tc``.
        SolverNotConvergedError: if the search hits its cap.

    See :func:`azoth.eos.reference.pure_saturation`.
    """
    return resolve(_PURE_SATURATION)(Tc=Tc, Pc=Pc, omega=omega, T=T)  # type: ignore[no-any-return]
