//! GENERATED FILE - DO NOT EDIT BY HAND.
//!
//! Generated by `tools/gen_registry.py` from:
//!
//!   - specs/calcs/characterization/tbp_cut_properties.toml
//!
//! Tables for the `characterization` namespace. Every namespace has its own generated
//! file, because a crate is the unit of compilation and a calculation must be able
//! to read its own bounds without depending on another namespace's crate. The
//! types these tables are built from are shared - see `azoth_core::spec`.
//!
//! These tables are what make the specs authoritative at runtime rather than
//! merely descriptive. Each calc reads its own range checks from here, so a
//! bound changed in a spec file changes the code's behaviour with no second
//! edit - and `cargo test` fails if the two ever disagree.
//
// A case's expected values are **recorded measurements**, so a literal that lands on
// a mathematical constant is a coincidence of the state rather than a hand-written
// approximation of one - `tray_hydraulics`' 1 m column answers an area of pi/4, and
// `clippy::approx_constant` reads that as a constant written out by hand.
#![allow(clippy::approx_constant)]

use azoth_core::{Band, CalcSpec, RangeCheck, Severity, SpecCheck, TestCase, WarningCode};

/// Registry entry for `characterization.tbp_cut_properties`.
static TBP_CUT_PROPERTIES_CHECKS: &[SpecCheck] = &[
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "molar_mass",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a molar mass; four coefficients divide by it and `Twu` takes its logarithm",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "density",
            min: Some(0.0),
            min_inclusive: false,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a specific gravity; `RiaziDaubert` and `Cavett` raise it to a fractional power and divide by it",
        },
    },
    SpecCheck {
        on_input: true,
        check: RangeCheck {
            quantity: "boiling_point",
            min: Some(0.0),
            min_inclusive: true,
            max: None,
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Error,
            code: WarningCode::OutOfValidRange,
            rationale: "a boiling point; zero and below mean 'not supplied' and select the correlation, so a supplied one must be positive",
        },
    },
    SpecCheck {
        on_input: false,
        check: RangeCheck {
            quantity: "acentric_factor",
            min: Some(-1.0),
            min_inclusive: true,
            max: Some(2.0),
            max_inclusive: true,
            equals: None,
            band: Band::Outside,
            severity: Severity::Warning,
            code: WarningCode::OutOfValidRange,
            rationale: "**Measured outside this** above `M = 1120` g/mol, where the heavy set gives a boiling point above the critical temperature: `-44.6358323245519` at `M = 1121`, `d = 1.0`. A Pitzer factor outside `[-1, 2]` describes no fluid, so it is reported rather than passed on.",
        },
    },
];

static TBP_CUT_PROPERTIES_TESTS: &[TestCase] = &[
    TestCase {
        id: "pedersen_srk_agrees_with_the_seam_id",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("molar_mass", 0.5), ("density", 880.0)],
        flags: &[],
        lists: &[],
        strings: &[("model", "pedersen_srk")],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("tc", 891.945256085426),
            ("pc", 1196293.59599742),
            ("boiling_temperature", 746.89),
            ("acentric_factor", 1.36586663262266),
            ("attraction_exponent", 2.228110216),
            ("watson_k", 12.5418146375894),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "pedersen_srk_heavy_oil_is_a_no_op",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("molar_mass", 0.5), ("density", 880.0)],
        flags: &[],
        lists: &[],
        strings: &[("model", "pedersen_srk_heavy_oil")],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("tc", 891.945256085426),
            ("pc", 1196293.59599742),
            ("boiling_temperature", 746.89),
            ("acentric_factor", 1.36586663262266),
            ("attraction_exponent", 2.228110216),
            ("watson_k", 12.5418146375894),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "riazi_daubert_switches_to_its_parent_above_mw_300",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("molar_mass", 0.3), ("density", 850.0)],
        flags: &[],
        lists: &[],
        strings: &[("model", "riazi_daubert")],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("tc", 815.802701858322),
            ("pc", 1081341.69675997),
            ("boiling_temperature", 644.547792011568),
            ("acentric_factor", 0.697599640892113),
            ("watson_k", 12.3620439797047),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "cavett_applies_its_api_correction_below_30",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("molar_mass", 0.5), ("density", 880.0)],
        flags: &[],
        lists: &[],
        strings: &[("model", "cavett")],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("tc", 894.305850190858),
            ("pc", 735341.797507176),
            ("boiling_temperature", 765.014651094374),
            ("acentric_factor", 1.1827925271406),
            ("watson_k", 12.6424549207867),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "standing_is_riazi_daubert_without_the_switch",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("molar_mass", 0.5), ("density", 880.0)],
        flags: &[],
        lists: &[],
        strings: &[("model", "standing")],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("tc", 942.447643628006),
            ("pc", 522599.858109319),
            ("boiling_temperature", 785.228404434496),
            ("acentric_factor", 1.21363914242666),
            ("watson_k", 12.752837620579),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "twu_solves_its_n_alkane_molar_mass",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("molar_mass", 0.5), ("density", 880.0)],
        flags: &[],
        lists: &[],
        strings: &[("model", "twu")],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("tc", 917.899204856315),
            ("pc", 724270.609562486),
            ("boiling_temperature", 785.228404434496),
            ("acentric_factor", 1.1666832492598),
            ("watson_k", 12.752837620579),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "the_pr_family_differs_from_the_srk_family",
        kind: "reference",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("molar_mass", 0.5), ("density", 880.0)],
        flags: &[],
        lists: &[],
        strings: &[("model", "pedersen_pr")],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("tc", 974.87977295161),
            ("pc", 1239174.46749789),
            ("boiling_temperature", 746.89),
            ("acentric_factor", 0.526722654332295),
            ("attraction_exponent", 1.897865692),
            ("watson_k", 12.5418146375894),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    TestCase {
        id: "round_trip_units",
        kind: "property",
        property: Some("unit_round_trip"),
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[],
        flags: &[],
        lists: &[],
        strings: &[],
        vectors: &[],
        matrices: &[],
        expected: &[],
        expected_vectors: &[],
        expected_strings: &[],
    },
];

/// Registered spec for `characterization.tbp_cut_properties`.
///
/// Public and addressable directly, so a calc can hold `&TBP_CUT_PROPERTIES_SPEC` with no
/// lookup and no failure path. A calc whose spec is missing is a build-time
/// invariant, not a runtime condition, and this shape makes it unrepresentable
/// rather than something to handle.
pub static TBP_CUT_PROPERTIES_SPEC: CalcSpec = CalcSpec {
    id: "characterization.tbp_cut_properties",
    checks: TBP_CUT_PROPERTIES_CHECKS,
    solver: None,
    worked_example: TestCase {
        id: "lee_kesler_worked_example",
        kind: "worked_example",
        property: None,
        status: "active",
        skip_reason: None,
        tolerance: 1e-12,
        numbers: &[("molar_mass", 0.5), ("density", 880.0)],
        flags: &[],
        lists: &[],
        strings: &[("model", "lee_kesler")],
        vectors: &[],
        matrices: &[],
        expected: &[
            ("tc", 906.211218915845),
            ("pc", 663946.297092384),
            ("boiling_temperature", 785.228404434496),
            ("acentric_factor", 1.43229568844577),
            ("watson_k", 12.752837620579),
        ],
        expected_vectors: &[],
        expected_strings: &[],
    },
    tests: TBP_CUT_PROPERTIES_TESTS,
};

/// Every calculation in the registry, sorted by id.
static ALL_SPECS: &[&CalcSpec] = &[&TBP_CUT_PROPERTIES_SPEC];

/// All specs, in a stable order.
#[must_use]
pub fn specs() -> &'static [&'static CalcSpec] {
    ALL_SPECS
}

/// Look up a spec by id.
#[must_use]
pub fn spec(id: &str) -> Option<&'static CalcSpec> {
    ALL_SPECS.iter().copied().find(|s| s.id == id)
}
